/* Sumber kandungan — Sains KSSM Tingkatan 3, Bidang 2.0 Respirasi.
   Jalankan `node bina.js t3b2` untuk menyemak dan menghasilkan bank-t3b2.js.

   Standard Prestasi disalin kata demi kata daripada DSKP KSSM Sains
   Tingkatan 3, Bahagian Pembangunan Kurikulum, April 2017, muka 52.

   Nota: fail ini dihasilkan daripada bank yang sedia ada semasa saluran
   kandungan diseragamkan, jadi kedudukan jawapan di dalamnya sudah
   diagihkan. Sunting fail ini, bukan bank. */

const SPI = [
 "Mengingat kembali pengetahuan dan kemahiran sains mengenai respirasi.",
 "Memahami respirasi serta dapat menjelaskan kefahaman tersebut.",
 "Mengaplikasikan pengetahuan mengenai respirasi untuk menerangkan kejadian atau fenomena alam dan melaksanakan tugasan mudah.",
 "Menganalisis pengetahuan mengenai respirasi dalam konteks penyelesaian masalah mengenai kejadian atau fenomena alam.",
 "Menilai pengetahuan mengenai respirasi dalam konteks penyelesaian masalah dan membuat keputusan untuk melaksanakan satu tugasan.",
 "Mereka cipta menggunakan pengetahuan dan kemahiran sains mengenai respirasi dalam konteks penyelesaian masalah atau membuat keputusan atau dalam melaksanakan aktiviti/tugasan dalam situasi baharu secara kreatif dan inovatif dengan mengambil kira nilai sosial/ekonomi/budaya masyarakat."
];

/* ---------- lampiran ---------- */

const L_GAS = "<div class=\"scrollx\"><table class=\"datatable\"><thead><tr><th>Gas</th><th class=\"n\">Disedut (%)</th><th class=\"n\">Dihembus (%)</th></tr></thead><tbody><tr><td>Nitrogen</td><td class=\"n\">78.0</td><td class=\"n\">78.0</td></tr><tr><td>Oksigen</td><td class=\"n\">21.0</td><td class=\"n\">16.0</td></tr><tr><td>Karbon dioksida</td><td class=\"n\">0.04</td><td class=\"n\">4.0</td></tr><tr><td>Wap air</td><td class=\"n\">sedikit</td><td class=\"n\">tepu</td></tr></tbody></table></div>";

const L_KLINIK = "<div class=\"scrollx\"><table class=\"datatable\"><thead><tr><th>Individu</th><th class=\"n\">Kapasiti vital (L)</th><th class=\"n\">Nafas rehat (min&#8315;&#185;)</th><th class=\"n\">PEFR (L min&#8315;&#185;)</th><th>Latar</th></tr></thead><tbody><tr><td>En. Fauzi, 45</td><td class=\"n\">2.6</td><td class=\"n\">22</td><td class=\"n\">290</td><td>Merokok 20 tahun</td></tr><tr><td>Mei Ling, 16</td><td class=\"n\">4.1</td><td class=\"n\">14</td><td class=\"n\">480</td><td>Atlet olahraga</td></tr><tr><td>Suriani, 15</td><td class=\"n\">3.0</td><td class=\"n\">18</td><td class=\"n\">340</td><td>Asma terkawal</td></tr></tbody></table></div><p class=\"qnote\">Kapasiti vital ialah isi padu udara terbanyak yang boleh dihembus selepas tarikan nafas paling dalam. PEFR (bacaan aliran puncak) ialah kelajuan maksimum udara dihembus keluar. Julat sihat: kapasiti vital 3.5&ndash;4.8 L &middot; nafas rehat 12&ndash;18 &middot; PEFR 400&ndash;550.</p>";

const L_TEKANAN = {
  jenis: "graf", titik: true, setiap: 2, grid: 4,
  x: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  yMin: 2.0, yMaks: 3.6,
  yKanan: { min: 100.9, maks: 101.7 },
  fasa: { dari: 0, hingga: 3, label: "FASA P" },
  siri: [
    { label: "Isi padu toraks (L, kiri)", warna: "ungu",
      y: [2.4, 2.9, 3.4, 3.5, 3.0, 2.5, 2.4, 2.9, 3.4] },
    { label: "Tekanan peparu (kPa, kanan)", warna: "merah", paksi: "kanan",
      y: [101.3, 101.0, 101.0, 101.3, 101.6, 101.6, 101.3, 101.0, 101.0] }
  ],
  xLabel: "Masa (saat)",
  kapsyen: "Rajah 1 · Satu kitaran pernafasan semasa rehat. Tekanan atmosfera ialah 101.3 kPa.",
  alt: "Graf dua paksi: isi padu rongga toraks naik dari 2.4 ke 3.5 liter semasa fasa P, manakala tekanan peparu turun di bawah 101.3 kPa pada masa yang sama"
};

/* ---------- hentian ---------- */

const ARAS = [

{n:1, tempat:"Hidung & Trakea", sk:"2.1 Sistem respirasi", kadNama:"Silia", kadEm:"🧹", kadFakta:"Silia ialah bulu halus pada dinding trakea. Ia berdegup ke atas kira-kira 1000 kali seminit untuk menyapu mukus keluar dari salur udara.", bosKadNama:"Gelang Rawan", bosKadEm:"🦴", bosKadFakta:"Trakea manusia ada 16 hingga 20 gelang rawan berbentuk C yang tak pernah membenarkannya kemek.",
 soalan:[
 {"j":"pilih","t":"Salur udara yang disokong gelang rawan berbentuk C ialah:","p":["Trakea","Esofagus","Alveolus","Diafragma"],"b":0,"u":"Gelang rawan menahan trakea daripada kemek."},
 {"j":"susun","t":"Susun laluan udara dari luar badan ke tempat pertukaran gas.","p":["Rongga hidung","Trakea","Bronkus","Bronkiol","Alveolus"],"b":[0,1,2,3,4],"u":"Setiap cabang jadi lebih kecil sehingga berakhir di alveolus."},
 {"j":"pilih","t":"Apakah fungsi silia (bulu halus) pada dinding trakea?","p":["Menyapu mukus berhabuk keluar dari salur udara","Menyerap oksigen terus ke dalam aliran darah","Menghasilkan tenaga untuk menggerakkan udara","Menapis karbon dioksida keluar daripada darah"],"b":0,"u":"Mukus memerangkap, silia menyapu."},
 {"j":"pilih","t":"Gas yang diperlukan untuk respirasi sel ialah:","p":["Nitrogen","Karbon dioksida","Oksigen","Helium"],"b":2,"u":"Oksigen mengoksidakan glukosa untuk bebaskan tenaga."},
 {"j":"pilih","t":"Otot berbentuk kubah di bawah peparu ialah:","p":["Otot interkosta","Pleura","Epiglotis","Diafragma"],"b":3,"u":"Diafragma memisahkan rongga toraks daripada rongga abdomen."},
 {"j":"pilih","t":"Unit terkecil tempat pertukaran gas berlaku ialah:","p":["Alveolus","Bronkus","Trakea","Peparu"],"b":0,"u":"Kira-kira 300 juta alveolus dalam sepasang peparu."},
 {"j":"pilih","t":"Hasil buangan respirasi sel ialah:","p":["Karbon dioksida dan air","Oksigen dan karbon dioksida","Nitrogen dan air","Glukosa dan tenaga"],"b":0,"u":"Glukosa dan oksigen masuk, karbon dioksida dan air keluar."},
 {"j":"pilih","t":"Rambut halus dalam rongga hidung berfungsi untuk:","p":["Menapis zarah habuk yang besar","Memanaskan darah dalam hidung","Menghasilkan mukus pelembap","Mengecut semasa menarik nafas"],"b":0,"u":"Hidung menapis, memanaskan dan melembapkan udara."}],
 bos:{"j":"banyak","t":"Pilih SEMUA struktur yang merupakan sebahagian sistem respirasi manusia.","p":["Trakea","Bronkiol","Bronkus","Alveolus","Esofagus","Aorta"],"b":[0,1,2,3],"u":"Esofagus salur makanan, aorta salur darah. Kedua-duanya bukan sistem respirasi."}},

{n:2, tempat:"Bronkus & Bronkiol", sk:"2.1 Mekanisme pernafasan", kadNama:"Diafragma", kadEm:"🛡", kadFakta:"Diafragma menyumbang kira-kira 75 peratus perubahan isi padu toraks semasa pernafasan rehat.", bosKadNama:"Surfaktan", bosKadEm:"🫧", bosKadFakta:"Surfaktan melapisi alveolus supaya ia tidak melekat dan kuncup selepas setiap hembusan.",
 soalan:[
 {"j":"susun","t":"Susun proses tarik nafas mengikut urutan yang betul.","p":["Otot interkosta luar dan diafragma mengecut","Sangkar rusuk naik, diafragma jadi mendatar","Isi padu rongga toraks bertambah","Tekanan udara dalam peparu turun","Udara luar mengalir masuk"],"b":[0,1,2,3,4],"u":"Otot dulu, isi padu, tekanan, barulah udara bergerak."},
 {"j":"pilih","t":"Mengapakah dinding alveolus setebal satu sel sahaja?","p":["Supaya jarak resapan pendek dan pertukaran gas cepat","Supaya darah boleh mengalir terus ke dalam alveolus","Supaya alveolus lebih ringan dan mudah mengembang","Supaya lebih banyak mukus dapat dihasilkan di situ"],"b":0,"u":"Jarak pendek bermakna resapan laju."},
 {"j":"pilih","t":"Apakah maksud respirasi sel?","p":["Pengoksidaan glukosa dalam sel untuk bebaskan tenaga","Pergerakan udara masuk dan keluar dari peparu","Resapan oksigen dari alveolus ke dalam kapilari darah","Pengangkutan oksigen oleh hemoglobin ke seluruh badan"],"b":0,"u":"Pernafasan ialah pergerakan udara, respirasi sel ialah tindak balas kimia."},
 {"j":"pilih","t":"Mengapakah alveolus banyak dan kecil, bukan satu kantung besar?","p":["Supaya jumlah luas permukaan jauh lebih besar","Supaya peparu lebih ringan dan mudah mengembang","Supaya udara bergerak lebih perlahan di dalam peparu","Supaya mukus mudah terkumpul dan memerangkap habuk"],"b":0,"u":"Jumlah luas permukaan alveolus manusia hampir sebesar gelanggang badminton."},
 {"j":"pilih","t":"Mengapakah permukaan dalam alveolus sentiasa lembap?","p":["Supaya gas larut dahulu sebelum meresap merentasi dinding","Supaya bakteria tidak dapat hidup di permukaan alveolus","Supaya udara yang disedut menjadi lebih sejuk dan segar","Supaya dinding alveolus tidak pecah apabila mengembang"],"b":0,"u":"Gas mesti larut dahulu baru boleh meresap."},
 {"j":"pilih","t":"Apakah perbezaan utama antara pernafasan dan respirasi?","p":["Pernafasan ialah pergerakan udara, respirasi ialah tindak balas dalam sel","Pernafasan ialah tindak balas dalam sel, respirasi ialah pergerakan udara","Pernafasan berlaku waktu siang, respirasi berlaku pada waktu malam","Pernafasan hanya pada manusia, respirasi hanya berlaku pada tumbuhan"],"b":0,"u":"Ini istilah yang paling kerap tertukar dalam bab ini."},
 {"j":"susun","t":"Susun proses hembus nafas mengikut urutan yang betul.","p":["Otot interkosta luar dan diafragma mengendur","Sangkar rusuk turun, diafragma melengkung ke atas","Isi padu rongga toraks berkurang","Tekanan udara dalam peparu naik","Udara keluar dari peparu"],"b":[0,1,2,3,4],"u":"Hembusan rehat berlaku tanpa tenaga, otot hanya mengendur."},
 {"j":"pilih","t":"Mengapakah alveolus dikelilingi rangkaian kapilari darah yang padat?","p":["Oksigen cepat dibawa pergi, jadi kecerunan kepekatan kekal tinggi","Alveolus memerlukan bekalan makanan yang banyak daripada darah","Darah menyejukkan alveolus supaya suhunya kekal rendah","Kapilari menghalang alveolus daripada mengembang secara berlebihan"],"b":0,"u":"Darah yang sentiasa mengalir menjaga kecerunan supaya resapan tak berhenti."}],
 bos:{"j":"pilih","t":"Apakah yang berlaku jika permukaan alveolus dilapisi lapisan mukus yang tebal?","p":["Kadar resapan oksigen berkurang kerana jarak resapan bertambah","Kadar resapan oksigen bertambah kerana gas lebih mudah larut","Tiada kesan kerana oksigen meresap terus melalui dinding darah","Alveolus mengembang lebih besar untuk menampung lapisan mukus"],"b":0,"u":"Inilah sebabnya jangkitan peparu menyebabkan sesak nafas."}},

{n:3, tempat:"Alveolus", sk:"2.2 Pertukaran gas", kadNama:"Air Kapur", kadEm:"🧪", kadFakta:"Air kapur bertukar keruh dengan udara hembus kerana kandungan karbon dioksidanya 100 kali ganda udara biasa.", bosKadNama:"Isi Padu Tidal", bosKadEm:"💨", bosKadFakta:"Setiap nafas biasa membawa masuk kira-kira 500 ml udara, dipanggil isi padu tidal.", lampiran:"gas",
 soalan:[
 {"j":"nombor","t":"Berdasarkan jadual, berapakah beza peratus oksigen antara udara disedut dan udara dihembus?","b":5,"tol":0.05,"suf":"%","u":"21.0 tolak 16.0 bersamaan 5.0. Maknanya kira-kira satu perempat daripada oksigen yang disedut diserap oleh badan, dan selebihnya dihembus keluar semula."},
 {"j":"pilih","t":"Mengapakah peratus nitrogen tidak berubah?","p":["Nitrogen tidak digunakan dalam respirasi sel","Nitrogen terlalu besar untuk meresap ke darah","Nitrogen dihasilkan semula oleh sel badan","Nitrogen bergabung terus dengan hemoglobin"],"b":0,"u":"Nitrogen hanya penumpang, masuk dan keluar sama banyak."},
 {"j":"pilih","t":"Selepas berlari 100 m, Danial bernafas lebih laju dan dalam. Mengapa?","p":["Respirasi sel meningkat, lebih banyak karbon dioksida perlu dibuang","Suhu badan naik lalu menyebabkan semua alveolus mengembang serentak","Otot memerlukan lebih banyak nitrogen untuk membina semula tisu","Darah menjadi pekat, jadi badan perlu menyedut lebih banyak wap air"],"b":0,"u":"Otak mengesan kenaikan karbon dioksida, bukan kekurangan oksigen."},
 {"j":"nombor","t":"Berapa kali ganda peratus karbon dioksida meningkat dari udara disedut ke udara dihembus?","b":100,"tol":1,"suf":"kali","u":"0.04 peratus naik ke 4.0 peratus, iaitu 100 kali ganda."},
 {"j":"pilih","t":"Mengapakah udara yang dihembus lebih panas dan lembap?","p":["Udara menyerap haba dan wap air dari permukaan alveolus","Karbon dioksida dalam udara hembus bersifat panas dan lembap","Udara termampat semasa hembusan lalu menjadi panas dan basah","Silia menghasilkan haba dan wap air semasa bergerak menyapu"],"b":0,"u":"Sebab itu cermin berkabus bila awak hembus nafas padanya."},
 {"j":"pilih","t":"Udara hembus ditiup ke dalam air kapur dan air kapur menjadi keruh. Ini membuktikan:","p":["Udara hembus mengandungi lebih banyak karbon dioksida","Udara hembus mengandungi lebih banyak wap air dan oksigen","Udara hembus jauh lebih panas daripada udara sedutan","Udara hembus mengandungi bakteria dari dalam peparu"],"b":0,"u":"Air kapur ialah ujian khusus untuk karbon dioksida."},
 {"j":"pilih","t":"Pendaki di puncak gunung tinggi cepat tercungap walaupun sihat. Mengapa?","p":["Tekanan udara rendah, jadi kurang oksigen meresap setiap nafas","Suhu yang sejuk menyekat pergerakan diafragma dan otot rusuk","Angin kencang menolak udara keluar dari peparu dengan cepat","Nitrogen di kawasan tinggi lebih pekat dan menghalang oksigen"],"b":0,"u":"Peratus oksigen sama, tetapi tekanan separanya jauh lebih rendah."},
 {"j":"pilih","t":"Mengapakah bayi baru lahir perlu menangis kuat pada kali pertama?","p":["Untuk mengembangkan alveolus supaya pertukaran gas bermula","Untuk membersihkan mukus dan cecair daripada kedua-dua matanya","Untuk memanaskan badan selepas keluar dari rahim yang panas","Untuk menguji sama ada pita suaranya berfungsi dengan baik"],"b":0,"u":"Tangisan pertama membuka alveolus yang sebelum ini kuncup."}],
 bos:{"j":"nombor","t":"Seseorang bernafas 15 kali seminit dan setiap nafas membawa 500 ml udara. Berapa liter udara masuk ke peparu dalam satu minit?","b":7.5,"tol":0.05,"suf":"L","u":"15 didarab 500 ml bersamaan 7500 ml, iaitu 7.5 liter."}},

{n:4, tempat:"Kapilari Darah", sk:"2.2 / 2.3 Kesihatan respirasi", kadNama:"Hemoglobin", kadEm:"🩸", kadFakta:"Satu molekul hemoglobin membawa empat molekul oksigen sekali jalan.", bosKadNama:"Emfisema", bosKadEm:"🚬", bosKadFakta:"Dalam emfisema, dinding alveolus pecah dan bercantum sehingga luas permukaan pertukaran gas hilang secara kekal.", lampiran:"tekanan",
 soalan:[
 {"j":"banyak","t":"Berdasarkan Rajah 1, pilih SEMUA yang betul tentang FASA P.","p":["Otot diafragma mengecut dan jadi mendatar","Tekanan peparu lebih rendah daripada tekanan atmosfera","Udara mengalir masuk ke peparu","Otot interkosta dalam mengecut dan rusuk turun","Isi padu rongga toraks berkurang"],"b":[0,1,2],"u":"Isi padu naik dan tekanan turun serentak. Itu tandatangan tarik nafas."},
 {"j":"pilih","t":"Seorang pesakit alami kecederaan saraf frenik sehingga diafragma tak boleh mengecut. Kesan paling langsung?","p":["Isi padu udara setiap tarikan nafas berkurang","Alveolus pecah kerana tekanan dalam peparu naik","Hemoglobin tidak dapat bergabung dengan oksigen","Karbon dioksida mula keluar melalui kulit badan"],"b":0,"u":"Hilang diafragma bermakna hilang kedalaman nafas."},
 {"j":"banyak","t":"Asap rokok mengandungi tar, nikotina dan karbon monoksida. Pilih SEMUA kesan yang betul.","p":["Tar melumpuhkan silia sehingga mukus terkumpul","Karbon monoksida bergabung dengan hemoglobin","Dinding alveolus pecah dan luas permukaan berkurang","Nikotina melebarkan salur darah ke seluruh badan","Karbon monoksida menambah oksigen yang dibawa darah"],"b":[0, 1, 2],"u":"Karbon monoksida merampas tempat oksigen pada hemoglobin. Nikotina menyempitkan salur darah."},
 {"j":"pilih","t":"Dalam serangan asma, otot pada dinding bronkiol mengecut. Apakah kesannya terhadap PEFR, iaitu kelajuan maksimum udara dihembus keluar?","p":["Rintangan aliran udara meningkat, jadi PEFR menurun","Luas permukaan alveolus bertambah, jadi PEFR meningkat","Kapasiti vital meningkat serta-merta semasa serangan","Hemoglobin membawa lebih banyak oksigen ke bronkiol"],"b":0,"u":"Salur menyempit bermakna udara sukar keluar dengan laju."},
 {"j":"pilih","t":"Mengapakah karbon monoksida bahaya walaupun kepekatannya rendah?","p":["Ia terikat pada hemoglobin jauh lebih kuat daripada oksigen","Ia melarutkan dinding alveolus sedikit demi sedikit","Ia menghalang diafragma daripada mengecut dengan sepenuhnya","Ia menukar oksigen dalam darah menjadi gas nitrogen"],"b":0,"u":"Ikatan itu hampir 200 kali lebih kuat daripada ikatan oksigen."},
 {"j":"pilih","t":"PEFR ialah kelajuan maksimum udara dihembus keluar. Bacaan PEFR seorang pesakit asma: pagi 310, tengah hari 420, malam 300. Apakah tafsirannya?","p":["Aliran udaranya paling terhad pada waktu pagi dan malam","Alat pengukur itu rosak kerana bacaannya tidak tetap","Pesakit sudah sembuh kerana bacaan tengah hari tinggi","Pesakit bersenam terlalu banyak pada waktu tengah hari"],"b":0,"u":"Bacaan PEFR yang lebih rendah bermakna saluran udara lebih sempit. Corak sepanjang hari menunjukkan bila gejala paling teruk, dan maklumat itulah yang doktor gunakan untuk merancang rawatan."},
 {"j":"pilih","t":"Seorang murid bernafas berulang kali ke dalam beg kertas. Apa yang berlaku?","p":["Karbon dioksida dalam udara sedutan naik, jadi pernafasan bertambah laju","Oksigen dalam beg bertambah, jadi dia berasa lebih segar dan bertenaga","Tiada perubahan kerana udara yang disedut dan dihembus adalah sama","Nitrogen dalam beg habis digunakan, jadi pernafasan menjadi perlahan"],"b":0,"u":"Karbon dioksida yang terkumpul itulah pencetus pusat pernafasan."},
 {"j":"pilih","t":"Mengapakah kapasiti vital perokok lama lebih rendah walaupun peparunya bersaiz sama?","p":["Dinding alveolus rosak, jadi peparu kurang kenyal","Tulang rusuknya menjadi lebih pendek dan kaku","Diafragmanya mengeras dan bertukar menjadi tulang","Darahnya membawa lebih sedikit gas nitrogen"],"b":0,"u":"Kekenyalan peparu yang hilang tidak boleh dipulihkan."}],
 bos:{"j":"banyak","t":"Berdasarkan Rajah 1, pilih SEMUA yang betul tentang hubungan isi padu dan tekanan.","p":["Apabila isi padu toraks naik, tekanan peparu turun","Udara masuk apabila tekanan peparu lebih rendah daripada atmosfera","Tekanan tertinggi berlaku semasa hembus nafas","Isi padu dan tekanan naik serentak","Udara masuk apabila tekanan peparu lebih tinggi daripada atmosfera"],"b":[0,1,2],"u":"Isi padu dan tekanan sentiasa berubah secara songsang."}},

{n:5, tempat:"Aliran Darah", sk:"2.3 Kesihatan sistem respirasi", kadNama:"PEFR", kadEm:"📊", kadFakta:"PEFR ialah kelajuan maksimum udara dihembus keluar, dan ia jatuh dahulu sebelum pesakit asma rasa sesak.", bosKadNama:"Kapasiti Vital", bosKadEm:"🫁", bosKadFakta:"Kapasiti vital ialah isi padu udara terbanyak yang boleh dihembus selepas tarikan nafas paling dalam.", lampiran:"klinik",
 soalan:[
 {j:"pilih",t:"Berdasarkan jadual, siapakah paling berisiko tidak mendapat oksigen yang cukup semasa aktiviti berat?",p:["Encik Fauzi, kerana ketiga-tiga bacaannya di luar julat sihat","Suriani, kerana asma menyempitkan bronkiolnya pada setiap masa","Mei Ling, kerana kadar nafas rehatnya paling rendah dalam jadual","Encik Fauzi, kerana umurnya paling tua antara ketiga-tiga individu"],b:0,u:"Kadar nafas rehat yang rendah seperti Mei Ling ialah tanda kecergasan. Umur sahaja bukan bukti; bacaan Encik Fauzi yang menjadi bukti."},
 {j:"banyak",t:"Pilih SEMUA bukti daripada jadual yang menunjukkan Encik Fauzi paling berisiko.",p:["Kapasiti vital 2.6 L, di bawah julat sihat","PEFR 290, jauh di bawah julat sihat","Nafas rehat 22, melebihi julat sihat","Kadar nafas yang tinggi bermakna peparunya lebih cekap","Merokok menambah bilangan alveolus"],b:[0,1,2],u:"Kadar nafas rehat yang tinggi bermakna setiap nafas kurang berkesan. Merokok memecahkan dinding alveolus, bukan menambahnya."},
 {j:"pilih",t:"Suriani mahu menyertai merentas desa sekolah. Keputusan paling wajar?",p:["Benarkan, dengan inhaler pelega dibawa dan pemanasan badan dahulu","Halang, kerana senaman berat pasti mencetuskan serangan asma","Benarkan, tetapi dia berhenti menggunakan inhaler supaya peparunya kuat","Benarkan tanpa persediaan kerana PEFR 340 dalam julat sihat"],b:0,u:"PEFR 340 masih di bawah julat sihat 400 hingga 550. Asma yang terkawal tidak menghalang senaman jika persediaan dibuat."},
 {j:"pilih",t:"Seorang murid mengukur kapasiti vitalnya sekali sahaja dan mendapat 2.9 L. Nilaikan kebolehpercayaan bacaan itu.",p:["Kurang boleh dipercayai, kerana ukuran perlu diulang dan bacaan tertinggi diambil","Boleh dipercayai, kerana kapasiti vital seseorang tetap sepanjang hari","Kurang boleh dipercayai, kerana kapasiti vital hanya diukur selepas bersenam","Boleh dipercayai, asalkan alat itu sudah ditentukur oleh pihak makmal"],b:0,u:"Satu tiupan yang lemah memberi bacaan rendah. Ulangan meningkatkan kebolehpercayaan. Alat yang ditentukur meningkatkan kejituan, tetapi tidak menggantikan ulangan."},
 {j:"pilih",t:"Sekolah hanya mampu menjalankan SATU program kesihatan respirasi. Pilihan paling wajar berdasarkan sains?",p:["Kempen bebas rokok","Kelas senaman pagi, kerana senaman membina semula alveolus yang pecah","Ujian PEFR sahaja, kerana ia mengesan semua jenis penyakit peparu","Topeng muka untuk semua, kerana topeng biasa menapis asap rokok"],b:0,u:"Kerosakan alveolus akibat rokok tidak boleh dipulihkan, jadi mencegahnya memberi manfaat paling besar. Senaman tidak membina semula alveolus."},
 {j:"pilih",t:"Habuk dari tapak binaan paling tinggi pada waktu petang. Langkah manakah melindungi paling ramai murid asma dengan kos paling rendah?",p:["Pindahkan aktiviti luar ke waktu pagi","Beli satu penapis udara untuk kelas murid asma","Beri inhaler pencegah kepada semua murid di sekolah","Minta murid asma bernafas melalui mulut semasa berada di luar"],b:0,u:"Mengelak pendedahan hampir tiada kos dan melindungi semua murid. Rongga hidung menapis habuk, jadi bernafas melalui mulut memburukkan keadaan."},
 {j:"banyak",t:"Pilih SEMUA fakta yang tepat untuk dimasukkan dalam poster anti-rokok untuk remaja.",p:["Tar melumpuhkan silia sehingga mukus berkumpul","Karbon monoksida mengurangkan oksigen yang dibawa darah","Stamina sukan boleh menurun walaupun baru merokok beberapa bulan","Nikotina melebarkan bronkiol supaya lebih banyak udara masuk","Rokok elektronik hanya mengeluarkan wap air yang tidak berbahaya"],b:[0,1,2],u:"Nikotina menyempitkan salur darah dan tidak membantu pernafasan. Rokok elektronik mengandungi nikotina dan bahan kimia lain."},
 {j:"pilih",t:"Encik Fauzi berhenti merokok. Ramalan paling munasabah tentang keadaan peparunya setahun kemudian?",p:["Batuk berkurang kerana silia pulih, tetapi alveolus yang pecah kekal rosak","Semua bacaan kembali ke julat sihat kerana peparu pulih sepenuhnya","Tiada sebarang perubahan kerana semua kerosakan akibat rokok kekal","Kapasiti vitalnya melebihi Mei Ling kerana alveolus baharu terbentuk"],b:0,u:"Silia boleh pulih selepas berhenti merokok, tetapi dinding alveolus yang pecah tidak terbentuk semula."}],
 bos:{j:"pilih",t:"Seorang guru mencadangkan PEFR sahaja digunakan untuk mengenal pasti murid asma. Nilaikan cadangan itu berdasarkan jadual.",p:["Kurang tepat, kerana perokok seperti Encik Fauzi juga mempunyai PEFR rendah","Tepat, kerana hanya pesakit asma mempunyai PEFR di bawah 400","Tepat, kerana PEFR mengukur isi padu udara terbanyak dalam peparu","Kurang tepat, kerana PEFR atlet sentiasa lebih rendah daripada pesakit asma"],b:0,u:"PEFR ialah kelajuan maksimum udara dihembus, bukan isi padu. Bacaan rendah boleh berpunca daripada asma, merokok atau penyakit lain."}},

{n:6, tempat:"Sel Badan", sk:"2.3 / 2.4 Penyelesaian masalah", kadNama:"Inhaler", kadEm:"💉", kadFakta:"Inhaler pelega melebarkan bronkiol dalam masa kurang lima minit semasa serangan asma.", bosKadNama:"Udara Bersih", bosKadEm:"💡", bosKadFakta:"Menyiram tanah di tapak pembinaan boleh mengurangkan habuk terapung sehingga separuh, dan kosnya hampir sifar.",
 soalan:[
 {j:"pilih",t:"Awak mereka alat amaran habuk untuk murid asma. Ciri manakah paling penting supaya ia benar-benar melindungi mereka?",p:["Amaran berbunyi sebelum habuk mencapai paras yang mencetuskan asma","Amaran berbunyi selepas murid mula batuk dan sesak nafas","Alat mengukur suhu kerana suhu tinggi ialah punca utama asma","Alat mengukur oksigen kerana habuk mengurangkan oksigen dalam udara"],b:0,u:"Amaran berguna hanya jika ia datang sebelum bronkiol mula menyempit. Habuk mencetuskan asma dengan merengsakan salur udara, bukan dengan mengurangkan oksigen."},
 {j:"pilih",t:"Awak reka topeng penapis habuk menggunakan bahan di sekolah. Kriteria manakah paling menentukan kejayaannya?",p:["Menapis zarah halus tetapi udara masih mengalir dengan mudah","Ditutup serapat mungkin dengan lima lapisan kain tebal","Menapis karbon dioksida supaya udara sedutan lebih bersih","Dibuat daripada plastik kedap udara supaya habuk langsung tidak masuk"],b:0,u:"Terlalu banyak lapisan menambah rintangan dan menyukarkan pernafasan, terutama bagi murid asma. Topeng habuk tidak menapis gas seperti karbon dioksida."},
 {j:"pilih",t:"Kontraktor tapak binaan enggan berhenti kerja. Pendekatan paling wajar yang mengambil kira nilai masyarakat?",p:["Minta mereka menyiram tanah dan menutup muatan lori","Minta mereka membina pagar zink kerana pagar menyekat semua habuk halus","Minta kerja dihentikan sepenuhnya sehingga semua murid asma sembuh","Minta mereka bekerja pada waktu malam tanpa sebarang kawalan habuk"],b:0,u:"Tanah basah tidak menerbangkan habuk. Zarah halus melepasi pagar, dan habuk malam masih terapung sehingga pagi."},
 {j:"pilih",t:"Selepas penyelesaian awak dipasang, bagaimana awak membuktikan ia benar-benar berkesan?",p:["Rekod PEFR dan episod sesak nafas murid asma sebelum dan selepas","Kira habuk yang melekat pada tingkap kelas sekali sahaja","Tanya kontraktor sama ada habuk di tapak binaan sudah berkurang","Bandingkan PEFR murid asma dengan PEFR murid yang sihat"],b:0,u:"Perbandingan sebelum dan selepas pada murid yang sama mengasingkan kesan penyelesaian. Murid sihat memang mempunyai PEFR lebih tinggi sejak awal."},
 {j:"pilih",t:"Awak mahu menanam penghadang hijau di pagar sekolah untuk memerangkap habuk. Pokok manakah paling sesuai?",p:["Pokok renek berdaun lebat yang ditanam rapat","Pokok palma tinggi dengan beberapa helai daun di puncaknya","Rumput pendek kerana akarnya menyerap habuk dari udara","Pokok berbunga harum supaya bau habuk tidak lagi dihidu"],b:0,u:"Daun yang banyak dan rapat pada paras pernafasan memerangkap zarah. Bau wangi tidak mengurangkan habuk yang disedut."},
 {j:"pilih",t:"Rakan awak mencadangkan kipas besar di pintu kelas untuk meniup habuk keluar. Nilaikan reka bentuk itu.",p:["Kurang sesuai, kerana kipas turut menerbangkan habuk di lantai","Sesuai, kerana aliran udara yang laju menapis habuk seperti silia","Sesuai, kerana habuk lebih berat daripada udara dan akan terus jatuh","Kurang sesuai, kerana kipas menambah karbon dioksida dalam kelas"],b:0,u:"Kipas menggerakkan udara, termasuk habuk yang sudah mendap. Habuk halus cukup ringan untuk terus terapung."},
 {j:"pilih",t:"Dua reka bentuk memberi perlindungan yang sama. A berharga RM90 dan perlu penapis baharu setiap bulan pada RM15. B berharga RM250 dan penapisnya boleh dibasuh. Pilihan paling wajar untuk setahun?",p:["B, kerana jumlah kos A setahun ialah RM270","A, kerana harga permulaannya jauh lebih rendah","A, kerana penapis baharu setiap bulan lebih berkesan","B, kerana penapis yang dibasuh menapis zarah lebih halus"],b:0,u:"RM90 campur RM15 darab 12 bersamaan RM270, melebihi RM250. Soalan menyatakan perlindungan sama, jadi kos jangka panjang yang menentukan."},
 {j:"pilih",t:"Awak menulis kad panduan kecemasan asma untuk kelas. Langkah pertama yang betul semasa serangan asma?",p:["Dudukkan murid tegak dan bantu dia menggunakan inhaler pelega","Baringkan murid supaya diafragma dapat berehat sepenuhnya","Beri murid air sejuk untuk melebarkan bronkiol yang menyempit","Minta murid bernafas berulang kali ke dalam beg kertas"],b:0,u:"Duduk tegak memudahkan pergerakan diafragma. Inhaler pelega melebarkan bronkiol; air sejuk tidak. Beg kertas menambah karbon dioksida."}],
 bos:{j:"buka",
  t:"Sekolah awak 300 m dari tapak pembinaan. Tiga murid asma dalam kelas awak kerap sesak nafas waktu petang. Reka satu penyelesaian yang sekolah awak benar-benar boleh laksanakan.",
  arahan:"Terangkan cara ia berfungsi, bahan atau alat yang perlu, siapa yang jalankan, dan bagaimana awak ambil kira kos serta penerimaan kontraktor dan penduduk sekitar.",
  u:"Jawapan TP6 yang kukuh menggabungkan sains respirasi, kos sebenar, dan penerimaan masyarakat."}}
];

module.exports = {
  id:"t3b2", tingkatan:3, kod:"2.0 Respirasi",
  tajuk:"Laluan Oksigen",
  subtajuk:"Sains Ting. 3 · Bab 2 Respirasi",
  spi:SPI,
  /* Ulasan PBD mengikut tahap penguasaan. {n} diganti dengan nama pertama murid. */
  ulasan:{
   1:"{n} dapat mengingat kembali struktur sistem respirasi manusia dan istilah asas bab ini. Langkah seterusnya ialah menerangkan sebab di sebalik setiap struktur, bukan sekadar menamakannya.",
   2:"{n} memahami mekanisme pernafasan serta ciri alveolus dan dapat menjelaskan kefahaman tersebut. Perlu lebih banyak latihan mentafsir data gas sebelum bergerak ke TP3.",
   3:"{n} boleh mengaplikasikan pengetahuan respirasi untuk menerangkan fenomena harian seperti kenaikan kadar pernafasan selepas bersenam. Galakkan membaca graf dan mengaitkan dua pemboleh ubah.",
   4:"{n} mampu menganalisis graf isi padu toraks melawan tekanan udara dan mengenal pasti punca apabila satu komponen sistem gagal. Seterusnya latih menimbang bukti untuk membuat keputusan.",
   5:"{n} dapat menilai data klinikal tiga individu, memilih kes berisiko tinggi dan menyokongnya dengan bukti berangka daripada jadual. Sudah bersedia untuk tugasan reka cipta.",
   6:"{n} berjaya mereka cipta penyelesaian kualiti udara yang praktikal untuk murid asma di sekolah, lengkap dengan pertimbangan kos dan penerimaan komuniti setempat. Pencapaian cemerlang bagi bab ini.",
   tiada:"{n} belum menunjukkan bukti penguasaan yang mencukupi bagi bab Respirasi. Cadangan: ulang aktiviti hentian pertama dengan bimbingan rakan sebaya."
  },
  lampiran:{ gas: L_GAS, klinik: L_KLINIK, tekanan: L_TEKANAN },
  aras:ARAS
};
