/* Sumber kandungan — Sains KSSM Tingkatan 4, Bidang 12.0 Tenaga Nuklear.
   Fail ini disunting tangan. Jalankan `node bina.js t4b10` untuk menyemaknya
   dan menghasilkan bank-t4b10.js dengan kedudukan jawapan yang seimbang.

   Standard Prestasi disalin kata demi kata daripada DSKP KSSM Sains
   Tingkatan 4, Bahagian Pembangunan Kurikulum, muka 106.

   Tulis jawapan betul pada indeks 0. Pembina akan mengagihkannya. */

const SPI = [
"Mengingat kembali pengetahuan dan kemahiran sains mengenai tenaga nuklear.",
"Memahami tenaga nuklear dan dapat menjelaskan kefahaman tersebut.",
"Mengaplikasikan pengetahuan mengenai tenaga nuklear dan dapat melaksanakan tugasan mudah.",
"Menganalisis pengetahuan mengenai tenaga nuklear dalam konteks penyelesaian masalah mengenai kejadian atau fenomena alam.",
"Menilai pengetahuan mengenai tenaga nuklear dalam konteks penyelesaian masalah dan membuat keputusan untuk melaksanakan satu tugasan.",
"Mencipta dengan menggunakan pengetahuan dan kemahiran sains mengenai tenaga nuklear dalam konteks penyelesaian masalah dan membuat keputusan atau dalam melaksanakan satu tugasan dalam situasi baru secara kreatif dan inovatif dengan mengambil kira nilai sosial/ekonomi/budaya masyarakat."];

/* ---------- lampiran ---------- */

const R_BELAHAN = {
  jenis:"aliran", mod:"turun",
  nod:[
    { label:"Neutron menghentam nukleus Uranium-235", isi:"kertas2" },
    { label:"Nukleus terbelah kepada dua nukleus lebih ringan", isi:"kuningLembut", panah:"kuning" },
    { label:"Tenaga dan 2-3 neutron baharu dibebaskan", isi:"merahLembut", panah:"merah" },
    { label:"Neutron baharu menghentam nukleus lain, reaksi berterusan", isi:"merahLembut" },
  ],
  kapsyen:"Rajah 1 · Reaksi berantai apabila nukleus Uranium-235 terbelah.",
  alt:"Rajah aliran menegak empat langkah reaksi berantai pembelahan nukleus uranium"
};

const R_REAKTOR = {
  jenis:"struktur", mod:"lapisan",
  lapisan:[
    { label:"Teras", tebal:1, isi:"merahLembut" },
    { label:"Rod kawalan", tebal:1, isi:"kuningLembut" },
    { label:"Penyejuk", tebal:1.3, isi:"hijauLembut" },
    { label:"Naungan", tebal:1.6, isi:"kertas2" },
  ],
  kapsyen:"Rajah 1 · Susunan lapisan utama sebuah reaktor nuklear.",
  alt:"Rajah lapisan sepusat empat bahagian reaktor nuklear: teras, rod kawalan, air penyejuk, naungan konkrit"
};

const T_SUMBER =
'<div class="scrollx"><table class="datatable"><thead><tr><th>Sumber tenaga</th>'+
'<th>Pelepasan karbon semasa operasi</th><th>Bekalan berterusan (tanpa cuaca)</th><th>Sisa berbahaya</th></tr></thead><tbody>'+
'<tr><td>Nuklear</td><td>Sangat rendah</td><td>Ya</td><td>Sisa radioaktif</td></tr>'+
'<tr><td>Arang batu</td><td>Tinggi</td><td>Ya</td><td>Abu dan gas rumah hijau</td></tr>'+
'<tr><td>Suria</td><td>Sangat rendah</td><td>Tidak (bergantung cuaca)</td><td>Tiada</td></tr>'+
'<tr><td>Angin</td><td>Sangat rendah</td><td>Tidak (bergantung angin)</td><td>Tiada</td></tr>'+
'</tbody></table></div><p class="qnote">Ringkasan ciri am setiap sumber tenaga, bukan angka sebenar sesuatu loji.</p>';

/* ---------- hentian ---------- */

const ARAS = [

{n:1, tempat:"Nukleus", sk:"12.1 / 12.2 Pengenalan tenaga nuklear", lampiran:"belahan",
 kadNama:"Uranium-235", kadEm:"\u{2622}", kadFakta:"Pembelahan lengkap satu gram Uranium-235 membebaskan tenaga yang kira-kira menyamai pembakaran tiga tan arang batu.",
 bosKadNama:"Pelakuran Hidrogen", bosKadEm:"\u{2600}", bosKadFakta:"Matahari menghasilkan tenaganya melalui pelakuran nukleus hidrogen menjadi helium, proses yang telah berlangsung lebih 4.6 bilion tahun.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 1, neutron menghentam nukleus Uranium-235 lalu ia terbelah. Apakah nama proses ini?",p:["Pembelahan nukleus (fission)","Pelakuran nukleus (fusion)","Pengionan atom","Pereputan radioaktif semula jadi"],b:0,u:"Pembelahan nukleus berlaku apabila nukleus berat terbelah kepada dua nukleus yang lebih ringan."},
 {j:"pilih",t:"Pelakuran nukleus (fusion) bermaksud:",p:["Dua nukleus ringan bergabung menjadi satu nukleus lebih berat","Nukleus berat terbelah kepada dua nukleus yang lebih ringan","Elektron tertanggal daripada atom itu akibat haba tinggi","Proton bertukar menjadi neutron secara semula jadi dengan sendiri"],b:0,u:"Pelakuran ialah proses sebaliknya daripada pembelahan: nukleus kecil bergabung, bukan nukleus besar terbelah."},
 {j:"pilih",t:"Tenaga nuklear terhasil daripada tindak balas yang berlaku di bahagian manakah atom?",p:["Nukleus atom","Petala elektron atom","Permukaan luar atom","Ruang kosong antara atom"],b:0,u:"Nukleus menyimpan tenaga ikatan yang jauh lebih besar berbanding tenaga yang terlibat dalam petala elektron."},
 {j:"pilih",t:"Proses manakah berlaku pada teras Matahari untuk menghasilkan tenaga?",p:["Pelakuran nukleus hidrogen","Pembelahan nukleus uranium","Pembakaran gas hidrogen dengan oksigen","Pantulan cahaya berterusan dari teras"],b:0,u:"Matahari terlalu panas untuk pembakaran biasa; tenaganya datang daripada pelakuran nukleus, bukan pembakaran kimia."},
 {j:"pilih",t:"Bahan api yang lazim digunakan dalam reaktor nuklear pembelahan ialah:",p:["Uranium-235","Karbon dioksida","Arang batu","Gas asli"],b:0,u:"Uranium-235 mudah mengalami pembelahan apabila dihentam neutron, jadi ia dipilih sebagai bahan api reaktor."},
 {j:"pilih",t:"Apakah yang dibebaskan apabila satu nukleus Uranium-235 terbelah?",p:["Tenaga, neutron baharu, dua nukleus ringan","Elektron dan cahaya nampak sahaja yang terhasil","Air dan oksigen tulen sahaja yang terhasil","Karbon dioksida sahaja tanpa bahan lain"],b:0,u:"Hasil pembelahan termasuk tenaga, beberapa neutron baharu, dan nukleus yang lebih kecil daripada nukleus asal."},
 {j:"susun",t:"Susun langkah reaksi berantai pembelahan nukleus mengikut urutan yang betul.",p:["Neutron menghentam nukleus Uranium-235","Nukleus terbelah kepada dua nukleus lebih ringan","Tenaga dan neutron baharu dibebaskan","Neutron baharu menghentam nukleus lain"],b:[0,1,2,3],u:"Reaksi berantai bermula dengan satu neutron dan berterusan apabila neutron baharu menghentam nukleus seterusnya."},
 {j:"pilih",t:"Berbanding pembakaran arang batu, tindak balas nuklear membebaskan tenaga yang:",p:["Jauh lebih banyak bagi setiap unit jisim","Sama banyak bagi setiap unit jisim bahan api","Lebih sedikit bagi setiap unit jisim bahan api","Tidak dapat dibandingkan sama sekali antara kedua-duanya"],b:0,u:"Tenaga ikatan nukleus jauh lebih besar daripada tenaga ikatan kimia, jadi jisim bahan api nuklear yang kecil boleh membebaskan tenaga yang besar."}],
 bos:{j:"banyak",t:"Pilih SEMUA pernyataan yang benar tentang pembelahan dan pelakuran nukleus.",p:["Pembelahan berlaku dalam reaktor nuklear di Bumi","Pelakuran berlaku secara semula jadi di teras Matahari","Kedua-dua proses membebaskan tenaga daripada nukleus atom","Pelakuran memerlukan suhu dan tekanan yang sangat tinggi","Pembelahan hanya berlaku pada nukleus hidrogen"],b:[0,1,2,3],u:"Pembelahan menggunakan nukleus berat seperti uranium, bukan hidrogen; hidrogen dikaitkan dengan pelakuran."}},

{n:2, tempat:"Reaktor", sk:"12.2 Penghasilan tenaga nuklear", lampiran:"reaktor",
 kadNama:"Rod Kawalan", kadEm:"\u{1F39B}", kadFakta:"Rod kawalan dalam reaktor lazimnya diperbuat daripada bahan seperti boron atau kadmium yang amat berkesan menyerap neutron.",
 bosKadNama:"Reaksi Berantai Terkawal", bosKadEm:"\u{1F517}", bosKadFakta:"Reaksi berantai nuklear terkawal yang pertama di dunia dicetuskan oleh saintis Enrico Fermi di Chicago pada tahun 1942.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 1, bahagian manakah terletak PALING luar dalam susunan reaktor?",p:["Naungan konkrit","Teras bahan api uranium","Rod kawalan","Air penyejuk"],b:0,u:"Naungan konkrit membungkus keseluruhan reaktor di lapisan paling luar untuk menghalang sinaran terlepas."},
 {j:"pilih",t:"Berdasarkan Rajah 1, apakah fungsi lapisan air penyejuk yang terletak antara rod kawalan dan naungan konkrit?",p:["Memindahkan haba daripada teras reaktor untuk hasilkan wap","Menyerap neutron supaya reaksi terhenti serta-merta sepenuhnya","Menambah bilangan nukleus uranium dalam teras reaktor itu","Menukar wap terus kepada nukleus baharu secara langsung"],b:0,u:"Air penyejuk membawa haba keluar daripada teras; wap yang terhasil kemudian memutarkan turbin."},
 {j:"pilih",t:"Fungsi rod kawalan dalam reaktor nuklear ialah:",p:["Menyerap lebihan neutron untuk mengawal kadar tindak balas","Mempercepatkan pembelahan nukleus dalam teras reaktor","Menyejukkan air dalam sistem reaktor secara langsung","Menjana elektrik terus daripada haba yang terhasil"],b:0,u:"Rod kawalan diselak masuk atau keluar untuk menaikkan atau menurunkan kadar reaksi berantai."},
 {j:"pilih",t:"Mengapa reaksi berantai dalam reaktor perlu dikawal, bukan dibiarkan berlaku secara bebas?",p:["Supaya tenaga dibebaskan secara terkawal","Supaya lebih banyak neutron terhasil dengan pantas sekali","Supaya nukleus uranium itu habis dengan lebih cepat","Supaya reaktor itu menjadi lebih sejuk daripada biasa"],b:0,u:"Tanpa kawalan, kadar pembelahan boleh meningkat mendadak dan menjadi tidak selamat."},
 {j:"pilih",t:"Struktur konkrit tebal yang membungkus reaktor berfungsi untuk:",p:["Menghalang sinaran berbahaya daripada terlepas","Mempercepatkan pembelahan nukleus dalam teras reaktor","Menyejukkan bahan api nuklear secara langsung dan cepat","Menambah tekanan dalam teras reaktor itu secara berterusan"],b:0,u:"Naungan konkrit ialah perisai sinaran, bukan komponen yang mengubah kadar tindak balas."},
 {j:"susun",t:"Susun proses reaktor nuklear menjana elektrik mengikut urutan yang betul.",p:["Pembelahan nukleus membebaskan haba","Haba menukar air kepada wap","Wap memutarkan turbin","Turbin memutarkan penjana untuk menghasilkan elektrik"],b:[0,1,2,3],u:"Prinsipnya sama seperti loji janakuasa lain: haba menghasilkan wap, wap memutarkan turbin dan penjana."},
 {j:"pilih",t:"Apakah perbezaan utama antara loji janakuasa nuklear dan loji janakuasa arang batu?",p:["Sumber haba berbeza; kedua-duanya memutarkan turbin dengan wap","Ia tidak menggunakan turbin langsung","Arang batu turut digunakan bersama tenaga nuklear","Tiada sebarang haba dihasilkan langsung"],b:0,u:"Kedua-dua jenis loji menggunakan wap untuk memutarkan turbin; bezanya hanya cara haba dihasilkan."},
 {j:"pilih",t:"Jika terlalu banyak rod kawalan ditarik keluar serentak, apakah risikonya?",p:["Kadar pembelahan meningkat mendadak, sukar dikawal","Reaktor akan terhenti serta-merta tanpa sebarang amaran","Bahan api nuklear itu bertukar sepenuhnya menjadi air","Elektrik yang terhasil itu menjadi terlalu sejuk"],b:0,u:"Menarik keluar rod kawalan mengurangkan penyerapan neutron, jadi lebih banyak nukleus terbelah serentak."}],
 bos:{j:"pilih",t:"Berdasarkan Rajah 1, apakah kaitan antara reaksi berantai dan keperluan rod kawalan dalam reaktor?",p:["Reaksi berantai boleh meningkat tanpa kawalan, jadi rod kawalan menyerap neutron lebihan","Rod kawalan mempercepatkan reaksi berantai supaya lebih banyak tenaga terhasil","Reaksi berantai berhenti sendiri tanpa sebarang kawalan diperlukan","Rod kawalan menggantikan sepenuhnya keperluan bahan api uranium"],b:0,u:"Rod kawalan dan reaksi berantai saling berkait: satu boleh melarikan diri tanpa kawalan, satu lagi menahannya pada kadar selamat."}},

{n:3, tempat:"Grid Kuasa", sk:"12.1 / 12.4 Membandingkan sumber tenaga", lampiran:"sumber",
 kadNama:"Grid Kuasa Kebangsaan", kadEm:"\u{1F50C}", kadFakta:"Sistem gred kuasa menggabungkan pelbagai sumber tenaga supaya bekalan elektrik kekal stabil walaupun satu sumber terganggu.",
 bosKadNama:"Tenaga Boleh Diperbaharui", bosKadEm:"\u{1F343}", bosKadFakta:"Malaysia mensasarkan peningkatan sumbangan tenaga boleh diperbaharui dalam campuran janakuasa negara sebagai sebahagian daripada transformasi sektor tenaga.",
 soalan:[
 {j:"pilih",t:"Berdasarkan jadual, sumber tenaga manakah membekalkan elektrik secara berterusan tanpa bergantung cuaca DAN mempunyai pelepasan karbon yang rendah?",p:["Nuklear","Suria","Angin","Arang batu"],b:0,u:"Nuklear sahaja dalam jadual memenuhi kedua-dua syarat itu serentak."},
 {j:"pilih",t:"Apakah kelebihan tenaga nuklear berbanding arang batu berdasarkan jadual?",p:["Pelepasan karbon semasa operasi jauh lebih rendah","Tiada sebarang sisa berbahaya yang dihasilkan langsung","Bekalannya bergantung sepenuhnya kepada keadaan cuaca","Kosnya pasti lebih murah dalam semua keadaan sekalipun"],b:0,u:"Jadual menunjukkan pelepasan karbon nuklear sangat rendah berbanding arang batu yang tinggi."},
 {j:"pilih",t:"Mengapa suria dan angin tidak sesuai dijadikan SATU-SATUNYA sumber tenaga sesebuah negara berdasarkan jadual?",p:["Bekalannya tidak berterusan kerana bergantung kepada cuaca","Sisa radioaktif dihasilkan oleh kedua-duanya","Karbon tinggi dilepaskan oleh kedua-duanya","Elektrik tidak dapat dijana langsung oleh kedua-duanya"],b:0,u:"Jadual menunjukkan kedua-dua sumber ini tidak membekalkan tenaga berterusan tanpa cuaca sesuai."},
 {j:"banyak",t:"Pilih SEMUA sumber tenaga dalam jadual yang bekalannya bergantung kepada keadaan cuaca.",p:["Suria","Angin","Nuklear","Arang batu"],b:[0,1],u:"Nuklear dan arang batu membekalkan tenaga berterusan tanpa bergantung cuaca mengikut jadual."},
 {j:"pilih",t:"Berdasarkan jadual, apakah cabaran UTAMA tenaga nuklear yang tiada pada suria dan angin?",p:["Penghasilan sisa radioaktif yang perlu diuruskan selamat","Kebergantungan kepada keadaan cuaca yang tidak menentu","Pelepasan karbon yang tinggi semasa operasi harian","Ketidakupayaan menjana elektrik dalam kuantiti yang besar"],b:0,u:"Jadual menunjukkan hanya nuklear menghasilkan sisa berbahaya berbentuk radioaktif."},
 {j:"pilih",t:"Sebuah kilang memerlukan bekalan elektrik stabil sepanjang masa dan mahu mengurangkan pelepasan karbon. Sumber manakah paling sesuai berdasarkan jadual?",p:["Nuklear","Suria","Angin","Arang batu"],b:0,u:"Nuklear membekalkan tenaga berterusan dan berkarbon rendah; arang batu stabil tetapi berkarbon tinggi."},
 {j:"pilih",t:"Apakah maksud 'bekalan berterusan' bagi sesuatu sumber tenaga dalam konteks jadual ini?",p:["Sumber itu boleh menjana elektrik bila-bila masa tanpa bergantung cuaca","Sumber itu tidak akan pernah habis walau digunakan selama-lamanya sekalipun","Sumber itu tidak memerlukan sebarang penyelenggaraan langsung","Sumber itu pasti paling murah untuk dibina berbanding lain"],b:0,u:"Bekalan berterusan bermaksud tidak terjejas oleh faktor luar seperti cuaca, bukan tentang kos atau penyelenggaraan."},
 {j:"pilih",t:"Mengapa sesetengah negara memilih menggabungkan tenaga nuklear dengan suria dan angin, bukan bergantung pada satu sumber sahaja?",p:["Menggabungkan kelebihan setiap sumber tenaga yang berbeza","Supaya kos pembinaan menjadi lebih tinggi daripada sepatutnya","Supaya lebih banyak sisa radioaktif yang dihasilkan kelak","Kerana undang-undang antarabangsa mewajibkan gabungan sumber tenaga"],b:0,u:"Gabungan sumber mengimbangi kelemahan setiap sumber apabila digunakan bersendirian."}],
 bos:{j:"banyak",t:"Berdasarkan jadual, pilih SEMUA sebab tenaga nuklear wajar dipertimbangkan sebagai sumber tenaga masa depan.",p:["Pelepasan karbon yang rendah semasa operasi","Bekalan elektrik yang stabil tanpa bergantung cuaca","Tiada sebarang risiko atau sisa yang perlu diuruskan","Boleh menjana elektrik dalam kuantiti yang besar"],b:[0,1,3],u:"Nuklear tetap menghasilkan sisa radioaktif yang perlu diuruskan; itu bukan kelebihan tanpa risiko."}},

{n:4, tempat:"Sejarah", sk:"12.3 Impak penggunaan tenaga nuklear",
 kadNama:"Sinaran Pengionan", kadEm:"\u{2623}", kadFakta:"Sinaran pengionan boleh merosakkan struktur DNA dalam sel, dan kesannya kadangkala hanya muncul bertahun-tahun selepas pendedahan.",
 bosKadNama:"Zon Larangan", bosKadEm:"\u{1F6A7}", bosKadFakta:"Sesetengah kawasan bekas ujian atau kemalangan nuklear ditetapkan sebagai zon larangan sehingga tahap sinaran disahkan selamat oleh pakar.",
 soalan:[
 {j:"pilih",t:"Letupan bom nuklear membebaskan tenaga dalam bentuk apa yang memudaratkan hidupan dalam jangka masa panjang?",p:["Sinaran pengionan","Bunyi bergema sahaja","Cahaya nampak sahaja","Wap air panas sahaja"],b:0,u:"Sinaran pengionan terus memberi kesan lama selepas haba dan letupan awal reda."},
 {j:"pilih",t:"Mengapa kawasan yang terkena ujian nuklear boleh kekal berbahaya bertahun-tahun selepas letupan?",p:["Bahan radioaktif yang tertinggal terus mengeluarkan sinaran sehingga reput","Habuk daripada letupan itu menutupi kawasan tersebut secara kekal","Suhu di kawasan itu kekal tinggi buat selama-lamanya","Air di kawasan itu menjadi beku dengan serta-merta"],b:0,u:"Bahan radioaktif mereput secara beransur-ansur; sinarannya berkurang mengikut masa, bukan berhenti serta-merta."},
 {j:"pilih",t:"Selepas pengeboman Hiroshima dan Nagasaki pada 1945, ramai mangsa mengalami kesan kesihatan bertahun-tahun kemudian. Apakah penjelasan paling munasabah?",p:["Pendedahan sinaran pengionan merosakkan sel dan DNA, kesannya muncul lambat","Kesan itu disebabkan sepenuhnya trauma psikologi tanpa kaitan sinaran langsung","Kesan kesihatan itu tiada kaitan dengan letupan dan hanya kebetulan sahaja","Sinaran hanya memberi kesan sejurus letupan dan tidak berpanjangan lagi"],b:0,u:"Kerosakan sel dan DNA akibat sinaran boleh mengambil masa untuk menunjukkan kesan seperti kanser."},
 {j:"banyak",t:"Pilih SEMUA kesan yang munasabah berlaku akibat ujian senjata nuklear ke atas persekitaran.",p:["Pencemaran radioaktif pada tanah dan air","Kepupusan atau kecacatan hidupan di kawasan terjejas","Peningkatan kesuburan tanah secara mendadak","Kesan kesihatan jangka panjang kepada penduduk berhampiran","Air laut bertukar menjadi tawar sepenuhnya"],b:[0,1,3],u:"Ujian nuklear tidak meningkatkan kesuburan tanah atau menukar air laut menjadi tawar; kedua-dua dakwaan itu tidak berasas."},
 {j:"pilih",t:"Mengapa saintis dan badan antarabangsa memantau tahap sinaran di kawasan bekas ujian nuklear sebelum membenarkan penduduk kembali?",p:["Untuk memastikan tahap sinaran radioaktif sudah selamat manusia","Untuk mengira bilangan haiwan yang terselamat sahaja di situ","Untuk menentukan suhu udara di kawasan itu sahaja","Untuk membina semula bangunan dengan lebih cepat lagi"],b:0,u:"Keselamatan sinaran ialah kriteria utama sebelum sesuatu kawasan diisytiharkan selamat didiami semula."},
 {j:"pilih",t:"Apakah perbezaan antara kesan SERTA-MERTA dan kesan JANGKA PANJANG letupan nuklear?",p:["Serta-merta: kemusnahan akibat letupan; jangka panjang: kesan sinaran dan penyakit","Kedua-duanya berlaku serentak dan tidak dapat dibezakan","Kesan jangka panjang hanya melibatkan bangunan, bukan hidupan","Kesan serta-merta hanya melibatkan sinaran, bukan haba atau letupan"],b:0,u:"Kesan serta-merta dan jangka panjang berpunca daripada mekanisme yang berbeza: haba/letupan berbanding sinaran berterusan."},
 {j:"pilih",t:"Berdasarkan sejarah pengeboman atom, apakah pengajaran utama berkaitan penggunaan tenaga nuklear untuk tujuan senjata?",p:["Kuasa pemusnah tenaga nuklear amat besar, perlu dikawal ketat","Senjata nuklear tidak memberi sebarang kesan kepada alam sekitar sama sekali","Senjata nuklear hanya memberi kesan kepada bangunan, bukan kepada manusia","Kesan senjata nuklear hilang sepenuhnya dalam masa seminggu sahaja"],b:0,u:"Sejarah menunjukkan kesan yang amat besar dan berpanjangan, mendorong kawalan antarabangsa terhadap senjata nuklear."},
 {j:"pilih",t:"Seorang murid mendakwa 'kawasan bekas ujian nuklear akan berbahaya selama-lamanya dan tidak boleh didiami lagi'. Nilaikan dakwaan ini.",p:["Tidak tepat; tahap sinaran berkurang dari masa ke masa dan sesetengah kawasan sudah selamat semula","Tepat sepenuhnya; semua kawasan sedemikian kekal berbahaya selama-lamanya","Tidak tepat; kawasan itu selamat sejurus letupan tamat","Tepat, tetapi hanya kerana suhu kawasan itu kekal tinggi"],b:0,u:"Kadar pereputan bahan radioaktif berbeza-beza; sesetengah unsur mereput lebih cepat berbanding yang lain."}],
 bos:{j:"pilih",t:"Berdasarkan trend sejarah, apakah faedah utama perjanjian antarabangsa yang mengehadkan ujian senjata nuklear?",p:["Mengurangkan pencemaran radioaktif serta risiko kepada awam","Meningkatkan bilangan negara yang boleh menguji senjata nuklear itu","Menghapuskan sepenuhnya kegunaan tenaga nuklear untuk penjanaan elektrik negara","Tiada faedah kerana perjanjian sedemikian dianggap tidak berkesan"],b:0,u:"Mengehadkan ujian mengurangkan pencemaran radioaktif tambahan, walaupun kegunaan nuklear untuk elektrik terus wujud."}},

{n:5, tempat:"Dewan Keputusan", sk:"12.1 / 12.4 Menilai kewajaran tenaga nuklear",
 kadNama:"Kajian Kebolehlaksanaan", kadEm:"\u{1F4CB}", kadFakta:"Kajian kebolehlaksanaan loji nuklear boleh mengambil masa bertahun-tahun, meliputi kajian geologi, alam sekitar dan sosioekonomi sesuatu tapak.",
 bosKadNama:"Penerimaan Awam", bosKadEm:"\u{1F5F3}", bosKadFakta:"Banyak negara mengadakan khidmat nasihat dan sesi maklum balas awam sebelum meluluskan pembinaan loji nuklear baharu.",
 soalan:[
 {j:"pilih",t:"Sebuah negara jiran Malaysia bercadang membina loji nuklear berhampiran sempadan. Faktor manakah PALING penting dinilai dahulu?",p:["Kestabilan geologi kawasan dan risiko gempa bumi","Warna cat bangunan loji tersebut sahaja perlu dinilai","Bilangan pekerja yang boleh diambil bekerja di situ","Jarak loji daripada pusat membeli-belah berdekatan"],b:0,u:"Keselamatan tapak dari segi geologi ialah faktor asas sebelum sebarang pertimbangan lain."},
 {j:"pilih",t:"Malaysia mempertimbangkan pembinaan stesen janakuasa nuklear. Apakah bukti PALING kukuh untuk menyokong cadangan ini?",p:["Kajian kebolehlaksanaan menunjukkan tapak itu selamat dan risiko banjir rendah","Seorang menteri menyatakan idea itu bagus dalam satu ucapan rasmi","Negara lain sudah membina loji serupa tanpa sebarang kajian lanjut","Kos pembinaan didakwa lebih murah tanpa sebarang bukti kukuh"],b:0,u:"Bukti berasaskan kajian saintifik lebih kukuh berbanding pendapat atau tanggapan tanpa data."},
 {j:"pilih",t:"Nilaikan hujah 'Malaysia tidak sesuai membina loji nuklear kerana kepadatan penduduk yang tinggi di sekitar kawasan tertentu'.",p:["Munasabah, kerana kepadatan penduduk meningkatkan risiko jika berlaku kebocoran sinaran","Tidak munasabah, kerana kepadatan penduduk tidak berkaitan langsung dengan keselamatan loji","Munasabah, tetapi hanya kerana kos pembinaan menjadi lebih tinggi","Tidak munasabah, kerana loji nuklear tidak pernah mengalami kebocoran di mana-mana negara"],b:0,u:"Kepadatan penduduk memang faktor keselamatan penting kerana ia menentukan bilangan orang terdedah jika berlaku kemalangan."},
 {j:"pilih",t:"Sebelum membenarkan pembinaan loji nuklear, pihak berkuasa memerlukan pelan pengurusan sisa radioaktif jangka panjang. Mengapa syarat ini penting?",p:["Sisa radioaktif kekal berbahaya lama dan perlu disimpan selamat","Sisa radioaktif hilang dengan sendirinya dalam masa seminggu sahaja","Sisa radioaktif boleh dibuang terus ke dalam sungai tanpa kesan buruk","Sisa radioaktif tidak memerlukan sebarang pengurusan khas langsung"],b:0,u:"Sesetengah sisa radioaktif mengambil masa yang sangat lama untuk mereput ke tahap selamat."},
 {j:"banyak",t:"Pilih SEMUA faktor yang wajar dinilai sebelum keputusan membina loji nuklear dibuat.",p:["Kestabilan geologi dan risiko bencana alam","Pelan pengurusan sisa radioaktif jangka panjang","Kepadatan penduduk berhampiran tapak","Warna bendera rasmi negara jiran berdekatan","Kos pembinaan dan keupayaan kewangan negara"],b:[0,1,2,4],u:"Warna bendera negara jiran tiada kaitan saintifik atau teknikal dengan keselamatan dan kewajaran loji."},
 {j:"pilih",t:"Seorang pembuat dasar berkata 'kita patut tolak semua tenaga nuklear kerana pernah berlaku bencana Chernobyl dan Fukushima'. Nilaikan hujah ini.",p:["Terlalu mudah; perlu juga menilai sebab dan langkah keselamatan moden","Sepenuhnya tepat dan tidak perlu sebarang penilaian lanjut","Tidak relevan kerana kedua-dua bencana itu tidak berkaitan tenaga nuklear langsung","Tepat, kerana semua loji nuklear di dunia mengalami masalah yang sama sahaja"],b:0,u:"Penilaian wajar mengambil kira sebab kejadian dan penambahbaikan keselamatan, bukan hanya menolak semua kemungkinan."},
 {j:"pilih",t:"Apakah keputusan paling wajar jika kajian kebolehlaksanaan mendapati tapak yang dicadangkan berisiko tinggi gempa bumi?",p:["Cari tapak alternatif yang lebih stabil atau tangguhkan cadangan itu","Teruskan pembinaan seperti dirancang tanpa sebarang perubahan langsung","Abaikan risiko gempa bumi kerana ia dianggap jarang berlaku","Kurangkan saiz loji supaya risiko berkurang secara automatik sahaja"],b:0,u:"Risiko gempa bumi yang tinggi memerlukan tindakan seperti mencari tapak lain, bukan diabaikan."},
 {j:"pilih",t:"Bandingkan menyokong tenaga nuklear semata-mata kerana ia rendah karbon, berbanding menyokongnya selepas menilai keselamatan, kos dan pengurusan sisa. Yang manakah keputusan lebih wajar?",p:["Keputusan berdasarkan penilaian menyeluruh lebih wajar","Kedua-dua pendekatan itu dianggap sama wajar sahaja","Menyokong kerana rendah karbon sudah mencukupi tanpa penilaian lain lagi","Faktor keselamatan dan sisa tidak perlu dinilai jika kos rendah sahaja"],b:0,u:"Keputusan yang baik mengambil kira pelbagai faktor, bukan hanya satu kelebihan tunggal."}],
 bos:{j:"pilih",t:"Sebuah jawatankuasa kerajaan perlu membuat cadangan akhir tentang tenaga nuklear di Malaysia. Susunan pertimbangan manakah paling wajar?",p:["Nilai keselamatan tapak, sisa, kos dan penerimaan awam sebelum cadangan","Buat keputusan berdasarkan negara mana yang paling ramai membina loji nuklear itu","Buat keputusan berdasarkan pendapat popular di media sosial itu sahaja","Tolak terus tanpa sebarang kajian kerana risiko dianggap terlalu tinggi sekali"],b:0,u:"Keputusan bertaklim memerlukan penilaian menyeluruh berasaskan bukti, bukan mengikut populariti atau menolak tanpa kajian."}},

{n:6, tempat:"Bilik Reka Bentuk", sk:"12.1 / 12.2 / 12.4 Mereka cipta cadangan tenaga",
 kadNama:"Sistem Hibrid", kadEm:"\u{1F9E9}", kadFakta:"Loji tenaga hibrid menggabungkan lebih daripada satu sumber tenaga supaya bekalan elektrik kekal stabil dan lebih mampan.",
 bosKadNama:"Pelan Induk Tenaga", bosKadEm:"\u{1F5FA}", bosKadFakta:"Pelan induk tenaga sesebuah negara biasanya dirangka untuk tempoh 20 hingga 30 tahun supaya pembangunan infrastruktur dapat dirancang lebih awal.",
 soalan:[
 {j:"pilih",t:"Sebuah bandar baharu ingin merancang bekalan tenaga yang mampan untuk 50 tahun akan datang. Kombinasi manakah paling seimbang?",p:["Gabungan nuklear untuk bekalan stabil, ditambah suria dan angin untuk mengurangkan sisa","Arang batu sahaja digunakan kerana ia paling murah","Suria sahaja digunakan tanpa sebarang sokongan sumber lain","Nuklear sahaja digunakan tanpa sebarang sumber alternatif"],b:0,u:"Gabungan sumber mengimbangi kestabilan bekalan dengan pengurangan sisa dan karbon."},
 {j:"pilih",t:"Apakah inovasi yang boleh mengurangkan risiko sisa radioaktif jangka panjang pada masa hadapan?",p:["Teknologi kitar semula bahan api nuklear mengurangkan jumlah sisa","Membuang sisa terus ke dalam laut tanpa sebarang rawatan","Menyimpan sisa itu di kawasan berpenduduk padat sahaja","Membakar sisa radioaktif seperti sampah biasa sahaja"],b:0,u:"Kitar semula bahan api mengurangkan jumlah dan tempoh bahaya sisa yang perlu disimpan."},
 {j:"susun",t:"Susun langkah mereka cipta cadangan tenaga negara yang wajar.",p:["Kaji keperluan tenaga negara dan sumber sedia ada","Nilai kelebihan dan risiko setiap sumber tenaga","Reka cadangan gabungan sumber yang seimbang","Dapatkan maklum balas orang awam dan pakar","Perhalusi cadangan berdasarkan maklum balas"],b:[0,1,2,3,4],u:"Reka bentuk yang baik bermula dengan kajian, diikuti penilaian, cadangan awal, maklum balas, dan penambahbaikan."},
 {j:"pilih",t:"Mengapa penglibatan orang awam penting dalam merancang loji nuklear baharu?",p:["Membina keyakinan masyarakat terhadap keselamatan projek","Orang awam boleh menentukan reka bentuk teknikal reaktor itu","Penglibatan awam menghapuskan keperluan kajian kebolehlaksanaan penuh","Penglibatan awam hanya diperlukan selepas loji itu siap dibina"],b:0,u:"Kepercayaan awam penting untuk penerimaan projek, walaupun reka bentuk teknikal kekal di tangan pakar."},
 {j:"banyak",t:"Pilih SEMUA ciri reka bentuk yang menunjukkan inovasi keselamatan dalam loji nuklear moden.",p:["Sistem penyejukan sokongan jika sistem utama gagal","Naungan konkrit berganda di sekeliling reaktor","Pemantauan sinaran automatik yang berterusan","Membuang keperluan rod kawalan sepenuhnya","Pelan tindakan kecemasan untuk penduduk sekitar"],b:[0,1,2,4],u:"Rod kawalan tetap diperlukan untuk mengawal reaksi berantai; membuangnya bukan inovasi keselamatan."},
 {j:"pilih",t:"Sebuah pasukan pelajar mereka cipta model kertas loji tenaga hibrid (nuklear + suria). Apakah kelebihan reka bentuk ini berbanding hanya satu sumber?",p:["Bekalan kekal stabil walaupun cuaca berubah, kurang bergantung satu sumber","Kosnya pasti menjadi lebih rendah tanpa sebarang sebab teknikal yang jelas","Ia menghapuskan sepenuhnya keperluan pengurusan sisa yang ada","Ia tidak memerlukan sebarang kajian keselamatan tambahan langsung"],b:0,u:"Gabungan sumber memberi kelebihan kestabilan dan pengurangan pergantungan, bukan penghapusan sisa atau kajian keselamatan."},
 {j:"pilih",t:"Apakah faktor kreatif yang boleh ditambah pada pelan tenaga masa depan supaya lebih mampan, selain jenis sumber tenaga itu sendiri?",p:["Sistem simpanan tenaga bateri berskala besar mengimbangi bekalan tidak menentu","Membina lebih banyak loji tanpa sebarang perancangan yang jelas","Mengabaikan keperluan tenaga masa depan negara sepenuhnya","Menggunakan hanya satu jenis sumber untuk semua kawasan sahaja"],b:0,u:"Simpanan tenaga membantu mengimbangi sumber yang bekalannya tidak tetap seperti suria dan angin."},
 {j:"pilih",t:"Nilaikan cadangan 'gunakan tenaga nuklear sahaja dan berhenti membangunkan suria/angin' untuk masa depan Malaysia.",p:["Kurang wajar; kepelbagaian sumber mengurangkan risiko dan tingkat kemampanan","Wajar sepenuhnya kerana nuklear satu-satunya sumber rendah karbon sedia ada","Wajar kerana suria dan angin tidak berguna langsung buat masa ini","Kurang wajar, tetapi hanya kerana kos suria lebih tinggi daripada nuklear sahaja"],b:0,u:"Kepelbagaian sumber tenaga mengurangkan risiko berbanding pergantungan kepada satu sumber sahaja."}],
 bos:{j:"buka",
  t:"Bayangkan awak dilantik sebagai penasihat tenaga untuk merancang bekalan elektrik Malaysia 30 tahun akan datang. Reka satu cadangan gabungan sumber tenaga yang mengambil kira kestabilan bekalan, kos, pelepasan karbon dan pengurusan sisa.",
  arahan:"Nyatakan sumber tenaga yang dicadangkan (termasuk peratusan kasar setiap sumber jika sesuai), justifikasi bagi setiap pilihan, dan satu langkah untuk menangani risiko atau sisa yang timbul.",
  u:"Jawapan TP6 yang kukuh menggabungkan kestabilan bekalan, kos, alam sekitar dan keselamatan dalam satu cadangan yang seimbang, bukan hanya memilih satu sumber tenaga sahaja."}}
];

module.exports = {
  id:"t4b10", tingkatan:4, kod:"12.0 Tenaga Nuklear",
  tajuk:"Laluan Inti",
  subtajuk:"Sains Ting. 4 · Bab 12 Tenaga Nuklear",
  spi:SPI,
  /* Ulasan PBD mengikut tahap penguasaan. {n} diganti dengan nama pertama murid. */
  ulasan:{
   1:"{n} dapat mengingat kembali fakta asas tentang pembelahan dan pelakuran nukleus serta istilah berkaitan tenaga nuklear. Langkah seterusnya ialah menerangkan bagaimana proses ini menghasilkan tenaga, bukan sekadar menamakannya.",
   2:"{n} memahami mekanisme reaktor nuklear, termasuk fungsi rod kawalan dan bahan penyejuk dalam menghasilkan elektrik. Perlu lebih banyak latihan mengaitkan setiap komponen dengan fungsinya sebelum bergerak ke TP3.",
   3:"{n} boleh mengaplikasikan pengetahuan tentang pelbagai sumber tenaga untuk membuat perbandingan mudah berdasarkan data. Galakkan mentafsir jadual dengan lebih terperinci.",
   4:"{n} mampu menganalisis kesan sejarah dan persekitaran akibat penggunaan tenaga nuklear untuk senjata dan ujian. Seterusnya latih membezakan kesan serta-merta dan kesan jangka panjang dengan lebih jelas.",
   5:"{n} dapat menilai kewajaran cadangan berkaitan tenaga nuklear berdasarkan bukti seperti keselamatan tapak, kos dan pengurusan sisa. Sudah bersedia untuk tugasan mereka cipta cadangan sendiri.",
   6:"{n} berjaya mereka cipta cadangan gabungan sumber tenaga yang mengambil kira kestabilan, kos, alam sekitar dan keselamatan. Pencapaian cemerlang bagi bab ini.",
   tiada:"{n} belum menunjukkan bukti penguasaan yang mencukupi bagi bab Tenaga Nuklear. Cadangan: ulang aktiviti hentian pertama dengan bimbingan rakan sebaya."
  },
  lampiran:{ belahan:R_BELAHAN, reaktor:R_REAKTOR, sumber:T_SUMBER },
  aras:ARAS
};
