/* Sumber kandungan — Sains KSSM Tingkatan 4, Bidang 10.0 Kimia dalam Perubatan dan Kesihatan.
   Fail ini disunting tangan. Jalankan `node bina.js t4b8` untuk menyemaknya
   dan menghasilkan bank-t4b8.js dengan kedudukan jawapan yang seimbang.

   Standard Prestasi disalin kata demi kata daripada DSKP KSSM Sains
   Tingkatan 4, Bahagian Pembangunan Kurikulum, muka 93.

   Tulis jawapan betul pada indeks 0. Pembina akan mengagihkannya. */

const SPI = [
"Mengingat kembali pengetahuan dan kemahiran sains mengenai kimia dalam perubatan dan kesihatan.",
"Memahami kimia dalam perubatan dan kesihatan dan dapat menjelaskan kefahaman tersebut.",
"Mengaplikasikan pengetahuan mengenai kimia dalam kesihatan dan perubatan dan dapat melaksanakan tugasan mudah.",
"Menganalisis pengetahuan mengenai kimia dalam kesihatan dan perubatan dalam konteks penyelesaian masalah mengenai kejadian atau fenomena alam.",
"Menilai pengetahuan mengenai kimia dalam kesihatan dan perubatan dalam konteks penyelesaian masalah dan membuat keputusan untuk melaksanakan satu tugasan.",
"Mencipta dengan menggunakan pengetahuan dan kemahiran sains mengenai kimia dalam kesihatan dan perubatan dalam konteks penyelesaian masalah dan membuat keputusan atau dalam melaksanakan satu tugasan dalam situasi baharu secara kreatif dan inovatif dengan mengambil kira nilai sosial/ekonomi/budaya masyarakat."];

/* ---------- lampiran ---------- */

const R_RADIKAL = {
  jenis:"aliran", mod:"turun",
  nod:[
    { label:"Molekul oksigen kehilangan satu elektron", isi:"kuningLembut", panah:"kuning" },
    { label:"Radikal bebas terbentuk, tidak stabil", isi:"merahLembut", panah:"merah" },
    { label:"Radikal bebas merampas elektron daripada sel sihat", isi:"merahLembut", panah:"merah" },
    { label:"Bahan antioksida menderma elektron kepada radikal bebas", isi:"hijauLembut", panah:"hijau" },
    { label:"Radikal bebas dineutralkan, sel kekal selamat", isi:"hijauLembut" },
  ],
  kapsyen:"Rajah 1 · Bagaimana radikal bebas terbentuk dan dineutralkan oleh antioksida.",
  alt:"Rajah aliran menegak lima peringkat: oksigen kehilangan elektron, radikal bebas terbentuk, merampas elektron sel sihat, antioksida menderma elektron, radikal bebas dineutralkan"
};

const R_LABEL = {
  jenis:"struktur", mod:"label", rangka:true, tinggiLukis:150,
  bahagian:[
    { label:"Bahan aktif", bentuk:"kotak", x:50, y:14, l:80, t:14, isi:"lembayungLembut" },
    { label:"Dos disyorkan", bentuk:"kotak", x:50, y:38, l:80, t:14, isi:"kuningLembut" },
    { label:"No. KKM", bentuk:"kotak", x:50, y:62, l:80, t:14, isi:"hijauLembut" },
    { label:"Tarikh luput", bentuk:"kotak", x:50, y:86, l:80, t:14, isi:"merahLembut" },
  ],
  kapsyen:"Rajah 2 · Maklumat yang wajib ada pada label produk kesihatan berdaftar.",
  alt:"Rajah label produk kesihatan menunjukkan empat bahagian dari atas ke bawah: nama produk dan bahan aktif, dos disyorkan, nombor pendaftaran KKM, dan tarikh luput"
};

const T_EPAL =
'<div class="scrollx"><table class="datatable"><thead><tr><th>Rawatan hirisan epal</th>'+
'<th class="n">Masa mula perang (minit)</th><th>Catatan</th></tr></thead><tbody>'+
'<tr><td>Tiada rawatan (kawalan)</td><td class="n">4</td><td>Permukaan terdedah terus kepada udara</td></tr>'+
'<tr><td>Disapu garam</td><td class="n">9</td><td>Perang bermula lebih lambat daripada kawalan</td></tr>'+
'<tr><td>Disapu jus lemon</td><td class="n">22</td><td>Permukaan masih segar selepas 20 minit</td></tr>'+
'<tr><td>Disapu natrium bikarbonat</td><td class="n">7</td><td>Perang bermula hampir sama dengan garam</td></tr>'+
'</tbody></table></div><p class="qnote">Empat hirisan daripada epal yang sama disapu dengan rawatan berlainan, kemudian didedahkan kepada udara terbuka pada masa yang sama. Masa diambil sehingga permukaan hirisan mula bertukar perang direkod.</p>';

/* ---------- hentian ---------- */

const ARAS = [

{n:1, tempat:"Tabib", sk:"10.1 Jenis perubatan",
 kadNama:"Perubatan Tradisional", kadEm:"\u{1F33F}", kadFakta:"Perubatan tradisional Melayu, Cina dan India telah diamalkan di Malaysia jauh sebelum perubatan moden diperkenalkan oleh penjajah British.",
 bosKadNama:"Analgesik", bosKadEm:"\u{1F48A}", bosKadFakta:"Parasetamol ialah analgesik yang paling banyak digunakan di dunia, tetapi ia tidak tergolong dalam kumpulan ubat anti-radang seperti aspirin.",
 soalan:[
 {j:"pilih",t:"Perubatan yang menggabungkan kaedah tradisional bersama rawatan perubatan moden dipanggil:",p:["Perubatan komplementari","Perubatan tradisional sepenuhnya","Perubatan moden sepenuhnya","Perubatan psikoteraputik"],b:0,u:"Komplementari bermaksud digunakan bersama, bukan menggantikan perubatan moden."},
 {j:"pilih",t:"Ubat yang digunakan untuk merawat masalah kesihatan mental dan emosi dipanggil ubat:",p:["Psikoteraputik","Ubat tahan sakit dan demam seperti parasetamol","Ubat yang membunuh bakteria penyebab jangkitan","Bahan yang menstabilkan radikal bebas dalam badan"],b:0,u:"Psiko merujuk kepada minda, teraputik bermaksud rawatan."},
 {j:"pilih",t:"Ubat yang digunakan untuk membunuh atau menghalang pertumbuhan bakteria dipanggil:",p:["Antibiotik","Analgesik","Psikoteraputik","Antioksida"],b:0,u:"Anti bermaksud melawan, biotik merujuk kepada hidupan seperti bakteria."},
 {j:"pilih",t:"Ubat yang digunakan untuk melegakan kesakitan tanpa merawat puncanya dipanggil:",p:["Ubat analgesik biasa","Antibiotik","Psikoteraputik","Antiseptik"],b:0,u:"Analgesik meredakan rasa sakit, bukan membunuh punca penyakit."},
 {j:"pilih",t:"Manakah contoh amalan perubatan tradisional yang masih diamalkan di Malaysia?",p:["Bertungku dan berurut selepas bersalin","Suntikan vaksin di klinik kesihatan kerajaan","Pembedahan menggunakan bantuan robot canggih","Rawatan sinaran radioterapi untuk kanser"],b:0,u:"Bertungku dan berurut ialah amalan tradisional turun-temurun, manakala tiga pilihan lain ialah perubatan moden."},
 {j:"pilih",t:"Akupunktur, yang berasal daripada perubatan tradisional Cina, kini turut ditawarkan di sesetengah hospital kerajaan bersama rawatan moden. Ini contoh:",p:["Perubatan komplementari","Perubatan moden sepenuhnya","Penyalahgunaan ubat","Perubatan psikoteraputik"],b:0,u:"Rawatan tradisional yang digunakan bersama sistem hospital moden ialah amalan komplementari."},
 {j:"pilih",t:"Antibiotik tidak berkesan untuk merawat:",p:["Jangkitan yang disebabkan oleh virus","Jangkitan yang disebabkan oleh bakteria","Luka yang dijangkiti bakteria","Radang tekak akibat bakteria"],b:0,u:"Antibiotik hanya bertindak ke atas bakteria, bukan virus."},
 {j:"banyak",t:"Pilih SEMUA yang tergolong dalam kumpulan ubat moden.",p:["Analgesik","Antibiotik","Psikoteraputik","Bertungku","Tuisyen"],b:[0,1,2],u:"Bertungku ialah amalan tradisional, dan tuisyen bukan ubatan."}],
 bos:{j:"pilih",t:"Seorang ibu memberi anaknya madu dan halia untuk batuk ringan, dan turut menghantarnya ke klinik untuk pemeriksaan. Gabungan tindakan ini paling tepat digambarkan sebagai:",p:["Perubatan komplementari","Penyalahgunaan ubat","Perubatan psikoteraputik sahaja","Perubatan moden sepenuhnya"],b:0,u:"Menggabungkan amalan tradisional (madu dan halia) dengan pemeriksaan perubatan moden ialah definisi komplementari."}},

{n:2, tempat:"Farmasi", sk:"10.1 Sumber ubatan & kewajaran penggunaan",
 kadNama:"Vitamin C Sintetik", kadEm:"\u{1F34A}", kadFakta:"Struktur kimia vitamin C sintetik dan vitamin C daripada buah-buahan adalah SAMA; badan tidak dapat membezakan sumbernya.",
 bosKadNama:"Kesan Sampingan", bosKadEm:"\u{26A0}", bosKadFakta:"Hampir semua ubat berkesan mempunyai kesan sampingan; keputusan perubatan sentiasa menimbang manfaat berbanding risiko.",
 soalan:[
 {j:"pilih",t:"Mengapakah vitamin C daripada buah-buahan segar sering disyorkan berbanding makanan tambahan?",p:["Buah turut membekalkan serat dan nutrien lain yang tiada dalam pil vitamin","Vitamin C dalam buah mempunyai struktur kimia berbeza daripada pil vitamin","Pil vitamin C tidak dapat diserap langsung oleh badan manusia","Buah-buahan tidak mengandungi sebarang bahan kimia tambahan"],b:0,u:"Dari segi kimia, vitamin C adalah sama tidak kira sumbernya; kelebihan buah ialah nutrien tambahan yang turut dibawanya."},
 {j:"pilih",t:"Mengapakah ubat perlu diambil mengikut dos yang ditetapkan oleh doktor atau ahli farmasi?",p:["Dos yang berlebihan boleh membawa kesan sampingan yang serius","Dos yang lebih rendah daripada ditetapkan selalu selamat diambil","Dos hanya penting untuk ubat yang mahal harganya","Semua ubat mempunyai dos yang sama tidak kira usia pesakit"],b:0,u:"Dos ditetapkan berdasarkan kajian keselamatan; melebihinya meningkatkan risiko kesan sampingan."},
 {j:"pilih",t:"Mengapakah antibiotik yang diberi doktor perlu dihabiskan walaupun pesakit sudah rasa sihat?",p:["Bakteria yang masih tertinggal boleh membiak semula dan menjadi rintang","Antibiotik akan rosak dan menjadi toksik jika disimpan selepas dibuka","Ubat yang berbaki mesti dikembalikan kepada farmasi mengikut undang-undang","Membiarkan baki ubat tidak memberi sebarang kesan kepada rawatan"],b:0,u:"Menghentikan antibiotik awal membenarkan bakteria yang masih hidup membiak dan membentuk rintangan."},
 {j:"pilih",t:"Paracetamol, ubat batuk dan antibiotik semuanya perlu diambil mengikut dos yang ditetapkan. Apakah persamaan sebab di sebalik peraturan ini?",p:["Pengambilan tidak mengikut dos boleh menjejaskan kesihatan pesakit","Ketiga-tiga ubat ini hanya berkesan jika diambil pada waktu malam sebelum tidur","Ubat-ubat ini hanya boleh dijual dengan preskripsi khas doktor pakar sahaja","Ketiga-tiga ubat ini tidak mempunyai sebarang kesan sampingan langsung"],b:0,u:"Dos yang tidak tepat, sama ada berlebihan atau tidak cukup, boleh memudaratkan pesakit."},
 {j:"pilih",t:"Apakah risiko utama pengambilan ubat tidak mengikut peringkat umur yang ditetapkan?",p:["Kesan ubat pada kanak-kanak boleh berbeza dan lebih berbahaya berbanding dewasa","Ubat akan hilang keberkesanannya sepenuhnya serta-merta jika diambil oleh kanak-kanak","Kanak-kanak tidak dapat menelan sebarang jenis ubat dalam bentuk pil sama sekali","Peringkat umur hanya mempengaruhi rasa ubat sahaja, bukan kesannya ke atas badan"],b:0,u:"Fungsi organ kanak-kanak masih berkembang, jadi dos dewasa boleh memudaratkan mereka."},
 {j:"pilih",t:"Kebergantungan berlebihan kepada ubat tidur boleh membawa kepada:",p:["Badan memerlukan dos yang semakin tinggi lagi untuk kesan yang sama","Badan menjadi kebal sepenuhnya terhadap semua jenis penyakit lain","Ubat tidur itu bertukar menjadi analgesik selepas digunakan lama","Kualiti tidur bertambah baik secara berterusan tanpa sebarang had"],b:0,u:"Ini dipanggil toleransi ubat, salah satu risiko utama penyalahgunaan."},
 {j:"pilih",t:"Manakah contoh penyalahgunaan ubat?",p:["Mengambil ubat lama tanpa nasihat","Menghabiskan kesemua antibiotik mengikut tempoh yang ditetapkan oleh doktor","Bertanya ahli farmasi tentang kesan sampingan sebelum mengambil sebarang ubat","Menyimpan ubat mengikut suhu penyimpanan yang dinyatakan pada label"],b:0,u:"Menggunakan ubat lama untuk masalah berbeza tanpa nasihat profesional ialah penyalahgunaan."},
 {j:"susun",t:"Susun langkah yang wajar sebelum seseorang mengambil ubat baharu, daripada yang paling awal.",p:["Berjumpa doktor atau ahli farmasi","Mendapatkan preskripsi atau nasihat dos","Membaca label dan arahan penggunaan","Mengambil ubat mengikut dos yang betul"],b:[0,1,2,3],u:"Nasihat profesional perlu datang dahulu sebelum ubat digunakan mengikut label."}],
 bos:{j:"pilih",t:"Seorang remaja mengambil ubat batuk abangnya yang dewasa kerana sukatan di rumah kehabisan. Apakah risiko utama tindakan ini?",p:["Dos untuk dewasa mungkin tidak sesuai dan memudaratkan remaja itu","Ubat batuk tidak mempunyai sebarang risiko tidak kira siapa penggunanya","Ubat batuk abang akan menjadi tidak berkesan selepas dikongsi","Tindakan ini digalakkan asalkan jenis batuknya adalah sama"],b:0,u:"Dos ubat selalunya ditetapkan mengikut berat badan dan umur, bukan sekadar jenis simptom."}},

{n:3, tempat:"Sel Terjejas", sk:"10.2 Radikal bebas", lampiran:"radikal",
 kadNama:"Radikal Bebas", kadEm:"\u{26A1}", kadFakta:"Badan manusia sebenarnya menghasilkan sedikit radikal bebas secara semula jadi semasa proses respirasi sel, tetapi masalah timbul apabila jumlahnya berlebihan.",
 bosKadNama:"Penuaan Kulit", bosKadEm:"\u{1F9EC}", bosKadFakta:"Kerosakan kolagen kulit akibat radikal bebas daripada sinar UV matahari ialah salah satu punca utama kedutan awal.",
 soalan:[
 {j:"pilih",t:"Apakah maksud radikal bebas?",p:["Molekul tidak stabil yang kehilangan satu elektron","Molekul yang mempunyai bilangan elektron genap dan stabil","Sejenis vitamin yang terdapat dalam buah-buahan segar","Sejenis ubat yang digunakan untuk merawat jangkitan bakteria"],b:0,u:"Kehilangan elektron menjadikan molekul itu tidak stabil dan reaktif."},
 {j:"pilih",t:"Berdasarkan Rajah 1, mengapakah radikal bebas dianggap berbahaya kepada sel badan?",p:["Ia merampas elektron daripada sel sihat untuk menstabilkan dirinya","Ia menghasilkan tenaga berlebihan yang membakar tisu badan","Ia menukar sel sihat kepada bahan antioksida secara langsung","Ia menghalang oksigen daripada memasuki sistem peredaran darah"],b:0,u:"Radikal bebas menstabilkan dirinya dengan merampas elektron, mencetuskan rantaian kerosakan pada sel lain."},
 {j:"pilih",t:"Berdasarkan Rajah 1, apakah peranan bahan antioksida dalam proses ini?",p:["Menderma elektron kepada radikal bebas supaya ia menjadi stabil","Menghasilkan lebih banyak radikal bebas untuk melindungi sel badan","Menyerap semua oksigen daripada udara supaya sel tidak bernafas","Memusnahkan terus semua sel yang telah rosak akibat radikal bebas"],b:0,u:"Antioksida menstabilkan radikal bebas dengan menderma elektronnya sendiri, menghentikan rantaian kerosakan."},
 {j:"pilih",t:"Pendedahan berlebihan kepada asap rokok dikaitkan dengan peningkatan radikal bebas dalam badan. Apakah kesan jangka panjang yang paling mungkin?",p:["Kerosakan sel yang berterusan dan meningkatkan risiko penyakit kronik","Peningkatan kadar penyembuhan luka badan secara mendadak dan kekal","Peningkatan jumlah bahan antioksida semula jadi dalam badan secara automatik","Sel badan menjadi lebih stabil dan kuat kerana biasa dengan radikal bebas"],b:0,u:"Radikal bebas berlebihan yang berterusan merosakkan sel dari semasa ke semasa, meningkatkan risiko penyakit seperti kanser dan penyakit jantung."},
 {j:"pilih",t:"Mengapakah badan manusia tetap memerlukan sedikit radikal bebas walaupun ia berbahaya dalam kuantiti besar?",p:["Ia terhasil secara semula jadi daripada proses respirasi sel yang penting","Ia satu-satunya sumber tenaga yang digunakan oleh sel badan","Ia menggantikan fungsi oksigen dalam sistem peredaran darah","Ia diperlukan untuk menghasilkan semua jenis vitamin dalam badan"],b:0,u:"Radikal bebas terhasil sebagai kesan sampingan proses semula jadi seperti respirasi sel; masalah timbul apabila jumlahnya berlebihan."},
 {j:"pilih",t:"Sinar UV daripada matahari dikaitkan dengan pembentukan radikal bebas pada kulit. Apakah langkah paling wajar untuk mengurangkan risiko ini?",p:["Menggunakan pelindung matahari yang mengandungi bahan antioksida","Mengelakkan sepenuhnya semua jenis buah-buahan dan sayur-sayuran segar","Meningkatkan pendedahan kepada matahari untuk membiasakan kulit sendiri","Mengurangkan pengambilan air minuman untuk melambatkan proses pengoksidaan"],b:0,u:"Pelindung matahari berasaskan antioksida membantu menstabilkan radikal bebas yang terbentuk akibat sinar UV."},
 {j:"pilih",t:"Manakah PALING tepat menerangkan hubungan antara oksigen dan radikal bebas?",p:["Sesetengah molekul oksigen boleh kehilangan elektron dan menjadi radikal bebas","Oksigen sentiasa menjadi radikal bebas sebaik sahaja ia disedut masuk ke dalam badan","Radikal bebas ialah satu bentuk oksigen tulen yang tiada sebarang elektron langsung","Oksigen dan radikal bebas sebenarnya ialah dua sebutan bagi bahan kimia yang sama"],b:0,u:"Radikal bebas terbentuk apabila molekul, termasuk sesetengah bentuk oksigen, kehilangan elektron — bukan semua oksigen menjadi radikal bebas."},
 {j:"susun",t:"Susun peringkat proses dalam Rajah 1 daripada yang paling awal.",p:["Molekul oksigen kehilangan satu elektron","Radikal bebas terbentuk dan tidak stabil","Radikal bebas merampas elektron daripada sel sihat","Bahan antioksida menderma elektron dan menstabilkannya"],b:[0,1,2,3],u:"Urutan ini mengikut tepat aliran dalam Rajah 1."}],
 bos:{j:"banyak",t:"Pilih SEMUA faktor yang boleh meningkatkan pembentukan radikal bebas dalam badan.",p:["Merokok","Pendedahan berlebihan kepada sinar UV","Pencemaran udara","Pengambilan buah-buahan segar setiap hari","Rehat yang mencukupi"],b:[0,1,2],u:"Buah-buahan segar dan rehat mencukupi membantu MENGURANGKAN kesan radikal bebas, bukan meningkatkannya."}},

{n:4, tempat:"Makmal Antioksida", sk:"10.3 Bahan antioksida & eksperimen", lampiran:"epal",
 kadNama:"Pengoksidaan", kadEm:"\u{1F34E}", kadFakta:"Perubahan warna epal kepada perang selepas dihiris ialah tindak balas pengoksidaan enzim, sama seperti proses yang mengaratkan besi walaupun keduanya berlainan bahan kimia.",
 bosKadNama:"Pembolehubah Terkawal", bosKadEm:"\u{1F9EA}", bosKadFakta:"Eksperimen yang baik hanya mengubah SATU pembolehubah pada satu masa, supaya kesan yang diperhatikan boleh dikaitkan dengan yakin kepada punca yang betul.",
 soalan:[
 {j:"pilih",t:"Berdasarkan jadual, rawatan manakah paling berkesan melambatkan pengoksidaan epal?",p:["Jus lemon","Garam","Natrium bikarbonat","Tiada rawatan"],b:0,u:"Jus lemon mengambil masa paling lama (22 minit) untuk perang bermula."},
 {j:"pilih",t:"Mengapakah jus lemon berkesan melambatkan pengoksidaan berbanding rawatan lain dalam jadual?",p:["Kandungan vitamin C dalam lemon bertindak sebagai bahan antioksida","Ia menutup permukaan epal itu sepenuhnya daripada udara sekeliling","Jus lemon membunuh enzim yang terdapat dalam epal secara serta-merta","Jus lemon menyejukkan permukaan epal itu dengan lebih cepat dan ketara"],b:0,u:"Vitamin C dalam jus lemon ialah antioksida semula jadi yang melambatkan tindak balas pengoksidaan."},
 {j:"nombor",t:"Berapa minit lebih lama masa perang bermula bagi hirisan yang disapu jus lemon berbanding kawalan?",b:18,tol:0.5,suf:"minit",u:"22 tolak 4 bersamaan 18 minit."},
 {j:"pilih",t:"Apakah tujuan menyediakan hirisan epal tanpa sebarang rawatan (kawalan) dalam eksperimen ini?",p:["Sebagai rujukan untuk membandingkan kesan rawatan lain","Untuk memastikan sekurang-kurangnya satu epal tidak menjadi perang","Kerana epal itu akan dimakan selepas eksperimen selesai","Untuk menambah bilangan sampel supaya data kelihatan lebih banyak"],b:0,u:"Kawalan memberi asas perbandingan bagi menentukan sama ada rawatan lain benar-benar memberi kesan."},
 {j:"pilih",t:"Pembolehubah manakah WAJIB dimalarkan supaya perbandingan dalam eksperimen ini adil?",p:["Jenis epal, saiz hirisan dan keadaan persekitaran","Jenis rawatan yang disapu pada setiap hirisan","Masa yang diambil sehingga permukaan bertukar perang","Catatan pemerhatian bagi setiap hirisan epal"],b:0,u:"Jenis rawatan ialah pembolehubah dimanipulasi, dan masa ialah pembolehubah bergerak balas — kedua-duanya memang sepatutnya berbeza atau diukur."},
 {j:"pilih",t:"Mengapakah garam dan natrium bikarbonat turut melambatkan pengoksidaan walaupun kurang berkesan daripada jus lemon?",p:["Kedua-duanya turut mengganggu aktiviti enzim yang menyebabkan pengoksidaan","Kedua-duanya mengandungi vitamin C dalam kuantiti yang sama seperti lemon","Kedua-duanya menukar warna epal kepada perang dengan lebih pantas","Kedua-duanya tidak memberi sebarang kesan kepada proses pengoksidaan"],b:0,u:"Garam dan natrium bikarbonat mengganggu enzim penyebab pengoksidaan melalui mekanisme berbeza daripada antioksida vitamin C."},
 {j:"pilih",t:"Jika eksperimen ini diulang dengan menggunakan epal daripada jenis dan sumber yang berbeza bagi setiap rawatan, apakah masalahnya?",p:["Perbezaan hasil mungkin disebabkan jenis epal, bukan rawatan yang disapu","Eksperimen akan menjadi lebih tepat kerana lebih banyak jenis epal turut diuji","Tiada masalah kerana semua jenis epal mempunyai kandungan kimia yang sama","Keputusan akan diperoleh dengan lebih pantas menggunakan kaedah sebegini"],b:0,u:"Menggunakan epal berbeza memperkenalkan pembolehubah tidak terkawal yang mengelirukan kesimpulan."},
 {j:"banyak",t:"Pilih SEMUA penambahbaikan yang akan menguatkan kesimpulan eksperimen pengoksidaan epal ini.",p:["Ulang eksperimen beberapa kali dan ambil purata","Guna epal daripada pokok dan kematangan yang sama","Rekod suhu bilik semasa eksperimen dijalankan","Buang rawatan yang menunjukkan hasil paling perang","Guna hirisan dengan saiz permukaan yang berbeza-beza"],b:[0,1,2],u:"Membuang data yang tidak disukai dan mengubah saiz permukaan sesuka hati akan memburukkan, bukan menguatkan, kesahihan eksperimen."}],
 bos:{j:"banyak",t:"Sebuah syarikat mendakwa produk jus mereka \"kaya antioksida\" berdasarkan eksperimen seperti di atas. Pilih SEMUA soalan yang wajar ditanya sebelum mempercayai dakwaan itu.",p:["Berapa banyak ulangan dilakukan dan adakah keputusan itu konsisten?","Adakah eksperimen turut dijalankan oleh pihak bebas, bukan syarikat itu sahaja?","Berapa harga produk itu dijual berbanding produk lain di pasaran tempatan?","Apakah kandungan sebenar bahan aktif di dalamnya berbanding produk lain?"],b:[0,1,3],u:"Harga produk tidak berkaitan dengan kesahihan saintifik dakwaan \"kaya antioksida\"."}},

{n:5, tempat:"Rak Produk", sk:"10.4 Produk kesihatan", lampiran:"label",
 kadNama:"Bahan Aktif", kadEm:"\u{1F4CB}", kadFakta:"Dua produk kesihatan dengan jenama dan harga berbeza kadangkala mengandungi bahan aktif yang sama pada kuantiti yang sama.",
 bosKadNama:"Pendaftaran KKM", bosKadEm:"✅", bosKadFakta:"Produk kesihatan berdaftar dengan Kementerian Kesihatan Malaysia telah melalui penilaian keselamatan asas, tetapi pendaftaran tidak semestinya membuktikan keberkesanan yang didakwa.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 2, apakah maksud \"bahan aktif\" pada label produk kesihatan?",p:["Kandungan yang bertanggungjawab memberi kesan sebenar produk itu","Bahan pewarna yang ditambah supaya produk itu kelihatan lebih menarik","Nama syarikat yang mengeluarkan produk kesihatan tersebut di kilang","Harga jualan produk itu yang tertera pada label kemasan luar"],b:0,u:"Bahan aktif ialah komponen yang benar-benar memberi kesan farmakologi kepada pengguna."},
 {j:"pilih",t:"Mengapakah maklumat \"No. pendaftaran KKM\" pada Rajah 2 penting sebelum membeli produk kesihatan?",p:["Ia menunjukkan produk telah melalui penilaian keselamatan asas","Ia menjamin sepenuhnya produk itu pasti berkesan seperti yang didakwa","Ia menentukan harga jualan produk itu di seluruh pasaran tempatan","Ia hanya menunjukkan produk itu dibuat di kilang tempatan sahaja"],b:0,u:"Pendaftaran KKM ialah penanda keselamatan asas, bukan jaminan keberkesanan penuh dakwaan pemasaran."},
 {j:"pilih",t:"Dua produk vitamin C dijual dengan harga sangat berbeza tetapi label menunjukkan kandungan bahan aktif yang sama. Penilaian paling wajar?",p:["Harga tinggi tidak semestinya bermaksud kesan yang lebih baik","Produk yang lebih mahal itu sudah pasti jauh lebih selamat digunakan","Produk yang lebih murah itu tentu mengandungi bahan tiruan semata-mata","Kedua-dua produk itu tetap mesti mempunyai kesan yang berbeza sekali"],b:0,u:"Jika bahan aktif dan kuantitinya sama, harga tinggi tidak semestinya bermakna kesan yang lebih baik."},
 {j:"pilih",t:"Sebuah iklan mendakwa produknya boleh \"menyembuhkan semua penyakit\" tanpa menyatakan bahan aktif. Apakah penilaian paling wajar?",p:["Dakwaan itu meragukan kerana tiada bukti saintifik yang khusus dinyatakan","Dakwaan itu pasti benar kerana ia disiarkan secara meluas di banyak media","Dakwaan itu wajar dipercayai sepenuhnya kerana harga produk itu agak tinggi","Dakwaan itu sah sepenuhnya kerana ramai orang telah membeli produk itu"],b:0,u:"Dakwaan tanpa bukti saintifik khusus dan tanpa bahan aktif dinyatakan wajar disangsikan."},
 {j:"pilih",t:"Mengapakah tarikh luput pada Rajah 2 penting untuk keselamatan pengguna?",p:["Bahan aktif boleh terurai","Tarikh luput hanya menentukan harga diskaun yang ditawarkan oleh kedai","Produk itu hanya akan bertukar warna sahaja selepas tarikh luput berlalu","Tarikh luput langsung tidak memberi sebarang kesan kepada kualiti produk"],b:0,u:"Selepas tarikh luput, bahan aktif mungkin telah terurai dan tidak lagi selamat atau berkesan."},
 {j:"pilih",t:"Seorang penjual dalam talian menjual suplemen tanpa nombor pendaftaran KKM dengan harga sangat murah. Tindakan paling wajar?",p:["Elakkan membeli dan laporkan kepada pihak berkuasa berkaitan","Beli segera kerana harganya jauh lebih murah daripada di farmasi","Beli dan cuba dahulu sebelum menentukan sama ada ia selamat","Minta rakan menggunakannya dahulu sebelum membuat keputusan"],b:0,u:"Produk tanpa pendaftaran KKM tidak disahkan keselamatannya dan berisiko tinggi."},
 {j:"pilih",t:"Apakah kelebihan membaca label bahan aktif sebelum membeli dua produk berbeza jenama untuk kegunaan yang sama?",p:["Pengguna dapat membandingkan kandungan sebenar, bukan sekadar jenama","Label bahan aktif menentukan warna kemasan produk itu","Membaca label menjamin produk itu pasti yang paling murah","Label bahan aktif hanya diperlukan untuk produk import sahaja"],b:0,u:"Perbandingan bahan aktif membolehkan pengguna membuat keputusan berdasarkan kandungan sebenar, bukan jenama semata-mata."},
 {j:"banyak",t:"Pilih SEMUA maklumat yang WAJAR disemak sebelum membeli produk kesihatan.",p:["Bahan aktif dan kuantitinya","Nombor pendaftaran KKM","Tarikh luput","Warna kemasan botol","Bilangan pengikut media sosial penjual"],b:[0,1,2],u:"Warna kemasan dan populariti media sosial tidak berkaitan dengan keselamatan atau keberkesanan produk."}],
 bos:{j:"pilih",t:"Seorang warga emas mengambil tiga jenis suplemen berbeza serentak berdasarkan iklan televisyen sahaja, tanpa berbincang dengan doktor. Apakah risiko paling wajar dibimbangi?",p:["Interaksi antara bahan aktif berbeza yang boleh memudaratkan kesihatannya","Suplemen itu akan menjadi tidak berkesan langsung jika diambil bersama-sama","Warna kemasan ketiga-tiga produk itu mungkin tidak sepadan satu sama lain","Harga ketiga-tiga produk itu akan meningkat serentak dalam masa terdekat"],b:0,u:"Mengambil pelbagai bahan aktif tanpa nasihat profesional berisiko interaksi ubat yang tidak diketahui."}},

{n:6, tempat:"Klinik", sk:"10.1 / 10.4 Sintesis dan keputusan",
 kadNama:"Reka Bentuk Bertanggungjawab", kadEm:"\u{1F4A1}", kadFakta:"Kempen kesihatan awam yang paling berkesan biasanya menggabungkan fakta saintifik dengan cara penyampaian yang mudah difahami oleh masyarakat umum.",
 bosKadNama:"Literasi Kesihatan", bosKadEm:"\u{1F393}", bosKadFakta:"Literasi kesihatan, iaitu keupayaan memahami maklumat perubatan dengan betul, dikaitkan dengan keputusan kesihatan yang lebih baik sepanjang hayat seseorang.",
 soalan:[
 {j:"pilih",t:"Sebuah sekolah ingin mereka poster kesihatan tentang bahaya penyalahgunaan ubat untuk murid tingkatan satu. Pendekatan paling berkesan?",p:["Gunakan bahasa mudah dan contoh situasi harian yang relevan dengan murid","Gunakan istilah perubatan teknikal sepenuhnya tanpa sebarang penjelasan ringkas","Fokus hanya kepada statistik kematian semata-mata tanpa sebarang penyelesaian","Elakkan sepenuhnya menyebut sebarang contoh konkrit supaya murid tidak takut"],b:0,u:"Bahasa mudah dan contoh relevan lebih berkesan menyampaikan mesej kepada kumpulan sasaran muda."},
 {j:"pilih",t:"Klinik komuniti ingin menggalakkan penduduk kampung memilih perubatan moden untuk penyakit serius, tanpa menolak terus amalan tradisional mereka. Pendekatan paling bijak?",p:["Terangkan bila perubatan tradisional sesuai dan bila perubatan moden diperlukan segera","Larang sepenuhnya semua amalan perubatan tradisional dalam komuniti itu","Abaikan sahaja kepercayaan tradisional dan hanya gunakan risalah teknikal","Galakkan penduduk bergantung sepenuhnya kepada perubatan tradisional sahaja"],b:0,u:"Pendekatan hormat-menghormati yang menjelaskan bila setiap kaedah sesuai lebih berkesan daripada penolakan total."},
 {j:"pilih",t:"Sebuah farmasi komuniti ingin membantu pesakit lanjut usia mengingati senarai ubat yang kompleks. Reka bentuk paling praktikal?",p:["Kotak ubat berlabel mengikut hari dan waktu, disertai penerangan ringkas","Botol ubat tanpa sebarang label demi mengurangkan kekeliruan warna kemasan","Arahan lisan semata-mata tanpa sebarang bahan bertulis untuk dirujuk semula","Gabungkan semua jenis ubat dalam satu bekas tanpa sebarang pengasingan waktu"],b:0,u:"Sistem visual berlabel mengurangkan risiko tersilap dos berbanding arahan lisan sahaja yang mudah dilupa."},
 {j:"pilih",t:"Seorang usahawan muda ingin memasarkan suplemen herba tempatan secara bertanggungjawab. Langkah PALING wajar sebelum jualan?",p:["Dapatkan pendaftaran KKM dan sertakan bahan aktif serta amaran yang jelas","Gunakan testimoni pelanggan sahaja tanpa sebarang ujian keselamatan","Dakwa produk dapat menyembuhkan semua penyakit untuk menarik pembeli","Jual tanpa label bahan aktif supaya formula kekal dirahsiakan"],b:0,u:"Pendaftaran rasmi dan label yang jelas ialah asas pemasaran produk kesihatan yang bertanggungjawab dan sah dari segi undang-undang."},
 {j:"pilih",t:"Kajian mendapati ramai remaja berkongsi ubat preskripsi rakan tanpa nasihat doktor. Cadangan paling berkesan untuk mengurangkan amalan ini?",p:["Pendidikan kesihatan sekolah tentang risiko berkongsi ubat preskripsi","Menghentikan sepenuhnya penggunaan ubat preskripsi di kalangan remaja","Membenarkan pembelian semua ubat preskripsi tanpa sekatan","Mengabaikan isu ini kerana ia jarang membawa kesan buruk"],b:0,u:"Pendidikan yang menyasarkan punca tingkah laku lebih berkesan berbanding sekatan mutlak atau mengabaikan isu."},
 {j:"pilih",t:"Sebuah hospital ingin mengurangkan kesilapan dos ubat dalam kalangan pesakit yang mengambil pelbagai jenis ubat serentak. Penyelesaian paling sistematik?",p:["Sistem semakan silang oleh ahli farmasi sebelum ubat diserahkan kepada pesakit","Benarkan pesakit menentukan sendiri dos mengikut rasa selesa mereka","Kurangkan bilangan ahli farmasi untuk mempercepatkan proses pengeluaran ubat","Serahkan semua jenis ubat dalam satu bungkusan tanpa label berasingan"],b:0,u:"Semakan silang profesional ialah lapisan keselamatan sistematik yang mengurangkan risiko kesilapan dos."},
 {j:"pilih",t:"Bagaimanakah pengetahuan tentang radikal bebas dan antioksida boleh diterapkan dalam pemilihan diet harian yang praktikal?",p:["Menggalakkan pengambilan lebih banyak buah dan sayur kaya antioksida secara semula jadi","Menggantikan semua makanan harian dengan pil suplemen antioksida sahaja","Mengelakkan sepenuhnya makanan yang mengandungi oksigen","Hanya bergantung kepada produk kesihatan mahal untuk melawan radikal bebas"],b:0,u:"Sumber semula jadi seperti buah dan sayur ialah cara paling praktikal dan kos efektif untuk mendapatkan antioksida harian."},
 {j:"banyak",t:"Pilih SEMUA amalan yang menyumbang kepada penggunaan ubat dan produk kesihatan secara bertanggungjawab dalam masyarakat.",p:["Membaca label bahan aktif sebelum membeli","Menghabiskan antibiotik mengikut tempoh yang ditetapkan","Berkongsi ubat preskripsi dengan ahli keluarga yang sakit serupa","Melaporkan produk tanpa pendaftaran KKM kepada pihak berkuasa"],b:[0,1,3],u:"Berkongsi ubat preskripsi, walaupun dengan niat baik, tetap berisiko kerana dos dan keadaan kesihatan setiap individu berbeza."}],
 bos:{j:"buka",
  t:"Kampung Pak Man kerap menerima jualan suplemen kesihatan \"ajaib\" yang didakwa dapat menyembuhkan pelbagai penyakit tanpa bukti saintifik, dan ramai warga emas di situ mudah terpengaruh. Reka satu kempen kesihatan mudah untuk komuniti itu.",
  arahan:"Terangkan mesej utama kempen, cara ia disampaikan supaya sesuai dengan warga emas, bagaimana ia menghormati kepercayaan tradisional komuniti tanpa menolaknya terus, dan bagaimana kesannya boleh diukur.",
  u:"Jawapan TP6 yang kukuh menggabungkan kimia perubatan sebenar (bahan aktif, pendaftaran KKM, dakwaan tanpa bukti) dengan kepekaan sosial terhadap komuniti yang disasarkan."}}
];

module.exports = {
  id:"t4b8", tingkatan:4, kod:"10.0 Kimia dalam Perubatan dan Kesihatan",
  tajuk:"Laluan Penawar",
  subtajuk:"Sains Ting. 4 · Bab 10 Kimia dalam Perubatan dan Kesihatan",
  spi:SPI,
  ulasan:{
   1:"{n} dapat mengingat kembali jenis-jenis perubatan dan kategori ubat moden asas. Langkah seterusnya ialah menerangkan sebab di sebalik penggunaan setiap jenis ubat, bukan sekadar menamakannya.",
   2:"{n} memahami sebab dos dan sumber ubatan penting untuk keselamatan penggunaan. Perlu lebih banyak latihan mengaitkan konsep ini dengan situasi harian sebelum bergerak ke TP3.",
   3:"{n} boleh mengaplikasikan pengetahuan tentang radikal bebas dan antioksida untuk menerangkan proses berdasarkan rajah. Galakkan mengaitkan konsep ini dengan situasi seperti merokok atau pendedahan UV.",
   4:"{n} mampu menganalisis data eksperimen pengoksidaan makanan dan mengenal pasti pembolehubah yang perlu dikawal. Seterusnya latih menilai kesahan dakwaan produk berdasarkan bukti.",
   5:"{n} dapat menilai kewajaran dakwaan produk kesihatan berdasarkan label dan bukti, disokong pertimbangan keselamatan pengguna. Sudah bersedia untuk tugasan mereka kempen.",
   6:"{n} berjaya mereka cadangan kempen kesihatan yang praktikal dan sensitif terhadap komuniti, lengkap dengan mesej sains yang tepat. Pencapaian cemerlang bagi bab ini.",
   tiada:"{n} belum menunjukkan bukti penguasaan yang mencukupi bagi bab Kimia dalam Perubatan dan Kesihatan. Cadangan: ulang aktiviti hentian pertama dengan bimbingan rakan sebaya."
  },
  lampiran:{ radikal:R_RADIKAL, label:R_LABEL, epal:T_EPAL },
  aras:ARAS
};
