/* Sumber kandungan — Sains KSSM Tingkatan 4, Bidang 11.0 Daya dan Gerakan.
   Fail ini disunting tangan. Jalankan `node bina.js t4b9` untuk menyemaknya
   dan menghasilkan bank-t4b9.js dengan kedudukan jawapan yang seimbang.

   Standard Prestasi disalin kata demi kata daripada DSKP KSSM Sains
   Tingkatan 4, Bahagian Pembangunan Kurikulum, muka 103.

   Tulis jawapan betul pada indeks 0. Pembina akan mengagihkannya. */

const SPI = [
"Mengingat kembali pengetahuan dan kemahiran sains mengenai daya dan gerakan.",
"Memahami daya dan gerakan dalam melestarikan alam dan dapat menjelaskan kefahaman tersebut.",
"Mengaplikasikan pengetahuan mengenai daya dan gerakan dan dapat melaksanakan tugasan mudah.",
"Menganalisis pengetahuan mengenai daya dan gerakan dalam konteks penyelesaian masalah mengenai kejadian atau fenomena alam.",
"Menilai pengetahuan mengenai daya dan gerakan dalam konteks penyelesaian masalah dan membuat keputusan untuk melaksanakan satu tugasan.",
"Mencipta dengan menggunakan pengetahuan dan kemahiran sains mengenai daya dan gerakan dalam konteks penyelesaian masalah dan membuat keputusan atau dalam melaksanakan satu tugasan dalam situasi baharu secara kreatif dan inovatif dengan mengambil kira nilai sosial/ekonomi/budaya masyarakat."];

/* ---------- lampiran ---------- */

const R_GERAK = {
  jenis:"graf",
  x:[0,1,2,3,4],
  siri:[
    { label:"Objek A (halaju seragam)", y:[4,4,4,4,4], warna:"hijau" },
    { label:"Objek B (pecutan seragam)", y:[0,2,4,6,8], warna:"lembayung" }
  ],
  xLabel:"Masa (s)", titik:true,
  kapsyen:"Rajah 1 · Graf halaju-masa dua objek: Objek A bergerak dengan halaju seragam, Objek B memecut secara seragam.",
  alt:"Graf garis halaju melawan masa: Objek A garis mendatar pada 4 meter sesaat, Objek B garis menaik lurus dari 0 hingga 8 meter sesaat"
};

const R_JATUH = {
  jenis:"graf",
  x:[0,1,2,3],
  siri:[
    { label:"Jatuh bebas", y:[0,10,20,30], warna:"merah" },
    { label:"Bukan jatuh bebas", y:[0,8,13,15], warna:"hijau" }
  ],
  xLabel:"Masa (s)", titik:true,
  kapsyen:"Rajah 1 · Graf halaju-masa objek jatuh bebas berbanding objek yang mengalami rintangan udara.",
  alt:"Graf garis halaju melawan masa: garis jatuh bebas lurus menaik dari 0 hingga 30 meter sesaat, garis bukan jatuh bebas melengkung dan mula mendatar berhampiran 15 meter sesaat"
};

const R_REKA = {
  jenis:"aliran", mod:"turun",
  nod:[
    { label:"Kenal pasti masalah: bekalan rosak semasa dijatuhkan dari udara", isi:"hijauLembut", panah:"hijau" },
    { label:"Kaji pembolehubah: saiz kanopi, bahan kanopi, panjang dan bilangan tali", isi:"kuningLembut", panah:"kuning" },
    { label:"Bina prototaip payung terjun", isi:"lembayungLembut", panah:"lembayung" },
    { label:"Uji kadar jatuh dan ubah suai reka bentuk", isi:"merahLembut" }
  ],
  kapsyen:"Rajah 1 · Langkah reka bentuk payung terjun untuk menjatuhkan bekalan semasa banjir.",
  alt:"Rajah aliran menegak empat langkah reka bentuk payung terjun: kenal pasti masalah, kaji pembolehubah, bina prototaip, uji dan ubah suai"
};

/* ---------- hentian ---------- */

const ARAS = [

{n:1, tempat:"Get Set", sk:"11.1 Gerakan Linear", kadNama:"Kereta F1", kadEm:"\u{1F3CE}", kadFakta:"Kereta Formula 1 boleh memecut dari senaman diam hingga 100 km/j dalam kurang dua saat, iaitu pecutan lebih dua kali graviti Bumi.", bosKadNama:"Cheetah", bosKadEm:"\u{1F406}", bosKadFakta:"Cheetah boleh berlari hingga 104 km/j tetapi hanya mampu mengekalkan kelajuan itu selama beberapa saat sebelum ototnya terlalu panas.",
 soalan:[
 {j:"pilih",t:"Jarak ditakrifkan sebagai:",p:["Jumlah panjang laluan yang dilalui, kuantiti skalar","Jarak lurus dari titik mula ke titik akhir, kuantiti vektor","Kadar perubahan kedudukan, kuantiti vektor","Jumlah masa yang diambil untuk sesuatu perjalanan"],b:0,u:"Jarak ialah kuantiti skalar; ia hanya mempunyai magnitud tanpa arah."},
 {j:"pilih",t:"Sesaran ditakrifkan sebagai:",p:["Jarak lurus dan arah dari titik mula ke titik akhir","Jumlah panjang sebenar laluan yang dilalui objek","Kelajuan objek pada satu-satu saat tertentu","Jumlah tenaga yang digunakan sepanjang keseluruhan perjalanan itu"],b:0,u:"Sesaran ialah kuantiti vektor kerana ia mempunyai magnitud dan arah."},
 {j:"pilih",t:"Unit SI bagi laju dan halaju ialah:",p:["Meter sesaat (ms⁻¹)","Meter sahaja (m)","Meter sesaat sesaat (ms⁻²)","Saat sahaja (s)"],b:0,u:"Laju dan halaju sama-sama diukur dalam ms⁻¹; bezanya halaju ada arah."},
 {j:"pilih",t:"Unit SI bagi pecutan ialah:",p:["Meter sesaat sesaat (ms⁻²)","Meter sesaat (ms⁻¹), sama seperti laju dan halaju","Newton (N), iaitu unit bagi daya dan bukan pecutan","Kilogram (kg), iaitu unit bagi jisim sesuatu jasad"],b:0,u:"Pecutan ialah kadar perubahan halaju, jadi unitnya ms⁻¹ dibahagi s."},
 {j:"pilih",t:"Halaju ditakrifkan sebagai:",p:["Kadar perubahan sesaran","Kadar perubahan jarak","Kadar perubahan pecutan","Jumlah jarak dibahagi jumlah masa"],b:0,u:"Halaju = sesaran / masa, berbeza daripada laju yang menggunakan jarak."},
 {j:"pilih",t:"Pecutan ditakrifkan sebagai:",p:["Kadar perubahan halaju","Kadar perubahan sesaran","Kadar perubahan jarak","Jumlah halaju dibahagi jarak"],b:0,u:"Pecutan a = (v − u) / t, iaitu kadar perubahan halaju."},
 {j:"banyak",t:"Pilih SEMUA kuantiti vektor dalam senarai berikut.",p:["Sesaran","Halaju","Pecutan","Jarak","Laju","Masa"],b:[0,1,2],u:"Sesaran, halaju dan pecutan mempunyai arah, jadi ia kuantiti vektor. Jarak, laju dan masa hanya mempunyai magnitud."},
 {j:"nombor",t:"Sebuah basikal menempuh jarak 50 m dalam masa 10 s pada laju seragam. Berapakah lajunya, dalam ms⁻¹?",b:5,tol:0.2,suf:"ms⁻¹",u:"Laju = jarak / masa = 50 / 10 = 5 ms⁻¹."}],
 bos:{j:"banyak",t:"Pilih SEMUA formula yang betul.",p:["Laju = Jarak / Masa","Halaju = Sesaran / Masa","Pecutan = (Halaju akhir − Halaju awal) / Masa","Jarak = Pecutan / Masa","Halaju = Pecutan / Jarak"],b:[0,1,2],u:"Dua pilihan terakhir mencampuradukkan kuantiti yang tidak berkaitan secara terus dengan cara itu."}},

{n:2, tempat:"Trek Lurus", sk:"11.1 Gerakan Linear", kadNama:"Usain Bolt", kadEm:"\u{1F3C3}", kadFakta:"Halaju puncak Usain Bolt semasa rekod dunia 100 m ialah kira-kira 12.4 ms⁻¹, jauh lebih tinggi daripada laju purata keseluruhan larinya kerana dia perlu memecut dahulu dari pegun.", bosKadNama:"Shinkansen", bosKadEm:"\u{1F686}", bosKadFakta:"Kereta api peluru Jepun boleh mengekalkan halaju seragam melebihi 300 km/j sepanjang trek lurus beratus kilometer.",
 soalan:[
 {j:"pilih",t:"Ahmad memandu 90 km ke utara dalam masa 1 jam, kemudian 90 km ke selatan dalam masa 1 jam kembali ke tempat asal. Apakah halaju purata seluruh perjalanannya?",p:["0 kmj⁻¹, kerana sesaran keseluruhan ialah sifar","90 kmj⁻¹, kerana dia memandu pada laju yang tetap sepanjang perjalanan","180 kmj⁻¹, iaitu jumlah kedua-dua bahagian perjalanannya","45 kmj⁻¹, iaitu separuh daripada laju setiap bahagian perjalanan"],b:0,u:"Halaju purata bergantung pada sesaran, bukan jarak. Dia kembali ke tempat asal, jadi sesaran keseluruhan sifar."},
 {j:"pilih",t:"Berdasarkan situasi Ahmad di atas, apakah laju puratanya?",p:["90 kmj⁻¹, jumlah jarak 180 km dibahagi jumlah masa 2 jam","0 kmj⁻¹, sama seperti halaju puratanya sepenuhnya","180 kmj⁻¹, jumlah jarak tanpa dibahagi dengan masa","45 kmj⁻¹, kerana dia berpatah balik pada separuh jalan"],b:0,u:"Laju purata menggunakan jumlah jarak (180 km), bukan sesaran, jadi ia tidak sifar walaupun halaju purata sifar."},
 {j:"pilih",t:"Sebuah kereta bergerak ke timur pada 20 ms⁻¹ kemudian bertukar arah bergerak ke barat pada 20 ms⁻¹. Adakah halajunya berubah?",p:["Ya, kerana arah bergerak bertukar walaupun magnitud sama","Tidak, kerana magnitud halaju kekal pada 20 ms⁻¹","Ya, kerana laju kereta itu berkurang sebanyak separuh","Tidak, kerana pecutan kereta itu adalah sifar sepenuhnya"],b:0,u:"Halaju ialah kuantiti vektor. Perubahan arah bermakna halaju berubah walaupun lajunya tidak berubah."},
 {j:"pilih",t:"Apakah maksud pecutan bernilai negatif?",p:["Halaju objek berkurang mengikut masa, iaitu nyahpecutan","Objek itu bergerak ke arah bertentangan dengan asalnya","Objek itu berhenti serta-merta tanpa sebarang halaju","Laju objek itu sentiasa sifar sepanjang pergerakan itu berlangsung"],b:0,u:"Pecutan negatif (nyahpecutan) bermaksud halaju berkurang, bukan semestinya objek berpatah balik."},
 {j:"pilih",t:"Sebiji bola dilontar lurus ke atas. Semasa ia menghampiri titik tertinggi, apakah yang berlaku kepada halaju dan pecutannya?",p:["Halaju berkurang ke sifar, pecutan graviti kekal ke bawah","Halaju bertambah, pecutan graviti bertukar ke atas","Halaju dan pecutan kedua-duanya menjadi sifar serentak","Halaju kekal malar, hanya pecutan yang berkurang"],b:0,u:"Graviti sentiasa bertindak ke bawah walaupun bola sedang bergerak ke atas, jadi ia terus mengurangkan halaju bola."},
 {j:"pilih",t:"Manakah antara berikut ialah contoh halaju seragam?",p:["Kereta bergerak lurus pada bacaan speedometer tetap 90 kmj⁻¹","Kereta memecut laju dari pegun hingga 90 kmj⁻¹","Kereta membrek dan perlahan-lahan berhenti sepenuhnya","Kereta bergerak dalam bulatan pada laju yang tetap"],b:0,u:"Halaju seragam memerlukan magnitud DAN arah yang tidak berubah; pergerakan membulat sentiasa menukar arah."},
 {j:"pilih",t:"Mengapakah jurulatih larian menekankan fasa pecutan awal dan bukan hanya laju puncak?",p:["Laju purata keseluruhan bergantung pada kedua-dua fasa, bukan laju puncak sahaja","Laju puncak sentiasa dicapai serta-merta tanpa fasa pecutan","Fasa pecutan tidak memberi kesan kepada masa larian keseluruhan","Pelari yang lebih laju semasa pecutan pasti mempunyai laju puncak lebih rendah, walau apa pun keadaan treknya"],b:0,u:"Masa larian keseluruhan dipengaruhi oleh kedua-dua fasa memecut dan fasa laju tetap, bukan laju puncak sahaja."},
 {j:"nombor",t:"Sebuah motosikal bergerak dari halaju 5 ms⁻¹ kepada 17 ms⁻¹ dalam masa 4 s. Berapakah pecutannya, dalam ms⁻²?",b:3,tol:0.2,suf:"ms⁻²",u:"Pecutan = (17 − 5) / 4 = 12 / 4 = 3 ms⁻²."}],
 bos:{j:"pilih",t:"Seekor arnab berlari 30 m ke hadapan dalam 6 s, berhenti sebentar, kemudian berlari 30 m berpatah balik ke sarangnya dalam 5 s. Bandingkan laju purata dan halaju purata keseluruhan perjalanan itu.",p:["Laju purata lebih besar daripada sifar, halaju purata bersamaan sifar","Kedua-duanya bersamaan sifar kerana arnab kembali ke sarang","Kedua-duanya sama nilai kerana jarak dan sesaran adalah sama","Halaju purata lebih besar kerana arnab bergerak pada dua arah"],b:0,u:"Jumlah jarak 60 m memberi laju purata positif, tetapi sesaran keseluruhan sifar kerana arnab kembali ke titik asal."}},

{n:3, tempat:"Graf Gerakan", sk:"11.2 Graf Gerakan Linear", lampiran:"gerak", kadNama:"Jangka Masa Detik", kadEm:"\u{23F1}", kadFakta:"Jangka masa detik makmal biasa merekod satu titik pada carta pita setiap 0.02 saat, iaitu 50 kali sesaat.", bosKadNama:"Roket SpaceX", bosKadEm:"\u{1F680}", bosKadFakta:"Graf halaju-masa roket semasa pelancaran melengkung semakin curam kerana pecutannya bertambah apabila bahan apinya berkurangan dan jisimnya menyusut.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 1, jenis gerakan Objek A ialah:",p:["Halaju seragam, kerana graf itu garis mendatar","Pecutan seragam, kerana graf itu garis menaik","Nyahpecutan seragam, kerana graf itu garis menurun","Halaju tidak seragam, kerana graf itu melengkung"],b:0,u:"Garis mendatar pada graf halaju-masa bermaksud halaju tidak berubah mengikut masa."},
 {j:"pilih",t:"Berdasarkan Rajah 1, jenis gerakan Objek B ialah:",p:["Pecutan seragam, kerana graf itu garis lurus menaik","Halaju seragam, kerana graf itu garis mendatar","Nyahpecutan seragam, kerana halajunya berkurang secara beransur","Halaju tidak seragam, kerana graf itu melengkung sepanjang masa"],b:0,u:"Kecerunan tetap pada garis lurus menaik bermaksud pecutan yang malar."},
 {j:"nombor",t:"Berdasarkan Rajah 1, berapakah pecutan Objek B, dalam ms⁻²?",b:2,tol:0.2,suf:"ms⁻²",u:"Kecerunan = perubahan halaju / perubahan masa = (8 − 0) / (4 − 0) = 2 ms⁻²."},
 {j:"pilih",t:"Berdasarkan Rajah 1, bagaimanakah jarak yang ditempuh oleh setiap objek dikira daripada graf?",p:["Luas di bawah graf halaju-masa bagi tempoh masa berkenaan","Kecerunan graf halaju-masa bagi tempoh masa berkenaan","Nilai halaju akhir sahaja pada penghujung graf itu","Perbezaan antara halaju akhir dan halaju awal graf itu sahaja"],b:0,u:"Luas di bawah graf halaju-masa memberikan jarak yang ditempuh, tidak kira bentuk graf itu."},
 {j:"nombor",t:"Berdasarkan Rajah 1, berapakah jarak yang ditempuh oleh Objek A dalam 4 saat pertama, dalam meter?",b:16,tol:0.5,suf:"m",u:"Luas segi empat tepat = halaju × masa = 4 × 4 = 16 m."},
 {j:"pilih",t:"Berdasarkan Rajah 1, bandingkan jarak yang ditempuh oleh Objek A dan Objek B dalam 4 saat pertama.",p:["Kedua-duanya menempuh jarak yang sama, iaitu 16 m","Objek A menempuh jarak lebih jauh daripada Objek B","Objek B menempuh jarak lebih jauh daripada Objek A","Tidak dapat ditentukan tanpa mengetahui jisim kedua-dua objek"],b:0,u:"Luas segi empat tepat Objek A (4×4=16 m) bersamaan luas segi tiga Objek B (½×4×8=16 m), walaupun bentuk graf berbeza."},
 {j:"pilih",t:"Sekiranya graf halaju-masa suatu objek berbentuk lengkung yang kecerunannya sentiasa berubah, apakah jenis geraknya?",p:["Halaju tidak seragam, kerana pecutannya berubah-ubah","Halaju seragam, kerana ia masih bergerak ke hadapan","Pecutan seragam, kerana graf itu tetap melengkung","Objek itu pegun sepanjang keseluruhan tempoh yang digambarkan"],b:0,u:"Kecerunan graf halaju-masa mewakili pecutan; jika kecerunan berubah-ubah, pecutan tidak malar."},
 {j:"pilih",t:"Mengapakah unit yang betul mesti dinyatakan semasa mentafsir graf gerakan linear?",p:["Nilai tanpa unit tidak bermakna dan boleh disalahtafsir sepenuhnya","Unit hanya soal kekemasan dan tidak menjejaskan ketepatan jawapan","Graf gerakan linear tidak memerlukan unit kerana ia hanya bentuk","Unit hanya penting untuk pecutan sahaja, bukan untuk halaju atau jarak"],b:0,u:"Nombor tanpa unit seperti \"5\" boleh bermaksud 5 ms⁻¹ atau 5 m, dua kuantiti yang berbeza sama sekali."}],
 bos:{j:"nombor",t:"Berdasarkan Rajah 1, berapakah jumlah jarak yang ditempuh oleh Objek A dan Objek B bersama dalam 4 saat pertama, dalam meter?",b:32,tol:1,suf:"m",u:"16 m (Objek A) tambah 16 m (Objek B) bersamaan 32 m."}},

{n:4, tempat:"Menara Jatuh", sk:"11.3 Pecutan Graviti dan Jatuh Bebas", lampiran:"jatuh", kadNama:"Galileo Galilei", kadEm:"\u{1F52D}", kadFakta:"Galileo menggunakan satah condong untuk melambatkan pergerakan jatuh supaya ia dapat diukur dengan tepat menggunakan alat pada zamannya, sebelum jangka masa detik elektronik wujud.", bosKadNama:"Felix Baumgartner", bosKadEm:"\u{1FA82}", bosKadFakta:"Semasa terjun dari stratosfera pada 2012, Felix Baumgartner mencapai halaju melebihi laju bunyi sebelum rintangan udara yang semakin tebal memperlahankannya berhampiran Bumi.",
 soalan:[
 {j:"pilih",t:"Jatuh bebas ditakrifkan sebagai:",p:["Gerakan jasad yang hanya dipengaruhi oleh daya tarikan graviti","Gerakan jasad yang dipengaruhi oleh graviti dan geseran udara","Gerakan jasad pada halaju seragam tanpa sebarang daya bertindak","Gerakan jasad yang dilontar mendatar dari satu ketinggian"],b:0,u:"Jatuh bebas berlaku apabila graviti sahaja bertindak ke atas jasad, tanpa daya lain seperti geseran udara."},
 {j:"pilih",t:"Berdasarkan Rajah 1, garis manakah mewakili objek dalam keadaan jatuh bebas, dan mengapa?",p:["Garis lurus, kerana pecutannya malar sepanjang masa","Garis melengkung, kerana halajunya berubah tidak seragam","Garis lurus, kerana halajunya kekal malar sepanjang masa","Garis melengkung, kerana ia dipengaruhi rintangan udara sahaja"],b:0,u:"Jatuh bebas hanya dipengaruhi graviti, jadi pecutannya malar dan grafnya garis lurus menaik."},
 {j:"nombor",t:"Berdasarkan Rajah 1, berapakah pecutan graviti, g, bagi objek yang mengalami jatuh bebas, dalam ms⁻²?",b:10,tol:0.5,suf:"ms⁻²",u:"Kecerunan garis jatuh bebas = (30 − 0) / (3 − 0) = 10 ms⁻²."},
 {j:"pilih",t:"Berdasarkan Rajah 1, mengapakah graf objek bukan jatuh bebas melengkung dan mula mendatar?",p:["Rintangan udara bertambah dan mengurangkan pecutan objek itu","Graviti berkurang secara beransur apabila objek jatuh lebih rendah","Objek itu berhenti dipengaruhi oleh graviti selepas dua saat","Jisim objek itu berkurang sepanjang ia jatuh ke bawah"],b:0,u:"Rintangan udara meningkat apabila halaju bertambah, jadi ia semakin melawan graviti dan mengurangkan pecutan."},
 {j:"pilih",t:"Manakah antara berikut ialah contoh keadaan bukan jatuh bebas?",p:["Sehelai daun yang gugur perlahan-lahan berlegar ke tanah","Sebiji guli logam yang dijatuhkan dalam tabung vakum","Sebiji bola keluli yang dijatuhkan dari ketinggian dua meter","Dua objek berjisim berbeza dijatuhkan serentak dalam vakum"],b:0,u:"Daun yang gugur perlahan sangat dipengaruhi rintangan udara berbanding beratnya, jadi ia bukan jatuh bebas."},
 {j:"pilih",t:"Dalam eksperimen menentukan nilai g menggunakan jangka masa detik, mengapakah beberapa bacaan perlu diambil dan puratanya dikira?",p:["Mengurangkan kesan ralat rawak daripada satu bacaan sahaja","Membolehkan pelajar memilih bacaan yang paling sesuai dengan jangkaan","Memastikan nilai g yang diperoleh sentiasa melebihi nilai sebenar","Mengelakkan penggunaan unit ms⁻² dalam pengiraan akhir"],b:0,u:"Ulangan dan purata ialah amalan asas mengurangkan kesan ralat rawak dalam sebarang eksperimen."},
 {j:"pilih",t:"Dalam projek payung terjun bekalan banjir, mengapakah kanopi yang lebih besar menjadikan bekalan jatuh dengan lebih selamat?",p:["Kanopi lebih besar meningkatkan rintangan udara, jadi halaju mendarat berkurang","Kanopi lebih besar meningkatkan graviti yang bertindak ke atas bekalan","Kanopi lebih besar mengurangkan jisim bekalan yang dijatuhkan","Kanopi lebih besar memastikan bekalan sentiasa jatuh secara jatuh bebas"],b:0,u:"Kanopi besar menangkap lebih banyak udara, meningkatkan rintangan udara sehingga bekalan jatuh pada halaju lebih rendah."},
 {j:"pilih",t:"Berdasarkan eksperimen Galileo yang dibincangkan dalam bab ini, apakah dapatan pentingnya?",p:["Objek berlainan jisim jatuh pada pecutan yang sama tanpa rintangan udara","Objek yang lebih berat sentiasa jatuh lebih laju daripada objek ringan","Rintangan udara tidak memberi apa-apa kesan kepada objek yang jatuh","Pecutan graviti sentiasa berbeza mengikut jisim objek yang dijatuhkan"],b:0,u:"Galileo menunjukkan bahawa tanpa rintangan udara, semua objek jatuh dengan pecutan graviti yang sama tidak kira jisimnya."}],
 bos:{j:"banyak",t:"Pilih SEMUA ciri yang betul bagi keadaan jatuh bebas.",p:["Hanya daya graviti yang bertindak ke atas objek","Pecutan objek adalah malar sepanjang masa jatuh","Graf halaju-masa objek berbentuk garis lurus menaik","Rintangan udara mengimbangi berat objek","Halaju objek kekal malar sepanjang masa jatuh"],b:[0,1,2],u:"Dua pilihan terakhir menerangkan keadaan bukan jatuh bebas apabila objek menghampiri halaju maksimum."}},

{n:5, tempat:"Makmal Inersia", sk:"11.4 Jisim dan Inersia", kadNama:"Neraca Inersia NASA", kadEm:"\u{1F6F0}", kadFakta:"Neraca inersia dicipta oleh pihak NASA untuk menentukan jisim objek di stesen angkasa lepas, kerana neraca tolok biasa memerlukan graviti untuk berfungsi.", bosKadNama:"Tali Pinggang Keledar", bosKadEm:"\u{1FA79}", bosKadFakta:"Semasa kemalangan, tali pinggang keledar mengenakan daya ke atas badan penumpang untuk mengatasi inersianya supaya penumpang tidak terus bergerak ke hadapan mengikut halaju asal kereta.",
 soalan:[
 {j:"pilih",t:"Inersia ditakrifkan sebagai:",p:["Kecenderungan jasad untuk mengekalkan keadaan pegun atau bergeraknya","Daya yang menyebabkan jasad bergerak dari keadaan pegun sepenuhnya","Kadar perubahan halaju sesuatu jasad yang sedang bergerak laju","Jumlah tenaga yang tersimpan dalam jasad yang sedang bergerak"],b:0,u:"Inersia ialah sifat jasad yang menentang perubahan pada keadaan geraknya, sama ada pegun atau bergerak."},
 {j:"pilih",t:"Berdasarkan Hukum Newton Pertama yang diperkenalkan dalam bab ini, apakah hubungan antara jisim dan inersia?",p:["Semakin besar jisim jasad, semakin besar inersianya","Semakin besar jisim jasad, semakin kecil inersianya","Jisim dan inersia tidak mempunyai hubungan langsung","Inersia hanya bergantung pada halaju jasad, bukan jisimnya"],b:0,u:"Jisim ialah ukuran inersia; jasad berjisim besar lebih sukar diubah keadaan geraknya."},
 {j:"pilih",t:"Mengapakah troli kosong lebih mudah ditolak untuk mula bergerak berbanding troli yang penuh dimuatkan barang?",p:["Troli penuh mempunyai jisim dan inersia yang lebih besar","Troli kosong mempunyai geseran roda yang lebih tinggi","Troli penuh bergerak lebih laju sebaik sahaja ditolak","Troli kosong memerlukan daya graviti yang jauh lebih besar"],b:0,u:"Jisim yang lebih besar bermakna inersia yang lebih besar, jadi lebih banyak daya diperlukan untuk mengubah keadaan geraknya."},
 {j:"pilih",t:"Mengapakah penumpang kereta tersentak ke hadapan apabila kereta membrek secara mengejut?",p:["Badan penumpang mengekalkan inersia untuk terus bergerak ke hadapan","Badan penumpang ditolak ke hadapan oleh tali pinggang keledar itu","Kereta itu sebenarnya masih memecut laju ke hadapan semasa membrek","Graviti bertambah secara mendadak semasa kereta itu membrek"],b:0,u:"Inersia badan penumpang cuba mengekalkan halaju asal walaupun kereta sudah perlahan, jadi badan tersentak ke hadapan."},
 {j:"pilih",t:"Apakah fungsi penyandar kepala (headrest) dalam kereta semasa kemalangan dilanggar dari belakang?",p:["Menahan inersia kepala supaya tidak tersentak ke belakang secara mendadak","Mengurangkan jisim kepala penumpang semasa perlanggaran berlaku","Menambah halaju kepala penumpang ke arah hadapan kereta","Menghalang badan kereta daripada mengalami sebarang kerosakan"],b:0,u:"Semasa dilanggar dari belakang, badan tersentak ke hadapan tetapi kepala tertinggal akibat inersia; penyandar kepala menahan pergerakan itu."},
 {j:"pilih",t:"Dalam eksperimen mengkaji hubungan jisim dan inersia menggunakan neraca inersia, pembolehubah manakah yang WAJIB dimalarkan?",p:["Daya awal yang dikenakan untuk menggerakkan neraca itu","Jisim objek yang diletakkan pada neraca inersia","Tempoh masa neraca itu berayun sepenuhnya","Bilangan kali neraca itu diayunkan sepanjang eksperimen"],b:0,u:"Daya awal ialah pembolehubah dimalarkan supaya perbandingan antara jisim berbeza adalah adil."},
 {j:"pilih",t:"Nilaikan kenyataan: \"Barang muatan lori mesti diikat kukuh supaya tidak tergelincir semasa lori membrek mengejut.\"",p:["Benar, kerana inersia barang cuba mengekalkan geraknya ke hadapan","Tidak benar, kerana barang statik tidak mempunyai inersia","Benar, tetapi hanya berlaku pada barang yang sangat ringan","Tidak benar, kerana geseran roda dengan jalan sahaja sudah cukup menahan barang itu"],b:0,u:"Barang yang bergerak bersama lori mempunyai inersia yang cuba mengekalkan halaju asalnya walaupun lori itu berhenti mengejut."},
 {j:"pilih",t:"Manakah antara berikut ialah kesan inersia yang memudaratkan, bukan bermanfaat?",p:["Penumpang tercedera akibat tersentak ke hadapan semasa perlanggaran","Palu kekal bergerak untuk memacu paku masuk ke dalam kayu","Kain hamparan tertarik keluar meninggalkan pinggan di atas meja","Roda gasing terus berpusing lama selepas dipusingkan oleh tangan"],b:0,u:"Kecederaan akibat tersentak semasa perlanggaran ialah kesan memudaratkan; tiga pilihan lain ialah kegunaan inersia yang bermanfaat."}],
 bos:{j:"pilih",t:"Sebuah syarikat pengangkutan mahu mengurangkan risiko kecederaan pemandu semasa kemalangan. Cadangan manakah paling berasaskan sains inersia?",p:["Pasang tali pinggang keledar dan penyandar kepala pada setiap kenderaan","Kurangkan jisim kenderaan supaya ia lebih ringan semasa bergerak","Naikkan had laju supaya perjalanan lebih pantas dan singkat","Buang penyandar kepala supaya pandangan pemandu lebih luas"],b:0,u:"Tali pinggang keledar dan penyandar kepala direka khusus untuk mengatasi kesan inersia badan semasa perlanggaran mengejut."}},

{n:6, tempat:"Bengkel Reka Bentuk", sk:"11.3 / 11.4 Mereka cipta", lampiran:"reka", kadNama:"Payung Terjun Bantuan Bencana", kadEm:"\u{1FA82}", kadFakta:"Semasa banjir besar, pasukan bantuan sering menjatuhkan bekalan makanan dan ubat dari udara menggunakan payung terjun supaya bekalan itu tidak rosak akibat halaju tinggi semasa mencecah tanah.", bosKadNama:"Reka Bentuk Berulang", bosKadEm:"\u{1F501}", bosKadFakta:"Jurutera sejati jarang berjaya pada prototaip pertama; kitaran uji-nilai-ubah suai berulang kali ialah cara reka bentuk sebenar berfungsi.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 1, mengapakah langkah \"Kaji pembolehubah\" perlu dilakukan sebelum membina prototaip?",p:["Supaya reka bentuk berasaskan bukti, bukan agakan","Supaya prototaip dapat dibina dengan lebih cepat tanpa sebarang ujian","Supaya kos bahan dapat dikurangkan tanpa mengira keberkesanannya","Supaya langkah menguji dan menilai dapat dilangkau sepenuhnya"],b:0,u:"Mengkaji pembolehubah dahulu membolehkan reka bentuk dibuat berdasarkan sains, bukan tekaan."},
 {j:"pilih",t:"Jika kanopi payung terjun dibuat terlalu kecil, apakah kesan yang paling mungkin berlaku kepada bekalan?",p:["Rintangan udara tidak mencukupi, bekalan jatuh terlalu laju dan rosak","Rintangan udara berlebihan, bekalan melayang terlalu jauh dari sasaran","Bekalan akan mengalami jatuh bebas sepenuhnya tanpa graviti","Bekalan akan berhenti bergerak sebaik sahaja payung dibuka"],b:0,u:"Kanopi kecil memberi kawasan permukaan yang kurang, jadi rintangan udara tidak cukup untuk memperlahankan bekalan dengan selamat."},
 {j:"pilih",t:"Jika kanopi payung terjun dibuat terlalu besar, apakah kelemahan yang mungkin timbul walaupun bekalan mendarat perlahan?",p:["Bekalan mungkin melayang jauh akibat angin dan terlepas dari sasaran","Bekalan akan jatuh terlalu laju dan pecah semasa mendarat","Jisim bekalan akan bertambah secara automatik akibat kanopi besar","Payung terjun tidak akan terbuka langsung akibat saiznya"],b:0,u:"Kanopi besar meningkatkan masa bekalan berada di udara, memberi lebih peluang untuk angin menghanyutkannya jauh dari sasaran."},
 {j:"pilih",t:"Bahan kanopi manakah paling sesuai untuk payung terjun bekalan banjir, dan mengapa?",p:["Kain ringan tetapi tahan koyak, supaya ia kekal berfungsi dan mudah dibawa","Plastik keras dan berat, supaya ia tidak mudah tertiup angin","Kertas nipis biasa, supaya kosnya paling rendah berbanding bahan lain","Logam nipis, supaya kanopi kekal berbentuk tetap sepanjang masa"],b:0,u:"Kain ringan tetapi tahan koyak memberi rintangan udara yang baik tanpa menambah jisim keseluruhan secara ketara."},
 {j:"pilih",t:"Mengapakah bilangan dan panjang tali payung terjun turut menjadi pembolehubah penting dalam reka bentuk ini?",p:["Ia menentukan kestabilan dan sudut bekalan semasa turun ke bawah","Ia satu-satunya faktor yang menentukan halaju mendarat bagi bekalan","Ia tidak memberi apa-apa kesan berbanding saiz kanopi sahaja","Ia menentukan jisim keseluruhan payung terjun itu sepenuhnya"],b:0,u:"Susunan dan panjang tali mempengaruhi kestabilan payung semasa turun, bukan sekadar menyokong beratnya."},
 {j:"pilih",t:"Selepas menguji prototaip pertama dan mendapati bekalan masih terhempas kuat, tindakan paling wajar ialah:",p:["Kembali ke langkah kaji pembolehubah dan besarkan saiz kanopi","Terus menjatuhkan bekalan sebenar itu tanpa sebarang ubah suai","Buang kesemua data ujian dan mula reka bentuk semula secara rawak","Kurangkan panjang tali supaya bekalan mendarat dengan lebih pantas"],b:0,u:"Reka bentuk yang baik ialah proses berulang: menilai kelemahan dan kembali memperbaik pembolehubah yang berkaitan."},
 {j:"pilih",t:"Bagaimanakah konsep jatuh bebas dan bukan jatuh bebas berkait dengan reka bentuk payung terjun ini?",p:["Payung terjun sengaja mewujudkan rintangan udara supaya bekalan tidak dalam keadaan jatuh bebas","Payung terjun direka supaya bekalan sentiasa dalam keadaan jatuh bebas sepenuhnya","Konsep ini tidak berkaitan langsung dengan reka bentuk payung terjun","Payung terjun menghapuskan sepenuhnya kesan graviti ke atas bekalan"],b:0,u:"Tujuan payung terjun ialah mewujudkan rintangan udara yang cukup besar supaya bekalan bergerak seperti objek bukan jatuh bebas, iaitu lebih perlahan dan selamat."},
 {j:"pilih",t:"Pasukan lain mencadangkan menambah beg udara (airbag) di bawah bekalan selain payung terjun. Nilaikan cadangan ini.",p:["Berpotensi membantu, kerana ia melanjutkan masa perlanggaran dan mengurangkan kesan hentaman","Tidak berguna sama sekali, kerana hanya payung terjun yang mengurangkan halaju","Berbahaya, kerana ia akan menambah halaju bekalan semasa mendarat","Tidak perlu dipertimbangkan kerana kos sahaja penentu utama reka bentuk"],b:0,u:"Beg udara melanjutkan tempoh perlanggaran, mengurangkan kesan hentaman tambahan selepas payung terjun memperlahankan bekalan."}],
 bos:{j:"buka",
  t:"Pasukan bantuan bencana ingin menjatuhkan bekalan ubat dari udara semasa banjir menggunakan payung terjun ringkas supaya ubat itu tidak rosak semasa mendarat.",
  arahan:"Cadangkan saiz kanopi, bahan kanopi, serta panjang dan bilangan tali yang sesuai. Jelaskan justifikasi setiap pilihan berdasarkan konsep jatuh bebas, rintangan udara dan inersia yang dipelajari dalam bab ini.",
  u:"Jawapan TP6 yang kukuh mengaitkan setiap pilihan reka bentuk (saiz kanopi, bahan, tali) secara jelas dengan konsep sains rintangan udara dan keselamatan pendaratan, bukan sekadar menyenaraikan pilihan."}}
];

module.exports = {
  id:"t4b9", tingkatan:4, kod:"11.0 Daya dan Gerakan",
  tajuk:"Laluan Pecutan",
  subtajuk:"Sains Ting. 4 · Bab 11 Daya dan Gerakan",
  spi:SPI,
  ulasan:{
   1:"{n} dapat mengingat kembali definisi jarak, sesaran, laju, halaju dan pecutan berserta unit SI masing-masing. Langkah seterusnya ialah membezakan kuantiti skalar dan vektor dalam situasi sebenar.",
   2:"{n} memahami perbezaan antara laju dengan halaju, dan laju purata dengan halaju purata, termasuk makna pecutan positif dan negatif. Galakkan lebih banyak contoh situasi harian.",
   3:"{n} boleh mentafsir graf gerakan linear untuk menentukan jenis gerakan serta mengira jarak dan pecutan daripada graf. Seterusnya latih menyelesaikan masalah berangka yang lebih mencabar.",
   4:"{n} mampu menganalisis graf dan data untuk membezakan keadaan jatuh bebas dengan bukan jatuh bebas, serta mengaitkannya dengan rintangan udara. Galakkan penjelasan sebab, bukan sekadar label.",
   5:"{n} dapat menilai hubungan antara jisim dan inersia serta menilai keberkesanan ciri keselamatan kenderaan berdasarkan konsep inersia, disokong alasan yang munasabah. Sudah bersedia untuk tugasan reka cipta.",
   6:"{n} berjaya mereka bentuk penyelesaian payung terjun yang mengaitkan saiz kanopi, bahan dan tali dengan konsep rintangan udara dan inersia secara koheren. Pencapaian cemerlang bagi bab ini.",
   tiada:"{n} belum menunjukkan bukti penguasaan yang mencukupi bagi bab Daya dan Gerakan. Cadangan: ulang aktiviti hentian pertama dengan bimbingan rakan sebaya."
  },
  lampiran:{ gerak:R_GERAK, jatuh:R_JATUH, reka:R_REKA },
  aras:ARAS
};
