/* Sumber kandungan — Sains KSSM Tingkatan 5, Bidang 3.0 Kelestarian Alam Sekitar.
   Fail ini disunting tangan. Jalankan `node bina.js t5b3` untuk menyemaknya
   dan menghasilkan bank-t5b3.js dengan kedudukan jawapan yang seimbang.

   Standard Prestasi disalin kata demi kata daripada DSKP KSSM Sains
   Tingkatan 5, Bahagian Pembangunan Kurikulum, muka 129.

   Tulis jawapan betul pada indeks 0. Pembina akan mengagihkannya. */

const SPI = [
"Mengingat kembali pengetahuan dan kemahiran saintifik mengenai kelestarian alam.",
"Memahami kelestarian alam dan dapat menjelaskan kefahaman tersebut.",
"Mengaplikasikan pengetahuan mengenai kelestarian alam dan dapat melaksanakan tugasan mudah.",
"Menganalisis pengetahuan mengenai kelestarian alam dalam konteks penyelesaian masalah mengenai kejadian atau fenomena alam.",
"Menilai pengetahuan mengenai kelestarian alam dalam konteks penyelesaian masalah dan membuat keputusan untuk melaksanakan satu tugasan.",
"Mereka cipta dengan menggunakan pengetahuan dan kemahiran sains mengenai kelestarian alam dalam konteks penyelesaian masalah dan membuat keputusan atau dalam melaksanakan satu tugasan dalam situasi baharu secara kreatif dan inovatif dengan mengambil kira nilai sosial/ekonomi/budaya masyarakat."];

/* ---------- lampiran ---------- */

const R_KITAR_PRODUK = {
  jenis:"aliran", mod:"kitar",
  nod:[
    { label:"Bahan Mentah", isi:"hijauLembut" },
    { label:"Pembuatan", isi:"kuningLembut" },
    { label:"Penggunaan", isi:"lembayungLembut" },
    { label:"Pelupusan", isi:"merahLembut" },
  ],
  kapsyen:"Rajah 1 · Kitar hayat umum sesuatu produk daripada bahan mentah hingga pelupusan.",
  alt:"Rajah kitaran empat peringkat: bahan mentah, pembuatan, penggunaan dan pelupusan, disambung dalam bulatan"
};

const R_GRAF_BOD = {
  jenis:"graf", mod:"mendatar",
  bar:[
    { label:"Hulu sungai", nilai:2, warna:"hijau" },
    { label:"Kolam rawatan", nilai:9, warna:"kuning" },
    { label:"Longkang rumah", nilai:19, warna:"kuning" },
    { label:"Discaj kilang", nilai:34, warna:"merah" },
  ],
  xLabel:"BOD (mg/L)",
  kapsyen:"Rajah 1 · Bacaan BOD empat sumber air dalam satu kajian makmal.",
  alt:"Graf palang mendatar bacaan BOD bagi empat sumber air: hulu sungai 2, kolam rawatan 9, longkang rumah 19, discaj kilang 34 miligram seliter"
};

/* ---------- hentian ---------- */

const ARAS = [

{n:1, tempat:"Jejak", sk:"3.1 Kitaran hayat produk",
 kadNama:"Jejak Karbon", kadEm:"\u{1F463}", kadFakta:"Purata jejak karbon seorang rakyat Malaysia dianggarkan lebih 7 tan karbon dioksida setahun, hasil daripada tenaga elektrik, pengangkutan dan makanan.",
 bosKadNama:"Tapak Tangan Karbon", bosKadEm:"\u{1F590}", bosKadFakta:"Tapak tangan karbon mengukur tindakan positif seseorang untuk mengurangkan gas rumah hijau, bukan sekadar jumlah yang dihasilkannya.",
 soalan:[
 {j:"pilih",t:"Jejak karbon (carbon footprint) bagi seseorang individu merujuk kepada:",p:["Jumlah gas rumah hijau yang dibebaskan akibat aktiviti hariannya","Jumlah sampah yang dihasilkannya dalam sehari sahaja","Luas kawasan tanah yang dimilikinya di kampung","Jumlah wang yang dibelanjakan untuk tenaga elektrik setiap bulan"],b:0,u:"Jejak karbon mengukur kesan aktiviti harian terhadap pembebasan gas rumah hijau, bukan kos atau sampah."},
 {j:"pilih",t:"Antara berikut, yang manakah PALING menyumbang kepada jejak karbon harian seorang murid bandar?",p:["Kenderaan berenjin petrol ke sekolah","Membaca buku pada waktu petang di rumah","Bermain congkak bersama rakan di sekolah","Minum air kosong semasa waktu rehat sekolah"],b:0,u:"Pembakaran petrol membebaskan karbon dioksida secara langsung, berbeza daripada aktiviti lain yang tiada pembakaran bahan api."},
 {j:"pilih",t:"Apakah yang dimaksudkan dengan gas rumah hijau?",p:["Gas yang memerangkap haba dalam atmosfera Bumi","Gas yang digunakan untuk menanam sayur dalam rumah hijau","Gas beracun yang hanya dihasilkan oleh kilang","Gas yang menyejukkan atmosfera Bumi"],b:0,u:"Gas seperti karbon dioksida dan metana memerangkap haba matahari, menyebabkan kesan rumah hijau."},
 {j:"susun",t:"Susun aktiviti berikut daripada PALING RENDAH kepada PALING TINGGI sumbangan jejak karbon.",p:["Berjalan kaki ke kedai","Menaiki basikal ke sekolah","Menaiki motosikal ke bandar","Menaiki kereta persendirian seorang diri ke bandar"],b:[0,1,2,3],u:"Semakin banyak bahan api fosil dibakar bagi setiap perjalanan, semakin tinggi jejak karbon yang dihasilkan."},
 {j:"pilih",t:"Mengapakah tapak tangan karbon penting selain jejak karbon?",p:["Ia mengukur tindakan positif yang kurangkan gas rumah hijau","Ia mengukur bilangan pokok yang ditanam sahaja setiap tahun","Ia menggantikan keperluan mengira jejak karbon sepenuhnya","Ia hanya digunakan oleh kilang besar sahaja di negara ini"],b:0,u:"Tapak tangan karbon menggalakkan tindakan mengurangkan kesan negatif, bukan sekadar merekod kesan negatif."},
 {j:"pilih",t:"Antara berikut, produk manakah biasanya mempunyai jejak karbon PALING RENDAH?",p:["Sayur-sayuran tempatan yang dijual di pasar pekan","Buah-buahan import yang dihantar menggunakan kapal terbang","Daging yang diproses dan dibungkus dalam plastik berlapis","Makanan segera yang dihantar menggunakan penghantaran ekspres"],b:0,u:"Produk tempatan tidak memerlukan pengangkutan jauh, jadi pembebasan karbon akibat penghantaran lebih rendah."},
 {j:"pilih",t:"Elektrik yang dijana daripada arang batu menyumbang kepada jejak karbon kerana:",p:["Pembakaran arang batu membebaskan karbon dioksida","Arang batu perlu digali daripada dalam tanah terlebih dahulu","Arang batu mahal untuk dibeli dan diangkut jauh","Penjanaan elektrik memerlukan air yang banyak setiap hari"],b:0,u:"Punca utama jejak karbon dalam penjanaan elektrik arang batu ialah pembakaran bahan api fosil itu sendiri."},
 {j:"pilih",t:"Seorang murid menukar penghawa dingin bilik kepada kipas biasa pada waktu malam. Kesannya terhadap jejak karbon murid itu ialah:",p:["Jejak karbon berkurang kerana penggunaan tenaga elektrik menurun","Jejak karbon bertambah kerana kipas menggunakan lebih tenaga elektrik","Jejak karbon tidak berubah langsung walau apa pun dilakukan","Jejak karbon hanya berkurang jika dilakukan sepanjang tahun penuh"],b:0,u:"Kipas menggunakan tenaga elektrik yang jauh lebih rendah berbanding penghawa dingin."}],
 bos:{j:"banyak",t:"Pilih SEMUA aktiviti yang akan MENGURANGKAN jejak karbon harian seseorang.",p:["Menggunakan pengangkutan awam berbanding kereta persendirian","Menutup suis lampu apabila keluar bilik","Membeli produk tempatan berbanding produk import","Membakar sampah secara terbuka di halaman rumah setiap minggu","Menggunakan plastik sekali guna setiap hari tanpa henti"],b:[0,1,2],u:"Membakar sampah dan plastik sekali guna sebenarnya MENAMBAH pembebasan gas rumah hijau, bukan menguranginya."}},

{n:2, tempat:"Kilang", sk:"3.1 Kitaran hayat produk", lampiran:"kitarProduk",
 kadNama:"Kitar Semula", kadEm:"\u{267B}", kadFakta:"Kitar semula satu tin aluminium menjimatkan tenaga yang cukup untuk menyalakan televisyen selama tiga jam.",
 bosKadNama:"Upcycle", bosKadEm:"\u{1F381}", bosKadFakta:"Upcycle mengubah sisa menjadi produk bernilai lebih tinggi, berbeza daripada kitar semula biasa yang memecah produk kepada bahan mentah semula.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 1, peringkat manakah berlaku SEBELUM sesuatu produk sampai ke tangan pengguna?",p:["Bahan Mentah dan Pembuatan","Penggunaan dan Pelupusan sahaja","Pelupusan sahaja","Bahan Mentah sahaja"],b:0,u:"Rajah 1 menunjukkan bahan mentah diproses menjadi produk semasa peringkat Pembuatan, sebelum sampai ke peringkat Penggunaan."},
 {j:"pilih",t:"Kitar hayat produk 'cradle to cradle' bermaksud:",p:["Produk dilupuskan dan dikitar semula menjadi bahan mentah baharu","Produk dibiarkan mereput di tapak pelupusan selepas ia digunakan","Produk hanya digunakan sekali sahaja sebelum ia dibuang","Produk dijual terus tanpa melalui peringkat pembuatan sepenuhnya"],b:0,u:"'Cradle to cradle' bermaksud kitaran itu bersambung semula, bukan berakhir di tapak pelupusan."},
 {j:"pilih",t:"Kitar hayat 'cradle to grave' berbeza daripada 'cradle to cradle' kerana:",p:["Produk mereput atau terkumpul di tapak pelupusan tanpa dikitar","Produk tidak pernah melalui peringkat pembuatan sama sekali","Produk digunakan berulang kali tanpa had oleh pengguna","Produk tidak memerlukan bahan mentah langsung untuk dihasilkan"],b:0,u:"'Cradle to grave' bermaksud kitaran itu berakhir sepenuhnya di tapak pelupusan."},
 {j:"pilih",t:"Istilah 'upcycle' merujuk kepada:",p:["Mengubah sisa menjadi produk baharu bernilai lebih tinggi","Membuang sisa ke tapak pelupusan sanitari yang berdekatan","Membakar sisa untuk menghasilkan elektrik sahaja setiap hari","Mengurangkan bilangan produk yang dibeli oleh pengguna"],b:0,u:"Upcycle menambah nilai sisa, berbeza daripada kitar semula biasa yang memecahnya kepada bahan mentah."},
 {j:"banyak",t:"Pilih SEMUA soalan yang wajar ditanya semasa menilai sama ada sesuatu produk mesra alam.",p:["Berapakah sisa yang dihasilkan selepas produk itu digunakan?","Apakah kesan negatif proses pembuatan produk itu?","Berapakah harga jualan produk itu di pasaran?","Adakah produk itu selamat digunakan?","Apakah warna kemasan produk itu?"],b:[0,1,3],u:"Harga dan warna kemasan tidak berkaitan secara langsung dengan kesan produk terhadap alam sekitar."},
 {j:"pilih",t:"Mengapakah kajian kitar hayat produk perlu mempertimbangkan KESELURUHAN peringkat, bukan hanya peringkat penggunaan?",p:["Kesan negatif alam sekitar boleh berlaku pada mana-mana peringkat","Peringkat penggunaan sentiasa yang paling merosakkan alam sekitar sepenuhnya","Peringkat pembuatan tidak pernah menjejaskan alam sekitar langsung","Hanya peringkat pelupusan yang relevan untuk kelestarian jangka panjang"],b:0,u:"Sesuatu produk mungkin selamat semasa digunakan tetapi proses pembuatannya membebaskan bahan pencemar."},
 {j:"pilih",t:"Sisa plastik sukar terurai secara semula jadi terutamanya kerana:",p:["Struktur kimianya tahan kepada proses pereputan semula jadi","Ia terlalu ringan untuk diproses oleh mikroorganisma dalam tanah","Ia hanya dihasilkan dalam kuantiti yang kecil setiap tahun","Ia sentiasa dikitar semula sebaik sahaja dibuang oleh pengguna"],b:0,u:"Struktur kimia kebanyakan plastik menjadikannya tahan lama, itulah sebabnya ia mengambil masa lama untuk terurai."},
 {j:"pilih",t:"Mikroplastik dalam rantaian makanan terhasil apabila:",p:["Plastik terurai kepada zarah kecil dan termakan oleh hidupan akuatik","Plastik dikitar semula sepenuhnya menjadi produk baharu yang berguna","Plastik dibakar sepenuhnya tanpa meninggalkan sebarang sisa","Plastik digunakan sekali sahaja oleh pengguna sebelum dibuang"],b:0,u:"Zarah mikroplastik yang termakan oleh hidupan akuatik boleh berpindah sepanjang rantaian makanan."}],
 bos:{j:"pilih",t:"Berdasarkan Rajah 1, sebuah kilang mereka bentuk produk supaya bahan pada peringkat Pelupusan boleh terus digunakan semula sebagai Bahan Mentah bagi kitaran seterusnya. Strategi ini paling tepat digambarkan sebagai:",p:["Kitar hayat 'cradle to cradle' yang berterusan","Kitar hayat 'cradle to grave' yang lazim","Pengurangan penggunaan produk secara mendadak","Pertambahan kos pengeluaran secara berterusan"],b:0,u:"Menyambung semula Pelupusan kepada Bahan Mentah ialah ciri utama kitaran 'cradle to cradle'."}},

{n:3, tempat:"Udara", sk:"3.2 Pencemaran alam sekitar",
 kadNama:"Hujan Asid", kadEm:"\u{1F327}", kadFakta:"Hujan asid terbentuk apabila sulfur dioksida dan nitrogen oksida daripada asap kilang dan kenderaan bertindak balas dengan wap air di atmosfera.",
 bosKadNama:"Eutrofikasi", bosKadEm:"\u{1F33F}", bosKadFakta:"Eutrofikasi berlaku apabila baja berlebihan daripada ladang mengalir ke sungai, menyebabkan pertumbuhan alga yang mengurangkan oksigen dalam air.",
 soalan:[
 {j:"pilih",t:"Asap kilang yang mengandungi sulfur dioksida bertindak balas dengan wap air di atmosfera dan jatuh sebagai hujan berasid. Fenomena ini dipanggil:",p:["Hujan asid","Kesan rumah hijau","Eutrofikasi","Pencemaran terma"],b:0,u:"Sulfur dioksida dan nitrogen oksida yang larut dalam wap air menghasilkan hujan berasid."},
 {j:"pilih",t:"Sebuah kilang kuasa melepaskan air yang telah digunakan untuk menyejukkan jentera terus ke sungai berhampiran pada suhu yang lebih tinggi daripada suhu asal sungai itu. Ini ialah contoh:",p:["Pencemaran terma","Pencemaran tanah","Hujan asid","Eutrofikasi"],b:0,u:"Peningkatan suhu air akibat pelepasan air sisa panas dipanggil pencemaran terma, dan ia menurunkan kandungan oksigen terlarut dalam air."},
 {j:"pilih",t:"Baja berlebihan daripada sebuah ladang sayur mengalir ke dalam kolam berhampiran, menyebabkan pertumbuhan alga yang sangat lebat sehingga menutupi permukaan air. Fenomena ini dipanggil:",p:["Eutrofikasi","Pencemaran terma","Hujan asid","Kesan rumah hijau"],b:0,u:"Nutrien berlebihan daripada baja mendorong pertumbuhan alga secara mendadak, iaitu eutrofikasi."},
 {j:"banyak",t:"Pilih SEMUA punca yang boleh menyebabkan pencemaran tanah.",p:["Pembuangan bahan kimia industri secara haram","Penggunaan racun perosak berlebihan di ladang","Pembuangan sisa pepejal secara terbuka","Penanaman pokok renek di taman","Penggunaan tenaga solar untuk lampu jalan"],b:[0,1,2],u:"Penanaman pokok dan penggunaan tenaga solar tidak mencemarkan tanah, malah membantu alam sekitar."},
 {j:"pilih",t:"Peningkatan kepekatan gas rumah hijau di atmosfera dikaitkan dengan pemanasan global kerana:",p:["Gas ini memerangkap lebih banyak haba matahari dalam atmosfera Bumi","Gas ini menghalang sepenuhnya cahaya matahari daripada sampai ke Bumi","Gas ini menyejukkan lapisan atmosfera atas","Gas ini hanya menjejaskan kawasan berhampiran khatulistiwa"],b:0,u:"Lebih banyak gas rumah hijau bermakna lebih banyak haba terperangkap, menyebabkan suhu purata Bumi meningkat."},
 {j:"pilih",t:"Perubahan iklim jangka panjang seperti peningkatan kekerapan banjir kilat di Malaysia paling berkait rapat dengan:",p:["Peningkatan suhu global akibat gas rumah hijau","Peningkatan bilangan kilang tekstil di kawasan pedalaman","Pengurangan penggunaan baja kimia oleh petani tempatan","Peningkatan bilangan kenderaan elektrik di bandar besar"],b:0,u:"Suhu global yang meningkat mengubah corak cuaca, termasuk menambah kekerapan hujan lebat dan banjir kilat."},
 {j:"pilih",t:"Manakah antara berikut PALING TEPAT membezakan pencemaran air dan eutrofikasi?",p:["Eutrofikasi ialah pencemaran air oleh nutrien berlebihan","Eutrofikasi tiada kaitan langsung dengan pencemaran air sama sekali","Pencemaran air hanya disebabkan oleh eutrofikasi sahaja tanpa punca lain","Eutrofikasi hanya berlaku di laut, bukan di sungai ataupun kolam"],b:0,u:"Eutrofikasi ialah satu bentuk khusus pencemaran air yang berpunca daripada nutrien berlebihan seperti nitrat dan fosfat."},
 {j:"susun",t:"Susun urutan kejadian eutrofikasi mengikut turutan yang betul.",p:["Baja berlebihan mengalir masuk ke dalam air","Alga membiak dengan cepat menutupi permukaan air","Cahaya matahari terhalang daripada mencapai tumbuhan air di bawah","Oksigen terlarut dalam air berkurang apabila alga mati dan mereput"],b:[0,1,2,3],u:"Nutrien berlebihan mencetuskan ledakan pertumbuhan alga, yang akhirnya menyebabkan kekurangan oksigen apabila alga itu mati dan direput oleh bakteria."}],
 bos:{j:"pilih",t:"Sebatang sungai berhampiran kawasan perindustrian didapati mempunyai suhu air yang lebih tinggi daripada bahagian hulu, tetapi tiada perubahan warna atau bau yang ketara. Punca yang paling mungkin ialah:",p:["Pelepasan air penyejuk panas daripada kilang berhampiran","Baja daripada ladang pertanian yang berhampiran","Hujan asid daripada asap kenderaan berat","Pembuangan sisa pepejal ke dalam sungai berdekatan"],b:0,u:"Peningkatan suhu tanpa perubahan warna atau bau paling konsisten dengan pencemaran terma daripada air penyejuk kilang."}},

{n:4, tempat:"Sungai", sk:"3.2 Pencemaran alam sekitar", lampiran:"grafBod",
 kadNama:"BOD", kadEm:"\u{1F9EA}", kadFakta:"BOD (Biochemical Oxygen Demand) mengukur jumlah oksigen yang digunakan oleh mikroorganisma untuk menguraikan bahan organik dalam air; semakin tinggi BOD, semakin tercemar air itu.",
 bosKadNama:"Metilena Biru", bosKadEm:"\u{1F535}", bosKadFakta:"Larutan metilena biru luntur lebih cepat dalam air yang tercemar kerana mikroorganisma menggunakan oksigen dengan lebih pantas untuk menguraikan bahan organik.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 1, sumber air manakah paling TERCEMAR?",p:["Discaj kilang","Hulu sungai","Kolam rawatan","Longkang rumah"],b:0,u:"Discaj kilang mencatatkan bacaan BOD paling tinggi, 34 mg/L, menunjukkan ia paling tercemar."},
 {j:"pilih",t:"Berdasarkan Rajah 1, mengapakah bacaan BOD di hulu sungai jauh lebih rendah berbanding discaj kilang?",p:["Hulu sungai mengandungi lebih sedikit bahan organik untuk diuraikan","Hulu sungai mempunyai lebih banyak ikan berbanding discaj kilang itu","Air di hulu sungai itu lebih sejuk sepanjang masa","Discaj kilang itu tidak mengandungi sebarang mikroorganisma langsung"],b:0,u:"BOD rendah bermakna sedikit sahaja oksigen digunakan untuk menguraikan bahan organik, kerana bahan organik itu sendiri sedikit."},
 {j:"nombor",t:"Berdasarkan Rajah 1, berapakah beza bacaan BOD, dalam mg/L, antara discaj kilang dan hulu sungai?",b:32,tol:0.5,suf:"mg/L",u:"34 tolak 2 bersamaan 32 mg/L."},
 {j:"pilih",t:"Mengapakah larutan metilena biru digunakan untuk menganggarkan tahap pencemaran air?",p:["Ia luntur cepat bila mikroorganisma guna oksigen pantas","Ia menukar warna mengikut suhu air semata-mata sahaja","Ia membunuh semua mikroorganisma dalam sampel air tersebut","Ia hanya bertindak balas dengan plastik dalam air itu"],b:0,u:"Kadar peluntur metilena biru berkait rapat dengan kadar penggunaan oksigen oleh mikroorganisma, jadi ia menganggarkan tahap pencemaran organik."},
 {j:"banyak",t:"Berdasarkan Rajah 1, pilih SEMUA kenyataan yang disokong oleh data.",p:["Longkang rumah lebih tercemar berbanding kolam rawatan","Discaj kilang mencatatkan BOD lebih daripada tiga kali ganda hulu sungai","Kolam rawatan mencatatkan bacaan BOD paling rendah antara keempat-empat sumber","Semua sumber air mencatatkan BOD melebihi 30 mg/L"],b:[0,1],u:"Kolam rawatan (9 mg/L) bukan paling rendah — hulu sungai (2 mg/L) paling rendah. Hanya discaj kilang melebihi 30 mg/L."},
 {j:"pilih",t:"BOD yang tinggi dalam sesuatu badan air biasanya membawa kepada:",p:["Kekurangan oksigen yang menjejaskan hidupan akuatik","Peningkatan bilangan ikan secara mendadak di sungai itu","Peningkatan kejernihan air sungai secara mendadak","Penurunan suhu air secara mendadak di kawasan itu"],b:0,u:"BOD tinggi bermakna banyak oksigen digunakan oleh mikroorganisma, meninggalkan sedikit oksigen untuk hidupan akuatik lain."},
 {j:"pilih",t:"Sebuah kilang mencadangkan merawat air sisa sebelum dilepaskan ke sungai untuk mengurangkan BOD. Kaedah yang PALING wajar ialah:",p:["Mengurangkan kandungan bahan organik dalam air sisa","Menambah baja ke dalam air sisa sebelum ia dilepaskan","Memanaskan air sisa itu sebelum ia dilepaskan","Menambah pewarna ke dalam air sisa sebelum ia dilepaskan"],b:0,u:"Mengurangkan bahan organik secara langsung menurunkan jumlah oksigen yang akan digunakan oleh mikroorganisma, iaitu menurunkan BOD."},
 {j:"pilih",t:"Sebuah sampel air didapati mempunyai BOD yang meningkat drastik selepas hujan lebat berbanding hari-hari biasa. Penjelasan paling munasabah ialah:",p:["Air larian membawa masuk lebih banyak bahan organik ke dalam sungai","Ia menambah kandungan oksigen dalam air secara mendadak","Ia menurunkan suhu air, jadi BOD meningkat","Ia tidak memberi kesan kepada bacaan BOD"],b:0,u:"Air larian selepas hujan lebat sering membawa bahan organik dan baja daripada kawasan sekitar, meningkatkan BOD."}],
 bos:{j:"nombor",t:"Berdasarkan Rajah 1, jika bacaan BOD longkang rumah berkurang sebanyak 40% selepas satu sistem rawatan mudah dipasang, berapakah bacaan BOD baharu, dalam mg/L? (Bundarkan kepada satu tempat perpuluhan)",b:11.4,tol:0.2,suf:"mg/L",u:"19 tolak (40% daripada 19, iaitu 7.6) bersamaan 11.4 mg/L."}},

{n:5, tempat:"Makmal", sk:"3.3 Pemeliharaan dan pemuliharaan alam sekitar",
 kadNama:"Teknologi Emisi Negatif", kadEm:"\u{1F331}", kadFakta:"Teknologi emisi negatif menggunakan mikroalga untuk menyerap karbon dioksida daripada atmosfera, malah boleh mengurangkan kandungan karbon yang sedia ada, bukan sekadar mengelakkan pertambahannya.",
 bosKadNama:"Eco-currency", bosKadEm:"\u{1F4B1}", bosKadFakta:"Eco-currency ialah konsep ganjaran berdasarkan tindakan mesra alam seseorang, seperti mengitar semula atau menjimatkan tenaga.",
 soalan:[
 {j:"pilih",t:"Kereta hibrid dianggap teknologi hijau kerana:",p:["Ia gabungkan enjin petrol dan motor elektrik, kurangkan bahan api fosil","Ia hanya boleh bergerak menggunakan tenaga elektrik sepenuhnya sahaja","Ia tidak memerlukan sebarang bahan api untuk bergerak langsung","Ia direka khas untuk perlumbaan berkelajuan tinggi sahaja"],b:0,u:"Gabungan dua sumber tenaga membolehkan penggunaan bahan api fosil dikurangkan tanpa menjejaskan prestasi sepenuhnya."},
 {j:"pilih",t:"Bangunan hijau direka untuk mengurangkan kesan terhadap alam sekitar terutamanya melalui:",p:["Penjimatan tenaga dan air melalui reka bentuk serta bahan binaan cekap","Penggunaan kaca berwarna gelap pada semua tingkap bangunan","Pembinaan tingkat yang lebih tinggi daripada bangunan biasa di kawasan itu","Penggunaan konkrit yang lebih tebal sahaja tanpa sebab lain"],b:0,u:"Bangunan hijau menekankan kecekapan tenaga dan air melalui reka bentuk, pengudaraan semula jadi, dan bahan mampan."},
 {j:"pilih",t:"Emisi Sifar Karbon (Zero Carbon Emission) bagi sesebuah kemudahan bermaksud:",p:["Jumlah bersih karbon dioksida yang dibebaskan adalah sifar","Ia tidak menggunakan sebarang tenaga elektrik langsung","Ia tidak membenarkan kenderaan bermotor masuk","Ia hanya beroperasi pada waktu siang"],b:0,u:"Emisi sifar karbon selalunya dicapai melalui gabungan pengurangan pembebasan dan langkah pengimbangan seperti penanaman pokok."},
 {j:"pilih",t:"Teknologi Emisi Negatif menggunakan mikroalga berbeza daripada teknologi hijau biasa kerana ia:",p:["Secara aktif mengurangkan karbon dioksida sedia ada di atmosfera","Hanya mengelakkan pertambahan karbon dioksida baharu sahaja","Tidak melibatkan sebarang organisma hidup dalam prosesnya","Hanya digunakan dalam industri perikanan tempatan sahaja"],b:0,u:"Kebanyakan teknologi hijau mengelakkan pertambahan karbon, tetapi teknologi emisi negatif turut mengurangkan karbon sedia ada melalui penyerapan oleh mikroalga."},
 {j:"pilih",t:"Nilaikan kenyataan: 'Biodiesel sepenuhnya bebas daripada kesan terhadap alam sekitar kerana ia diperbuat daripada tumbuhan.' Kenyataan ini:",p:["Tidak tepat, kerana penanaman sumber biodiesel besar-besaran juga menjejaskan alam sekitar","Tepat sepenuhnya kerana ia tidak menggunakan bahan api fosil langsung","Tepat kerana biodiesel tidak membebaskan sebarang gas semasa pembakaran","Tidak berkaitan dengan alam sekitar langsung"],b:0,u:"Penanaman tumbuhan sumber biodiesel secara meluas boleh menyebabkan penerokaan hutan dan kehilangan biodiversiti, jadi ia bukan tanpa kesan."},
 {j:"pilih",t:"Peranan setiap individu dalam mengurus sumber semula jadi penting untuk mengekalkan keseimbangan alam sekitar terutamanya kerana:",p:["Tindakan kolektif ramai individu memberi kesan lebih besar berbanding segelintir","Kerajaan sahaja bertanggungjawab sepenuhnya terhadap alam sekitar negara","Individu tidak mampu memberi sebarang kesan kepada alam sekitar langsung","Hanya kilang besar yang perlu mengambil tindakan di negara ini"],b:0,u:"Perubahan tabiat harian ramai individu, apabila digabungkan, memberi kesan yang jauh lebih besar berbanding tindakan segelintir pihak sahaja."},
 {j:"banyak",t:"Pilih SEMUA sektor yang disebut sebagai contoh penerapan Teknologi Hijau.",p:["Kereta hibrid","Teknologi solar","Bangunan hijau","Perlombongan arang batu terbuka","Pembakaran sisa pepejal tanpa kawalan"],b:[0,1,2],u:"Perlombongan arang batu dan pembakaran sisa tanpa kawalan bukan contoh Teknologi Hijau, malah menyumbang kepada pencemaran."},
 {j:"pilih",t:"Konsep eco-currency bertujuan untuk:",p:["Menggalakkan tindakan mesra alam dengan memberi ganjaran atas tindakan itu","Menggantikan sepenuhnya mata wang rasmi sesebuah negara itu","Mengenakan cukai kepada semua pengguna tenaga elektrik negara","Mengehadkan bilangan kenderaan yang boleh dimiliki sesebuah keluarga itu"],b:0,u:"Eco-currency memberi insentif atau ganjaran kepada tindakan mesra alam, bukan menggantikan mata wang rasmi atau mengenakan cukai."}],
 bos:{j:"pilih",t:"Sebuah sekolah ingin memilih SATU teknologi hijau untuk dilaksanakan dengan bajet terhad. Pertimbangan PALING wajar untuk membuat keputusan ialah:",p:["Membandingkan kos, kesan alam sekitar dan kebolehlaksanaan setiap pilihan","Teknologi yang paling mahal kerana pasti paling berkesan","Teknologi yang paling mudah disebut dalam media","Sesuatu secara rawak tanpa sebarang perbandingan"],b:0,u:"Keputusan yang wajar mempertimbangkan pelbagai faktor serentak, bukan hanya kos atau populariti semata-mata."}},

{n:6, tempat:"Persidangan", sk:"3.3 Peranan Pertubuhan Bangsa-Bangsa Bersatu",
 kadNama:"Protokol Kyoto", kadEm:"\u{1F30D}", kadFakta:"Protokol Kyoto ialah perjanjian antarabangsa pertama yang menetapkan sasaran mengikat secara undang-undang untuk mengurangkan pembebasan gas rumah hijau bagi negara maju.",
 bosKadNama:"Persidangan Rio", bosKadEm:"\u{1F91D}", bosKadFakta:"Persidangan Rio 1992 membawa kepada penubuhan Konvensyen Rangka Kerja Bangsa-Bangsa Bersatu mengenai Perubahan Iklim, asas kepada kebanyakan perjanjian iklim antarabangsa kemudiannya.",
 soalan:[
 {j:"pilih",t:"Protokol Kyoto merupakan perjanjian antarabangsa yang bertujuan untuk:",p:["Menetapkan sasaran mengurangkan gas rumah hijau bagi negara menyertainya","Menghapuskan sepenuhnya penggunaan kenderaan bermotor di seluruh dunia","Mewajibkan semua negara menggunakan tenaga solar sepenuhnya","Melarang sepenuhnya perdagangan antarabangsa bahan api fosil"],b:0,u:"Protokol Kyoto menetapkan sasaran pengurangan gas rumah hijau yang mengikat secara undang-undang, bukan larangan mutlak."},
 {j:"pilih",t:"Persidangan Rio 1992 penting dalam sejarah alam sekitar global kerana ia:",p:["Membawa penubuhan rangka kerja antarabangsa perubahan iklim","Menandakan penubuhan Pertubuhan Bangsa-Bangsa Bersatu buat pertama kali","Melarang sepenuhnya penggunaan plastik di seluruh dunia","Menghasilkan teknologi solar buat pertama kali"],b:0,u:"Persidangan Rio membawa kepada Konvensyen Rangka Kerja PBB mengenai Perubahan Iklim, asas kepada perjanjian iklim seterusnya."},
 {j:"pilih",t:"Peranan utama PBB dalam menangani isu alam sekitar global ialah:",p:["Menyediakan platform kerjasama dan perjanjian antarabangsa antara negara anggota","Menguatkuasakan undang-undang alam sekitar terus ke atas setiap individu","Membiayai sepenuhnya semua projek teknologi hijau di dunia","Menggantikan peranan kerajaan tempatan sepenuhnya"],b:0,u:"PBB berfungsi sebagai platform untuk negara anggota berunding dan bersetuju atas tindakan bersama, bukan menguatkuasakan undang-undang terus ke atas individu."},
 {j:"pilih",t:"Mengapakah kerjasama antarabangsa, bukan tindakan satu negara sahaja, diperlukan untuk menangani perubahan iklim?",p:["Gas rumah hijau yang dibebaskan di satu negara memberi kesan kepada atmosfera global, bukan setempat sahaja","Setiap negara mempunyai atmosferanya sendiri yang berasingan","Perubahan iklim hanya menjejaskan negara yang membebaskan gas rumah hijau","Kerjasama antarabangsa tidak memberi sebarang kelebihan berbanding tindakan individu negara"],b:0,u:"Atmosfera Bumi bersambung secara global, jadi pembebasan gas rumah hijau di mana-mana negara memberi kesan kepada seluruh dunia."},
 {j:"pilih",t:"Nilaikan hujah: 'Perjanjian antarabangsa seperti Protokol Kyoto tidak berguna kerana sesetengah negara gagal mencapai sasaran mereka.' Hujah ini:",p:["Terlalu mudah; perjanjian sebegini masih menetapkan hala tuju dan tekanan global","Sepenuhnya tepat, jadi perjanjian sebegini tidak perlu diteruskan","Tidak berkaitan dengan isu alam sekitar global","Hanya benar bagi negara membangun sahaja"],b:0,u:"Walaupun pematuhan tidak sempurna, perjanjian antarabangsa menetapkan sasaran bersama dan tekanan diplomatik yang menggalakkan tindakan berterusan."},
 {j:"banyak",t:"Pilih SEMUA kesan positif yang boleh terhasil daripada perjanjian iklim antarabangsa seperti Protokol Kyoto.",p:["Menetapkan sasaran jelas untuk pengurangan gas rumah hijau","Menggalakkan pemindahan teknologi hijau antara negara","Menghapuskan sepenuhnya keperluan tindakan individu","Meningkatkan kesedaran global terhadap isu perubahan iklim"],b:[0,1,3],u:"Perjanjian antarabangsa tidak menghapuskan keperluan tindakan individu; kedua-duanya saling melengkapi, bukan menggantikan."},
 {j:"pilih",t:"Sebuah negara membangun berhujah bahawa ia patut diberi lebih masa untuk mencapai sasaran pengurangan karbon berbanding negara maju. Hujah yang PALING munasabah untuk menyokong pendirian ini ialah:",p:["Negara maju secara sejarah telah membebaskan lebih banyak gas rumah hijau","Negara membangun tidak membebaskan sebarang gas rumah hijau langsung","Negara maju tidak mempunyai sebarang tanggungjawab terhadap alam sekitar","Sasaran pengurangan karbon tidak penting bagi negara membangun"],b:0,u:"Prinsip tanggungjawab bersama tetapi berbeza dalam perjanjian iklim antarabangsa mengambil kira sejarah pembebasan gas rumah hijau sesebuah negara."},
 {j:"pilih",t:"Antara berikut, manakah PALING TEPAT menggambarkan hubungan antara tindakan individu dan perjanjian antarabangsa seperti Protokol Kyoto?",p:["Kedua-duanya saling melengkapi; tindakan individu menyokong sasaran antarabangsa","Tindakan individu tidak memberi sebarang kesan berbanding perjanjian antarabangsa","Perjanjian antarabangsa menggantikan sepenuhnya keperluan tindakan individu","Kedua-duanya tidak mempunyai sebarang kaitan antara satu sama lain"],b:0,u:"Sasaran besar yang ditetapkan pada peringkat antarabangsa dicapai melalui pelaksanaan pada peringkat kerajaan tempatan dan individu."}],
 bos:{j:"buka",
  t:"Sekolah awak ingin melancarkan satu kempen 'Kelestarian Alam Sekitar' untuk mengurangkan jejak karbon warga sekolah dalam tempoh satu penggal. Reka satu pelan kempen yang praktikal untuk sekolah awak.",
  arahan:"Nyatakan SATU masalah alam sekitar khusus yang kempen awak sasarkan (contohnya sisa plastik, penggunaan elektrik berlebihan, atau pembaziran makanan), SATU tindakan konkrit yang akan dilaksanakan oleh warga sekolah, cara awak mengukur kejayaan kempen itu, dan bagaimana awak memastikan penyertaan berterusan warga sekolah sepanjang tempoh kempen.",
  u:"Jawapan TP6 yang kukuh menggabungkan sains alam sekitar (punca dan kesan masalah yang dipilih), pelan tindakan yang praktikal dan boleh diukur, serta strategi mengekalkan penyertaan warga sekolah."}}
];

module.exports = {
  id:"t5b3", tingkatan:5, kod:"3.0 Kelestarian Alam Sekitar",
  tajuk:"Laluan Lestari",
  subtajuk:"Sains Ting. 5 · Bab 3 Kelestarian Alam Sekitar",
  spi:SPI,
  ulasan:{
   1:"{n} dapat mengingat kembali konsep jejak karbon dan gas rumah hijau serta mengenal pasti aktiviti harian yang menyumbang kepadanya. Langkah seterusnya ialah menerangkan sebab di sebalik setiap sumbangan itu, bukan sekadar menyenaraikannya.",
   2:"{n} memahami kitar hayat produk daripada bahan mentah hingga pelupusan, termasuk konsep 'cradle to cradle', 'cradle to grave' dan upcycle. Perlu lebih banyak latihan mengaitkan konsep ini dengan produk harian sebelum bergerak ke TP3.",
   3:"{n} boleh mengaplikasikan pengetahuan untuk mengenal pasti jenis dan punca pencemaran alam sekitar daripada situasi sebenar seperti hujan asid, pencemaran terma dan eutrofikasi. Galakkan mentafsir data eksperimen berkaitan pencemaran.",
   4:"{n} mampu menganalisis data BOD daripada pelbagai sumber air dan mengaitkannya dengan tahap pencemaran organik. Seterusnya latih menimbang faktor tambahan seperti kos dan kebolehlaksanaan sebelum membuat cadangan.",
   5:"{n} dapat menilai pilihan teknologi hijau serta peranan individu dalam mengekalkan keseimbangan alam sekitar, disokong hujah yang munasabah. Sudah bersedia untuk tugasan mereka cipta pelan tindakan sendiri.",
   6:"{n} berjaya mereka cipta pelan kempen kelestarian alam sekitar yang praktikal, lengkap dengan masalah disasarkan, tindakan konkrit dan cara mengukur kejayaannya. Pencapaian cemerlang bagi bab ini.",
   tiada:"{n} belum menunjukkan bukti penguasaan yang mencukupi bagi bab Kelestarian Alam Sekitar. Cadangan: ulang aktiviti hentian pertama dengan bimbingan rakan sebaya."
  },
  lampiran:{ kitarProduk:R_KITAR_PRODUK, grafBod:R_GRAF_BOD },
  aras:ARAS
};
