/* Sumber kandungan — Sains KSSM Tingkatan 5, Bidang 7.0 Cahaya dan Optik.
   Fail ini disunting tangan. Jalankan `node bina.js t5b7` untuk menyemaknya
   dan menghasilkan bank-t5b7.js dengan kedudukan jawapan yang seimbang.

   Standard Prestasi disalin kata demi kata daripada DSKP KSSM Sains
   Tingkatan 4 dan 5, Bahagian Pembangunan Kurikulum, muka 154.

   Tulis jawapan betul pada indeks 0. Pembina akan mengagihkannya. */

const SPI = [
"Mengingat kembali pengetahuan dan kemahiran saintifik mengenai cahaya dan optik.",
"Memahami cahaya dan optik dan dapat menjelaskan kefahaman tersebut.",
"Mengaplikasikan pengetahuan mengenai cahaya dan optik dan dapat melaksanakan tugasan mudah.",
"Menganalisis pengetahuan mengenai cahaya dan optik dalam konteks penyelesaian masalah mengenai kejadian atau fenomena alam.",
"Menilai pengetahuan mengenai cahaya dan optik dalam konteks penyelesaian masalah dan membuat keputusan untuk melaksanakan satu tugasan.",
"Mereka cipta dengan menggunakan pengetahuan dan kemahiran sains mengenai cahaya dan optik dalam konteks penyelesaian masalah dan membuat keputusan atau dalam melaksanakan satu tugasan dalam situasi baru secara kreatif dan inovatif dengan mengambil kira nilai sosial/ekonomi/budaya masyarakat."];

/* ---------- lampiran ---------- */
/* Kedudukan imej dikira daripada rumus kanta nipis oleh tools/lukis/kanta.js,
   bukan dilukis dengan agakan. */

const R_JAUH = {
  jenis:"kanta", jenisKanta:"cembung", f:3, u:9, ho:0.7, skala:12,
  kapsyen:"Rajah 1 · Objek pada u > 2f melalui kanta cembung.",
  alt:"Rajah sinar kanta cembung dengan objek jauh melebihi dua kali panjang fokus, menghasilkan imej nyata songsang mengecil antara F dan 2F"
};

const R_DEKAT = {
  jenis:"kanta", jenisKanta:"cembung", f:3, u:1.5, ho:0.7, skala:12,
  kapsyen:"Rajah 2 · Objek pada u < f melalui kanta cembung.",
  alt:"Rajah sinar kanta cembung dengan objek dekat dalam jarak fokus, menghasilkan imej maya tegak membesar pada sebelah objek, seperti kanta pembesar"
};

const R_CEKUNG = {
  jenis:"kanta", jenisKanta:"cekung", f:3, u:5, ho:0.7, skala:12,
  kapsyen:"Rajah 3 · Objek melalui kanta cekung.",
  alt:"Rajah sinar kanta cekung menghasilkan imej maya tegak dan mengecil pada sebelah objek, tidak kira jarak objek"
};

const R_TELESKOP = {
  jenis:"aliran", mod:"turun",
  nod:[
    { label:"Cahaya dari objek jauh tiba dalam berkas selari", isi:"kertas2" },
    { label:"Kanta objektif memfokuskan cahaya, membentuk imej pertama: nyata, songsang, kecil", isi:"hijauLembut", panah:"hijau" },
    { label:"Imej pertama jatuh dalam jarak fokus kanta mata", isi:"kuningLembut", panah:"kuning" },
    { label:"Kanta mata bertindak sebagai kanta pembesar", isi:"lembayungLembut", panah:"lembayung" },
    { label:"Imej akhir: maya, songsang, dibesarkan", isi:"merahLembut", panah:"merah" },
  ],
  kapsyen:"Rajah 4 · Laluan pembentukan imej dalam teleskop pembiasan.",
  alt:"Rajah aliran menegak lima peringkat pembentukan imej dalam teleskop: cahaya selari, imej pertama oleh kanta objektif, jatuh dalam fokus kanta mata, kanta mata sebagai pembesar, imej akhir maya songsang dibesarkan"
};

/* ---------- hentian ---------- */

const ARAS = [

{n:1, tempat:"Paksi Utama", sk:"7.1 Pembentukan imej oleh kanta", lampiran:"jauh",
 kadNama:"Kanta Penumpu", kadEm:"\u{1F50D}", kadFakta:"Kanta cembung lebih tebal di tengah berbanding di tepi, dan itulah sebabnya ia menumpukan sinar selari ke satu titik fokus.",
 bosKadNama:"Kanta Pencapah", bosKadEm:"\u{1F576}", bosKadFakta:"Kanta cekung digunakan dalam pengintip pintu supaya seluruh koridor kelihatan dalam satu bulatan kecil.",
 soalan:[
 {j:"pilih",t:"Kanta cembung dikenali sebagai kanta:",p:["Penumpu, kerana ia menumpukan sinar selari ke satu titik","Pencapah, kerana ia mencapahkan sinar selari ke pelbagai arah","Penumpu, kerana ia lebih nipis di tengah berbanding di tepi","Pencapah, kerana ia hanya membiaskan cahaya berwarna"],b:0,u:"Kanta cembung lebih tebal di tengah, jadi ia membiaskan sinar selari supaya bertemu di satu titik fokus."},
 {j:"pilih",t:"Kanta cekung dikenali sebagai kanta:",p:["Pencapah, kerana ia mencapahkan sinar selari seolah datang dari satu titik","Penumpu, kerana ia menumpukan sinar selari ke satu titik di belakangnya sahaja","Pencapah, kerana ia lebih tebal di tengah berbanding di tepi kanta","Penumpu, kerana ia hanya berfungsi pada cahaya terang sahaja"],b:0,u:"Kanta cekung lebih nipis di tengah, jadi sinar selari yang melaluinya mencapah keluar."},
 {j:"pilih",t:"Paksi utama sesuatu kanta ialah:",p:["Garis lurus melalui pusat optik kanta secara berserenjang dengan kanta","Garis yang menyambungkan hujung atas dan bawah kanta itu sendiri sahaja","Garis yang menunjukkan arah sinar yang paling terang di antaranya","Garis yang membahagikan kanta kepada dua bahagian berlainan bahan itu"],b:0,u:"Semua jarak (u, v, f) diukur sepanjang paksi utama ini."},
 {j:"pilih",t:"Pusat optik (O) sesuatu kanta ialah:",p:["Titik di tengah kanta tempat paksi utama itu melaluinya","Titik di permukaan kanta yang paling melengkung sekali","Titik pertemuan semua sinar selepas ia membias","Titik pada objek yang paling hampir dengan kanta itu"],b:0,u:"Sinar yang melalui pusat optik tidak mengalami sebarang pesongan arah."},
 {j:"pilih",t:"Titik fokus utama (F) sesuatu kanta cembung ialah:",p:["Titik pada paksi utama tempat sinar selari bertumpu selepas membias","Titik pada permukaan kanta tempat cahaya mula-mula menyentuhnya itu sekali","Titik tengah antara kanta dan objek yang sedang diperhatikan itu","Titik pada paksi utama tempat objek itu mesti diletakkan pula"],b:0,u:"Jarak dari pusat optik ke titik ini dipanggil panjang fokus, f."},
 {j:"pilih",t:"Jarak imej, v, ditakrifkan sebagai:",p:["Jarak dari pusat optik kanta ke imej yang telah terbentuk","Jarak dari objek ke pusat optik kanta itu sendiri","Jarak dari titik fokus ke objek yang diperhatikan","Ketinggian imej yang terbentuk berbanding objek asal"],b:0,u:"Jarak objek u dan jarak imej v kedua-duanya diukur dari pusat optik, bukan dari tepi kanta."},
 {j:"susun",t:"Susun istilah kanta berikut daripada yang paling dekat dengan kanta ke yang paling jauh, bagi kanta cembung dengan objek pada u > 2f.",p:["Pusat optik (O)","Titik fokus (F)","Titik 2F","Kedudukan objek (u)"],b:[0,1,2,3],u:"Bagi u > 2f, objek diletakkan melepasi titik 2F, iaitu paling jauh daripada kanta berbanding O, F dan 2F itu sendiri."},
 {j:"pilih",t:"Berdasarkan Rajah 1, apakah yang berlaku kepada sinar yang melalui pusat optik kanta?",p:["Ia diteruskan tanpa sebarang pesongan arah","Ia membias tajam ke arah titik fokus F","Ia dipantulkan semula ke arah objek","Ia terhenti di pusat optik dan tidak diteruskan"],b:0,u:"Ini salah satu daripada dua sinar utama yang digunakan untuk membina rajah sinar kanta."}],
 bos:{j:"banyak",t:"Pilih SEMUA pernyataan yang benar mengenai kanta cembung dan kanta cekung.",p:["Kanta cembung lebih tebal di tengah berbanding di tepi","Kanta cekung lebih nipis di tengah berbanding di tepi","Kanta cembung menumpukan sinar selari ke satu titik fokus","Kanta cekung boleh membentuk imej nyata bagi sebarang jarak objek","Kedua-dua jenis kanta hanya boleh dibuat daripada kaca"],b:[0,1,2],u:"Kanta cekung sentiasa membentuk imej maya sahaja, dan kanta boleh dibuat daripada plastik optik juga."}},

{n:2, tempat:"Kanta Cembung", sk:"7.1 Pembentukan imej oleh kanta", lampiran:"dekat",
 kadNama:"Kanta Pembesar", kadEm:"\u{1F50E}", kadFakta:"Kanta pembesar berfungsi dengan meletakkan objek dalam jarak fokus kanta cembung, menghasilkan imej maya yang jauh lebih besar.",
 bosKadNama:"Panjang Fokus", kadEm2:"", bosKadEm:"\u{1F4CF}", bosKadFakta:"Panjang fokus kanta cembung boleh ditentukan dengan memfokuskan imej objek yang sangat jauh, seperti matahari atau pokok jauh, pada skrin.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 2, mengapakah imej yang terbentuk digelar imej maya?",p:["Sinar yang membias tidak bertemu, hanya sambungannya sahaja bertemu","Imej itu tidak dapat dilihat oleh mata manusia secara langsung sekalipun","Imej itu tidak mempunyai kedudukan yang tepat pada paksi utama itu","Sinar yang membias bertemu tepat pada permukaan kanta itu sendiri sahaja"],b:0,u:"Imej maya terbentuk apabila sambungan sinar (garis putus) bertemu, bukan sinar sebenar."},
 {j:"pilih",t:"Berdasarkan Rajah 2, di sebelah manakah imej maya itu terbentuk berbanding kanta?",p:["Sebelah yang sama dengan objek","Sebelah bertentangan dengan objek","Tepat di atas kanta itu sendiri","Pada jarak 2F dari kanta, tidak kira sebelah mana"],b:0,u:"Imej maya kanta cembung sentiasa terbentuk pada sebelah objek, lebih jauh daripada objek itu sendiri."},
 {j:"pilih",t:"Cara paling sesuai untuk menentukan panjang fokus kanta cembung menggunakan objek jauh ialah:",p:["Fokuskan imej objek jauh pada skrin; jarak kanta ke skrin itu ialah f","Ukur jarak dari objek ke kanta sahaja tanpa menggunakan sebarang skrin","Ukur ketebalan kanta di tengah berbanding di tepi kanta itu","Bandingkan saiz kanta dengan saiz bingkai cermin mata itu"],b:0,u:"Objek yang sangat jauh dianggap berada pada infiniti, jadi sinar daripadanya hampir selari dan imej terbentuk tepat pada F."},
 {j:"pilih",t:"Apakah ciri imej apabila objek diletakkan tepat pada u = f?",p:["Sinar keluar selari daripada kanta itu, jadi tiada imej terbentuk","Ia terbentuk tepat pada permukaan kanta itu sendiri sahaja","Ia maya dan terbentuk sama saiz dengan objek asal","Ia nyata dan terbentuk pada jarak 2f daripada kanta itu"],b:0,u:"Ini kes istimewa: 1/v menjadi sifar, iaitu v tidak terhingga."},
 {j:"pilih",t:"Bagi kanta cembung dengan f < u < 2f, ciri imej yang terbentuk ialah:",p:["Nyata, songsang, dan lebih besar daripada objek","Maya, tegak, dan lebih besar daripada objek","Nyata, songsang, dan lebih kecil daripada objek","Maya, tegak, dan sama saiz dengan objek"],b:0,u:"Dalam julat ini, v > 2f, jadi imej terbentuk lebih jauh dan lebih besar, tetapi tetap nyata dan songsang."},
 {j:"pilih",t:"Bagi kanta cembung dengan u = 2f, ciri imej yang terbentuk ialah:",p:["Nyata, songsang, dan sama saiz dengan objek","Maya, tegak, dan sama saiz dengan objek","Nyata, tegak, dan lebih besar daripada objek","Maya, songsang, dan lebih kecil daripada objek"],b:0,u:"Pada u = 2f, v juga bersamaan 2f, jadi magnifikasi tepat 1×."},
 {j:"nombor",t:"Sebuah kanta cembung mempunyai panjang fokus 10 cm. Sebiji objek diletakkan pada jarak 6 cm daripada kanta. Berapakah jarak imej, v, dalam cm? (Guna 1/f = 1/u + 1/v; imej maya dicatat sebagai nilai negatif.)",b:-15,tol:0.5,suf:"cm",u:"1/v = 1/10 − 1/6 = 3/30 − 5/30 = −2/30, jadi v = -15 cm. Nilai negatif menunjukkan imej maya."},
 {j:"pilih",t:"Berdasarkan pengiraan di atas (f = 10 cm, u = 6 cm), apakah magnifikasi imej itu?",p:["2.5×, imej dibesarkan","0.4×, imej dikecilkan","1.5×, imej dibesarkan","15×, imej dibesarkan"],b:0,u:"m = |v/u| = 15/6 = 2.5×. Kanta digunakan sebagai kanta pembesar apabila u < f."}],
 bos:{j:"nombor",t:"Sebuah kanta cembung berpanjang fokus 8 cm digunakan sebagai kanta pembesar dengan objek pada jarak 5 cm. Berapakah magnifikasi imej, dibundarkan kepada satu tempat perpuluhan?",b:2.7,tol:0.1,suf:"×",u:"1/v = 1/8 − 1/5 = 5/40 − 8/40 = −3/40, jadi v = −13.33 cm. m = 13.33/5 ≈ 2.7×."}},

{n:3, tempat:"Kanta Cekung", sk:"7.1 Pembentukan imej oleh kanta", lampiran:"cekung",
 kadNama:"Imej Maya Tetap", kadEm:"\u{1F441}", kadFakta:"Tidak kira sejauh mana objek diletakkan, kanta cekung sentiasa menghasilkan imej maya, tegak, dan mengecil.",
 bosKadNama:"Kanta Bersepadu", bosKadEm:"\u{1F4F1}", bosKadFakta:"Kamera telefon pintar moden menggunakan gabungan beberapa kanta cembung dan cekung yang sangat nipis untuk mengurangkan herotan imej.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 3, apakah ciri imej yang terbentuk oleh kanta cekung?",p:["Maya, tegak, dan mengecil","Nyata, songsang, dan mengecil","Maya, songsang, dan membesar","Nyata, tegak, dan membesar"],b:0,u:"Kanta cekung mencapahkan sinar, jadi sambungan sinar sentiasa bertemu pada sebelah objek sahaja, menghasilkan imej maya tegak."},
 {j:"pilih",t:"Mengapakah kanta cekung TIDAK PERNAH menghasilkan imej nyata, tidak kira jarak objek?",p:["Sinar yang mencapah tidak pernah benar-benar bertemu selepas ia membias","Kanta cekung terlalu nipis untuk membiaskan cahaya dengan begitu ketara","Objek mesti sentiasa berada pada jarak yang sangat jauh daripadanya","Kanta cekung hanya berfungsi dengan cahaya terang sahaja tanpa lain"],b:0,u:"Hanya sambungan sinar (garis putus di belakang) yang bertemu, dan itulah takrif imej maya."},
 {j:"pilih",t:"Nilai jarak fokus, f, bagi kanta cekung dalam rumus 1/f = 1/u + 1/v dicatat sebagai:",p:["Negatif, kerana ia kanta mencapah","Positif, sama seperti kanta cembung","Sifar, kerana ia tidak mempunyai fokus sebenar","Bergantung kepada jarak objek yang digunakan"],b:0,u:"Konvensyen nyata-adalah-positif menetapkan f negatif untuk kanta mencapah, supaya v yang terhasil sentiasa negatif juga."},
 {j:"pilih",t:"Aplikasi harian yang menggunakan kanta cekung ialah:",p:["Cermin mata untuk membetulkan rabun jauh","Ia sebagai pembesar untuk membaca tulisan halus","Ia sebagai objektif dalam mikroskop","Ia sebagai projektor panggung wayang"],b:0,u:"Rabun jauh dibetulkan dengan kanta cekung supaya imej objek jauh jatuh tepat pada retina, bukan di hadapannya."},
 {j:"pilih",t:"Berbanding kanta cembung dengan objek pada u > 2f, apakah perbezaan utama imej kanta cekung?",p:["Imej kanta cekung sentiasa maya, kanta cembung dalam kes itu nyata","Imej kanta cekung sentiasa lebih besar, manakala kanta cembung lebih kecil sahaja","Imej kanta cekung terbentuk lebih jauh, manakala kanta cembung lebih dekat sahaja","Imej kanta cekung songsang, manakala kanta cembung sentiasa tegak"],b:0,u:"Kanta cembung dengan u > 2f menghasilkan imej nyata songsang, berbeza sepenuhnya dengan kanta cekung."},
 {j:"nombor",t:"Sebuah kanta cekung berpanjang fokus bermagnitud 10 cm digunakan dengan objek pada jarak 15 cm. Berapakah jarak imej, v, dalam cm? (Catat sebagai nilai negatif jika maya.)",b:-6,tol:0.5,suf:"cm",u:"f = −10 cm. 1/v = 1/(−10) − 1/15 = −3/30 − 2/30 = −5/30, jadi v = -6 cm."},
 {j:"pilih",t:"Berdasarkan pengiraan di atas (f = −10 cm, u = 15 cm), apakah magnifikasi imej itu?",p:["0.4×, imej mengecil","2.5×, imej membesar","1.5×, imej mengecil","0.67×, imej membesar"],b:0,u:"m = |v/u| = 6/15 = 0.4×, konsisten dengan sifat kanta cekung yang sentiasa mengecilkan imej."},
 {j:"pilih",t:"Jika jarak objek pada kanta cekung ditambah dua kali ganda, apakah yang berlaku kepada saiz imej maya itu?",p:["Saiz imej semakin mengecil berbanding sebelumnya","Saiz imej semakin membesar berbanding sebelumnya","Saiz imej kekal sama tidak kira jarak objek","Imej bertukar daripada maya kepada nyata"],b:0,u:"Apabila u bertambah, nisbah |v/u| bagi kanta cekung semakin kecil, jadi imej semakin mengecil, walaupun tetap maya dan tegak."}],
 bos:{j:"pilih",t:"Nilaikan kenyataan ini: 'Kanta cekung tidak berguna kerana ia tidak pernah membesarkan imej.'",p:["Tidak tepat, kerana imej yang lebih kecil dan medan pandang lebih luas berguna untuk tujuan seperti pengintip pintu dan kanta pembetul rabun jauh","Tepat, kerana kanta yang tidak membesarkan imej tidak mempunyai kegunaan praktikal dalam kehidupan seharian","Tidak tepat, kerana kanta cekung sebenarnya turut boleh membesarkan imej dalam keadaan tertentu","Tepat, kerana hanya kanta cembung yang digunakan dalam semua peralatan optik moden"],b:0,u:"Kegunaan sesuatu kanta bergantung pada keperluan optik, bukan semata-mata pada magnifikasi; medan pandang luas dan imej tegak juga bernilai."}},

{n:4, tempat:"Kanta Objektif", sk:"7.2 Peralatan optik", lampiran:"teleskop",
 kadNama:"Teleskop Pembiasan", kadEm:"\u{1F52D}", kadFakta:"Teleskop pembiasan pertama Galileo pada tahun 1609 hanya mampu membesarkan imej kira-kira 20 kali, tetapi cukup untuk menemui empat bulan besar Musytari.",
 bosKadNama:"Mikroskop Majmuk", bosKadEm:"\u{1F52C}", bosKadFakta:"Kuasa pembesaran mikroskop majmuk ialah hasil darab pembesaran kanta objektif dan kanta mata, bukan jumlahnya.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 4, apakah fungsi kanta objektif dalam teleskop?",p:["Membentuk imej pertama yang nyata, songsang, dan kecil daripada objek","Membesarkan imej pertama supaya lebih jelas dilihat oleh mata kita","Memantulkan cahaya terus ke mata pemerhati tanpa membiaskannya","Menapis cahaya supaya hanya satu warna sahaja yang diteruskan"],b:0,u:"Kanta objektif ialah kanta cembung pertama yang menangkap cahaya selari daripada objek jauh."},
 {j:"pilih",t:"Berdasarkan Rajah 4, apakah fungsi kanta mata dalam teleskop?",p:["Bertindak sebagai kanta pembesar untuk membesarkan imej pertama itu","Membentuk imej pertama daripada cahaya objek yang jauh","Membalikkan semula imej supaya ia kelihatan tegak","Menghalang cahaya terang daripada memasuki mata secara terus"],b:0,u:"Imej pertama daripada kanta objektif jatuh dalam jarak fokus kanta mata, jadi kanta mata berfungsi seperti kanta pembesar."},
 {j:"pilih",t:"Ciri imej akhir yang dilihat oleh mata melalui teleskop pembiasan ialah:",p:["Maya, songsang, dan dibesarkan","Nyata, tegak, dan dibesarkan","Maya, tegak, dan dikecilkan","Nyata, songsang, dan sama saiz"],b:0,u:"Imej akhir teleskop astronomi mudah kekal songsang, sebab itu ia sesuai untuk memerhati angkasa tetapi bukan pemandangan di bumi."},
 {j:"pilih",t:"Pada pelarasan normal, jarak antara kanta objektif dan kanta mata dalam teleskop ialah:",p:["Jumlah panjang fokus kedua-dua kanta, fo + fe","Beza panjang fokus kedua-dua kanta, fo − fe","Hasil darab panjang fokus kedua-dua kanta, fo × fe","Sentiasa tetap 10 cm tidak kira jenis kanta"],b:0,u:"Ini memastikan imej pertama jatuh tepat pada titik fokus kanta mata untuk pelarasan normal."},
 {j:"nombor",t:"Sebuah teleskop mempunyai kanta objektif berpanjang fokus 90 cm dan kanta mata berpanjang fokus 5 cm. Pada pelarasan normal, berapakah jarak antara kedua-dua kanta, dalam cm?",b:95,tol:0.5,suf:"cm",u:"fo + fe = 90 + 5 = 95 cm."},
 {j:"pilih",t:"Kuasa pembesaran mikroskop majmuk dikira dengan cara:",p:["Mendarab pembesaran kanta objektif dengan pembesaran kanta mata","Menambah pembesaran kanta objektif dengan pembesaran kanta mata","Membahagi pembesaran kanta objektif dengan pembesaran kanta mata","Menolak pembesaran kanta mata daripada pembesaran kanta objektif"],b:0,u:"Ini sebabnya mikroskop menggunakan gabungan kanta objektif dan kanta mata berlainan kuasa untuk kajian berbeza."},
 {j:"nombor",t:"Kanta objektif mikroskop membesarkan imej 40× dan kanta matanya membesarkan 10×. Berapakah kuasa pembesaran keseluruhan mikroskop itu?",b:400,tol:1,suf:"×",u:"40 × 10 = 400×."},
 {j:"pilih",t:"Alatan harian yang menggunakan kanta cembung untuk membentuk imej pada sensor atau filem ialah:",p:["Kamera dan telefon pintar","Cermin mata pembetul rabun jauh sahaja","Pengintip pintu sahaja","Kanta cekung dalam kaca mata renang"],b:0,u:"Kamera dan telefon pintar menggunakan kanta cembung untuk memfokuskan imej nyata pada sensor cahaya."}],
 bos:{j:"pilih",t:"Mengapakah telefon pintar moden semakin nipis sukar direka dengan kanta kamera berkuasa tinggi?",p:["Fokus lebih besar perlukan jarak imej lebih jauh, ketebalan jadi had","Kanta berkuasa tinggi terlalu berat untuk dipasang pada telefon pintar","Kanta berkuasa tinggi hanya berfungsi dengan bateri yang sangat besar","Sensor kamera tidak dapat berfungsi dengan kanta cembung sama sekali"],b:0,u:"Jarak imej v bergantung pada panjang fokus kanta; kanta berkuasa tinggi (f besar) memerlukan ruang lebih dalam untuk sensor menerima imej yang fokus, dan itulah sebabnya kamera telefon pintar guna gabungan kanta nipis berlapis, bukan satu kanta tebal."}},

{n:5, tempat:"Reka Bentuk Optik", sk:"7.1 / 7.2 Menilai reka bentuk optik", lampiran:"jauh",
 kadNama:"Ujian Objek Jauh", kadEm:"\u{1F31E}", kadFakta:"Matahari dianggap 'objek pada infiniti' dalam optik kerana jaraknya begitu jauh sehingga sinar yang sampai ke Bumi praktikalnya selari.",
 bosKadNama:"Aberasi Kanta", bosKadEm:"\u{1F4A1}", bosKadFakta:"Kanta tunggal yang ringkas sering menghasilkan imej kabur di tepi, dipanggil aberasi, dan itulah sebabnya kamera profesional menggunakan gabungan banyak kanta nipis.",
 soalan:[
 {j:"pilih",t:"Seorang murid mengukur panjang fokus kanta cembung dengan memfokuskan imej pokok yang berjarak 3 meter, bukan objek yang sangat jauh seperti matahari. Nilaikan kesahan kaedah ini.",p:["Kurang tepat, kerana 3 meter belum cukup jauh untuk dianggap selari sepenuhnya, jadi jarak yang diukur sedikit lebih besar daripada f sebenar","Tepat sepenuhnya, kerana sebarang objek yang lebih jauh daripada kanta dianggap berada pada infiniti","Kurang tepat, kerana pokok tidak memantulkan cahaya seperti matahari","Tepat sepenuhnya, kerana jarak objek tidak mempengaruhi ketepatan ukuran panjang fokus"],b:0,u:"Semakin dekat objek berbanding infiniti sebenar, semakin besar v berbanding f sebenar, walaupun perbezaannya kecil pada jarak beberapa meter."},
 {j:"pilih",t:"Dua kanta cembung mempunyai panjang fokus 5 cm dan 20 cm. Kanta manakah lebih sesuai sebagai kanta objektif teleskop, dan mengapa?",p:["Kanta 20 cm, kerana panjang fokus objektif yang lebih besar menghasilkan imej pertama yang lebih besar","Kanta 5 cm, kerana panjang fokus objektif yang lebih kecil menghasilkan imej pertama yang lebih besar","Kanta 20 cm, kerana ia lebih ringan dan mudah dipasang pada tiub teleskop","Kedua-dua kanta sama sesuai kerana panjang fokus objektif tidak mempengaruhi pembesaran"],b:0,u:"Pembesaran teleskop lebih kurang fo/fe, jadi objektif berfokus panjang menghasilkan pembesaran keseluruhan yang lebih tinggi."},
 {j:"pilih",t:"Seorang jurutera mereka bentuk kanta pembesar untuk tukang jam. Panjang fokus manakah lebih sesuai — 3 cm atau 15 cm — untuk magnifikasi yang lebih tinggi apabila objek diletakkan dekat dengan kanta?",p:["3 cm, kerana panjang fokus yang lebih kecil menghasilkan nisbah v/u yang lebih besar bagi jarak objek yang sama","15 cm, kerana panjang fokus yang lebih besar membolehkan objek diletakkan lebih dekat","3 cm, kerana kanta yang lebih kecil sentiasa lebih murah untuk dihasilkan","15 cm, kerana panjang fokus yang lebih besar mengurangkan herotan imej"],b:0,u:"Bagi u yang sama dan lebih kecil daripada f, kanta berfokus pendek memberikan nisbah |v/u| yang lebih besar, jadi magnifikasi lebih tinggi."},
 {j:"pilih",t:"Nilaikan cadangan ini: 'Gunakan kanta cekung sebagai kanta objektif teleskop supaya imej akhir kelihatan tegak, bukan songsang.'",p:["Tidak sesuai, kerana kanta cekung tidak pernah membentuk imej pertama yang nyata untuk dibesarkan oleh kanta mata","Sesuai sepenuhnya, kerana kanta cekung menghasilkan imej yang lebih terang berbanding kanta cembung","Tidak sesuai, kerana kanta cekung terlalu berat untuk dipasang di hujung teleskop","Sesuai sepenuhnya, kerana kanta cekung menghasilkan magnifikasi yang lebih tinggi"],b:0,u:"Kanta objektif mesti membentuk imej nyata untuk kanta mata membesarkannya; kanta cekung sentiasa memberi imej maya sahaja, jadi ia tidak boleh berfungsi sebagai objektif teleskop pembiasan mudah."},
 {j:"pilih",t:"Seorang murid mencadangkan mikroskop menggunakan kanta objektif berpembesaran 5× dan kanta mata berpembesaran 5× untuk mendapat kuasa pembesaran 400×, dengan menambah kedua-dua nilai lalu mendarab dengan 40. Nilaikan cadangan ini.",p:["Salah, kerana kuasa pembesaran ialah hasil darab terus kedua-dua kanta, iaitu 5 × 5 = 25×, bukan 400×", "Betul, kerana kaedah tambah kemudian darab turut memberikan jawapan yang sah dalam optik", "Salah, kerana kuasa pembesaran mikroskop hanya bergantung pada kanta objektif sahaja", "Betul, kerana sebarang gabungan pengiraan yang munasabah akan memberi jawapan yang sama"],b:0,u:"Formula yang betul ialah darab terus: pembesaran objektif × pembesaran mata. 5× dan 5× hanya memberi 25×, bukan 400×."},
 {j:"pilih",t:"Sebuah syarikat mahu mereka bentuk kanta pembesar poket yang sangat nipis tetapi berkuasa tinggi. Cabaran fizik utama yang perlu ditangani ialah:",p:["Kanta berfokus pendek biasanya perlu lebih melengkung, jadi ia sukar dibuat nipis tanpa mengurangkan kualiti imej","Kanta berfokus pendek sentiasa lebih ringan berbanding kanta berfokus panjang","Kanta nipis secara semula jadi tidak dapat membesarkan imej sama sekali","Warna kanta perlu ditukar kepada warna gelap untuk mendapat kuasa tinggi"],b:0,u:"Panjang fokus pendek biasanya bermakna lengkungan permukaan kanta lebih ketara, jadi reka bentuk nipis-tetapi-berkuasa-tinggi memerlukan bahan atau bentuk kanta yang lebih canggih."},
 {j:"pilih",t:"Berdasarkan Rajah 1, jika objek digerakkan lebih jauh daripada kedudukan asalnya (u bertambah, kekal u > 2f), apakah yang berlaku kepada saiz dan kedudukan imej?",p:["Imej menjadi lebih kecil dan bergerak lebih dekat dengan titik fokus F","Imej menjadi lebih besar dan bergerak lebih jauh daripada kanta","Imej kekal sama saiz tidak kira jarak objek, selagi u > 2f","Imej bertukar daripada nyata kepada maya apabila u bertambah"],b:0,u:"Apabila u bertambah tanpa had, v menghampiri f, dan magnifikasi |v/u| semakin mengecil."},
 {j:"pilih",t:"Apakah bukti terbaik untuk mengesahkan panjang fokus kanta yang dilaporkan oleh pengeluar adalah tepat?",p:["Ukur v bagi beberapa nilai u yang berbeza dan sahkan ia konsisten dengan 1/f = 1/u + 1/v","Bandingkan berat kanta itu dengan kanta lain yang panjang fokusnya diketahui","Tanya pendapat beberapa pengguna lain tentang ketajaman imej kanta itu","Perhatikan warna kanta di bawah cahaya matahari secara terus"],b:0,u:"Ukuran berulang pada u berbeza-beza yang konsisten dengan formula kanta memberikan bukti kukuh, bukan pendapat atau pemerhatian tidak langsung."}],
 bos:{j:"pilih",t:"Sebuah sekolah mahu membina teleskop mudah untuk kelab astronomi dengan bajet terhad, hanya mampu membeli dua kanta cembung: satu berpanjang fokus 60 cm dan satu lagi 4 cm. Nilaikan susunan yang paling sesuai.",p:["Kanta 60 cm sebagai objektif dan kanta 4 cm sebagai kanta mata, dipasang pada jarak lebih kurang 64 cm, memberi pembesaran lebih kurang 15×","Kanta 4 cm sebagai objektif dan kanta 60 cm sebagai kanta mata, kerana kanta objektif sepatutnya lebih kecil untuk muat di hujung tiub","Kedua-dua kanta perlu panjang fokus yang sama supaya imej akhir kelihatan tegak","Susunan kanta tidak penting selagi kedua-duanya kanta cembung yang berkualiti tinggi"],b:0,u:"Objektif berfokus panjang menghasilkan imej pertama yang lebih besar, dan kanta mata berfokus pendek membesarkannya lagi; pembesaran lebih kurang fo/fe = 60/4 = 15×. Menyongsangkan kanta akan menjadikan teleskop itu hampir tidak berguna."}},

{n:6, tempat:"Peralatan Optik", sk:"7.2 Mereka cipta peralatan optik", lampiran:"dekat",
 kadNama:"Reka Bentuk Mesra Belia", kadEm:"\u{1F393}", kadFakta:"Kelab sains sekolah di serata Malaysia telah membina teleskop Galileo mudah daripada tiub kadbod dan kanta cermin mata terpakai untuk aktiviti STEM.",
 bosKadNama:"Peralatan Optik Kos Rendah", bosKadEm:"\u{267B}", bosKadFakta:"Sebuah mikroskop kos rendah yang dibina daripada kanta telefon pintar dan tiub kadbod boleh membesarkan imej sehingga 30 kali, cukup untuk melihat sel tumbuhan.",
 soalan:[
 {j:"pilih",t:"Berdasarkan Rajah 2, sebuah kelab sains mahu membina kanta pembesar mudah daripada bahan terpakai. Bahan manakah paling sesuai sebagai kanta?",p:["Kanta cermin mata rabun jauh terpakai (kanta cembung)","Kanta cermin mata rabun dekat terpakai (kanta cekung)","Cermin datar yang dilapisi kertas legap","Kepingan kaca rata tanpa sebarang lengkungan"],b:0,u:"Rabun jauh dibetulkan dengan kanta cembung, jadi kanta itu sesuai digunakan sebagai kanta pembesar, sama seperti susunan objek pada u < f dalam Rajah 2."},
 {j:"pilih",t:"Murid ingin membina model mikroskop mudah dengan dua kanta cembung. Susunan panjang fokus manakah yang lebih sesuai untuk kanta objektif dan kanta mata?",p:["Kanta objektif berfokus pendek, kanta mata sedikit lebih panjang, kedua sangat pendek","Kanta objektif berfokus sangat panjang, kanta mata berfokus sangat pendek, seperti susunan teleskop itu","Kedua-dua kanta mesti mempunyai panjang fokus yang sama tepat sekali","Panjang fokus tidak penting selagi kedua-dua kanta jenis cembung sahaja"],b:0,u:"Mikroskop memerlukan objektif berfokus sangat pendek supaya objek yang sangat dekat dapat membentuk imej pertama yang besar, berbeza daripada teleskop yang objeknya jauh."},
 {j:"pilih",t:"Sebuah reka bentuk kanta pembesar poket perlu selesa dipegang oleh kanak-kanak dan tidak mudah tergores. Pertimbangan reka bentuk yang paling wajar ialah:",p:["Gunakan bingkai plastik ringan berpenutup boleh tarik, kanta plastik tahan calar","Gunakan kanta kaca setebal mungkin supaya lebih tahan lama walaupun lebih berat itu","Buang penutup kanta supaya kanak-kanak dapat menggunakannya dengan lebih pantas lagi","Gunakan kanta cekung supaya imej kelihatan lebih kecil dan selamat untuk mata kanak-kanak itu"],b:0,u:"Reka bentuk mesra pengguna mengambil kira keselamatan, ketahanan, dan keselesaan, bukan hanya prestasi optik semata-mata."},
 {j:"pilih",t:"Sebuah PIBG sekolah luar bandar mahu membina teleskop mudah untuk aktiviti kelab astronomi tetapi bajet sangat terhad. Cadangan paling wajar ialah:",p:["Guna kanta cermin mata terpakai disumbangkan dan tiub kadbod sebagai badan","Beli teleskop profesional termahal supaya kualiti imej yang terbaik dapat dijamin sekali","Tangguhkan aktiviti sehingga bajet mencukupi untuk membeli teleskop yang baharu","Gunakan cermin datar biasa menggantikan kedua-dua kanta cembung itu"],b:0,u:"Reka bentuk kos rendah yang berkesan menggunakan bahan mudah didapati tanpa mengorbankan prinsip optik asas — cermin datar tidak dapat menggantikan fungsi kanta cembung."},
 {j:"pilih",t:"Seorang murid membina teleskop mudah tetapi imej akhir kelihatan sangat gelap. Punca yang paling munasabah ialah:",p:["Diameter kanta objektif terlalu kecil, terlalu sedikit cahaya ditangkap","Kanta mata terlalu dekat dengan kanta objektif berbanding fo + fe itu","Panjang fokus kanta objektif terlalu panjang berbanding kanta mata itu","Kanta objektif diletakkan secara songsang berbanding kanta mata itu"],b:0,u:"Diameter kanta objektif menentukan jumlah cahaya yang ditangkap; kanta objektif yang kecil menghasilkan imej yang malap walaupun fokus tepat."},
 {j:"pilih",t:"Bagi memastikan reka bentuk kanta pembesar mudah dapat digunakan oleh murid kurang penglihatan tanpa menjadikan mereka berasa tersisih, langkah paling sesuai ialah:",p:["Sediakan kanta pembesar sebagai alat biasa untuk sesiapa sahaja di makmal","Berikan kanta pembesar hanya kepada murid berkenaan secara senyap semasa waktu rehat","Umumkan kepada seluruh kelas keperluan penglihatan murid itu sebelum menggunakannya","Minta murid itu duduk berasingan daripada rakan lain semasa menggunakan kanta itu"],b:0,u:"Reka bentuk inklusif yang menormalkan penggunaan alat bantu untuk semua orang mengurangkan rasa tersisih, sejajar dengan pertimbangan nilai sosial dalam reka cipta."},
 {j:"pilih",t:"Sebuah syarikat mahu menguji sama ada kanta kamera baharu mereka benar-benar lebih tajam berbanding model lama. Kaedah paling meyakinkan ialah:",p:["Ambil gambar objek uji sama, bandingkan ketajaman pada pembesaran sama","Tanya pendapat jurujual tentang kanta mana yang lebih baik","Bandingkan harga kedua-dua kanta sahaja","Perhatikan saiz fizikal kanta; kanta yang lebih besar dianggap lebih baik"],b:0,u:"Ujian terkawal dengan keadaan yang sama bagi kedua-dua kanta memberikan perbandingan yang adil dan boleh dipercayai."},
 {j:"pilih",t:"Nilaikan cadangan memasang kanta objektif teleskop yang jauh lebih besar diameternya tanpa menukar kanta mata. Apakah kesan paling mungkin?",p:["Imej menjadi lebih terang kerana lebih banyak cahaya, pembesaran tidak berubah","Pembesaran keseluruhan turut meningkat secara automatik mengikut diameter kanta itu","Imej menjadi lebih gelap kerana kanta besar menghalang lebih banyak cahaya itu","Kanta mata perlu turut membesar mengikut nisbah yang sama itu"],b:0,u:"Diameter kanta objektif menentukan kecerahan (jumlah cahaya ditangkap), manakala pembesaran ditentukan oleh nisbah panjang fokus fo/fe, dua perkara yang berasingan."}],
 bos:{j:"buka",
  t:"Kelab Sains sekolah awak ingin membina satu peralatan optik mudah (kanta pembesar, teleskop mudah, atau mikroskop mudah) menggunakan bahan kos rendah untuk pameran STEM sekolah rendah berdekatan.",
  arahan:"Nyatakan peralatan optik yang dipilih, kanta dan bahan yang diperlukan (nyatakan anggaran panjang fokus jika berkaitan), cara ia disusun, dan bagaimana awak memastikan ia selamat dan mudah digunakan oleh murid sekolah rendah.",
  u:"Jawapan TP6 yang kukuh menggabungkan prinsip optik (jenis kanta, panjang fokus yang sesuai, susunan) dengan pertimbangan praktikal seperti kos, keselamatan, dan kesesuaian untuk khalayak sasaran."}}

];

module.exports = {
  id:"t5b7", tingkatan:5, kod:"7.0 Cahaya dan Optik",
  tajuk:"Laluan Kanta",
  subtajuk:"Sains Ting. 5 · Bab 7 Cahaya dan Optik",
  spi:SPI,
  ulasan:{
   1:"{n} dapat mengingat kembali istilah asas optik kanta seperti paksi utama, pusat optik, titik fokus, jarak objek dan jarak imej. Langkah seterusnya ialah memahami bagaimana sinar sebenarnya membentuk imej, bukan sekadar menghafal takrifan.",
   2:"{n} memahami ciri imej yang terbentuk oleh kanta cembung dan kanta cekung pada jarak objek yang berbeza-beza, termasuk kes istimewa u = f. Perlu lebih banyak latihan mengaitkan rajah sinar dengan pengiraan sebenar sebelum bergerak ke TP3.",
   3:"{n} boleh mengaplikasikan rumus kanta nipis 1/f = 1/u + 1/v dan formula magnifikasi untuk menyelesaikan masalah pengiraan mudah bagi kanta cembung dan kanta cekung, serta memahami fungsi kanta objektif dan kanta mata. Galakkan mengaitkan pengiraan dengan situasi peralatan optik sebenar.",
   4:"{n} mampu menganalisis situasi optik yang lebih kompleks seperti pemilihan panjang fokus untuk teleskop dan mikroskop, dan sebab kamera telefon pintar direka dengan cara tertentu. Seterusnya latih menilai reka bentuk dan membuat keputusan berasaskan bukti.",
   5:"{n} dapat menilai kesahan kaedah eksperimen dan cadangan reka bentuk peralatan optik, disokong hujah berasaskan prinsip kanta. Sudah bersedia untuk tugasan reka cipta peralatan optik yang lengkap.",
   6:"{n} berjaya mereka cipta cadangan peralatan optik yang praktikal, lengkap dengan pertimbangan kos, keselamatan dan kesesuaian pengguna. Pencapaian cemerlang bagi bab ini.",
   tiada:"{n} belum menunjukkan bukti penguasaan yang mencukupi bagi bab Cahaya dan Optik. Cadangan: ulang aktiviti hentian pertama dengan bimbingan rakan sebaya, memberi tumpuan kepada istilah asas kanta."
  },
  lampiran:{ jauh:R_JAUH, dekat:R_DEKAT, cekung:R_CEKUNG, teleskop:R_TELESKOP },
  aras:ARAS
};
